### ISSUE TITLE
Questionnaire designer with simple question

### ISSUE THREAD

**Issue by nditada** [instedd/ask#1]
- [x] User can press a "add numeric question"
- [x] User can enter a question name

**Comment by juanboca** [comment]
Solved on:
https://github.com/instedd/ask/commit/adcc5030800ccc3156a838ee89d0e436c3b6201c
https://github.com/instedd/ask/commit/fdf3b01df72ecd5d7a330d34599983f6f5f5db3d
https://github.com/instedd/ask/commit/9560f6048a31afec1f1204cf73b5b2218148d904
