### ISSUE TITLE
Unable to Rename Survey

### ISSUE THREAD

**Issue by adam704a** [instedd/ask#100]
According to what is in the 0.1.0 (Alder) release plan, rename survey should be working.  I can't seem to get it to work though.

I have tried surveys in my project, such as this one: 
http://ask-stg.instedd.org/projects/17/surveys/48/edit/questionnaire

**Comment by waj** [comment]
In 0.2 the rename can be done from the title bar. I'm closing this because 0.2 is coming soon and we're not maintaining 0.1 anymore.
