### ISSUE TITLE
Display disposition information along with quotas on respondents table

### ISSUE THREAD

**Issue by nekron** [instedd/ask#1001]
Same as the multiple questionnaire version, but with the reference of the quotas.

**Comment by asterite** [comment]
@nekron Design for this?

**Comment by nekron** [comment]
https://projects.invisionapp.com/d/main#/console/8374235/232431824/preview

**Comment by nekron** [comment]
Depends on #965

**Comment by asterite** [comment]
I still don't understand. Under each quota we should display each disposition ungrouped? Or grouped, and under each group each disposition?

**Comment by fgasperij** [comment]
The table should have the quotas as columns and the dispositions as rows. The dispositions must appear grouped as in the comparison version.

**Comment by mmuller** [comment]
When using numeric steps to define the quotas it doesn't work (version b4a2461).

http://recordit.co/Mc43LKCOEk

<img width="1517" alt="screen shot 2017-06-16 at 3 25 58 pm" src="https://user-images.githubusercontent.com/518152/27240550-97c3a202-52ab-11e7-891b-5c03bc41da77.png">

**Comment by pmallol** [comment]
Ok in Version: 0.10.0-dev-9c51b93 (build 2566)
