### ISSUE TITLE
[survey] Display a hint to indicate that it's paused due to scheduling

### ISSUE THREAD

**Issue by nekron** [instedd/ask#1004]
Display a text like: "Next call in 12hs, at 9am PST" in survey overview.

Use 'access_time' icon in survey index. and display a text like: "Scheduled to 9am PST"

**Comment by asterite** [comment]
One question: 

The sample text is "Next call in 12hs". What happens if it's in 49hs? Should we say "in 49hs" or "in 2 days and 1 hour"? I personally think it's better just to say "Next call at time + date" in the user's timezone (the one in the browser) to avoid confusion and to simplify things.

**Comment by nekron** [comment]
I think that having the time span of the next call is useful if you are failing to realise that the one thing that's preventing the call to be made is the schedule.

We can just simply use the same behavior of the last saved at but for dates in the future.

**Comment by mmuller** [comment]
Working properly in version cc5d3df
