### ISSUE TITLE
[Survey] Have a single final state

### ISSUE THREAD

**Issue by waj** [instedd/ask#1012]
Let's unify "completed" and "cancelled" states into a single final state "terminated". Add an "exit_code" field indicating the reason of the survey termination, and an "exit_message" to describe error details.

0 - successfully completed
1 - cancelled by user

**Comment by asterite** [comment]
@waj Should we add a migration to existing surveys?

**Comment by fgasperij** [comment]
The existing surveys will be updated on the same migration that the exit fields are added because if not they would get to an inconsistent state.
