### ISSUE TITLE
[Survey] Failed respondents not being recorded in CSVs and Respondents tab

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#1016]
Related to #762 
Version: 0.9.0 (build 2357)

Respondents that appear as 'Failed' in Survey Overview due to the following error in verboice:
 
```State: Failed
Failure information: Unknown error. Interworking, unspecified (127)
```

show up in CSVs as it follows:
- Disposition 'Failed' in Survey Results CSV
- 'Queued' in Disposition History CSV
- Disposition 'Queued' in Interactions CSV

- Incentives CSV is empty
- Disposition column in Respondents tab is also empty

![screen shot 2017-05-24 at 2 24 23 pm](https://cloud.githubusercontent.com/assets/9214460/26416570/b88011f0-408c-11e7-8a5a-e51c7de8071f.png)
![screen shot 2017-05-24 at 2 25 06 pm](https://cloud.githubusercontent.com/assets/9214460/26416596/d5aab00a-408c-11e7-8c2f-44dbc641abb6.png)
![screen shot 2017-05-24 at 2 25 31 pm](https://cloud.githubusercontent.com/assets/9214460/26416612/e403bf0c-408c-11e7-8832-f4a1a9a2c38c.png)

[762-csv.zip](https://github.com/instedd/ask/files/1026432/762-csv.zip)

Expected:
- Disposition column in Respondents tab should display 'Failed'
- No CSV should show 'Queued' as a Disposition

**Comment by nditada** [comment]
@pmallol the expectation that "No CSV should show 'Queued' as a Disposition" is incorrect. If the survey stops for any reason, respondents that are in disposition "Queued" should remain in that disposition.

I think the main issue here is that there is no coherence between in the way dispositions are reported in the UI and the CSVs.

**Comment by mmuller** [comment]
When testing this issue verify if the `Breakoff` is included in the `Disposition history` CSV.

**Comment by mmuller** [comment]
Working properly in version 51b2425
