### ISSUE TITLE
Archive/Delete Questionnaire

### ISSUE THREAD

**Issue by adam704a** [instedd/ask#1018]
In the same way that someone can delete a survey, we should be able to delete a questionnaire. We need this to avoid clutter in the UI. The Zambia this is becoming an issue (https://surveda-zambia.org/projects/2/questionnaires)

**Comment by adam704a** [comment]
@nditada can this be added to https://github.com/instedd/ask/milestone/23

**Comment by mmuller** [comment]
Working properly in version 55aca59
