### ISSUE TITLE
Add more description to "Something went wrong" error

### ISSUE THREAD

**Issue by adam704a** [instedd/ask#1019]
Provide a  better way to diagnose the "Something went wrong" error from a tester/user perspective. We see this message from time to time and it would be nice to a little more about what is going on so that we can report the problem more accurately. 

Sort of related to https://github.com/instedd/ask/issues/524

**Comment by waj** [comment]
Let's do two things:
- [ ] Add a unique identifier of the error so we can match the issue with the log in Sentry
- [ ] Show a "details" section that the user can expand to see the error

**Comment by waj** [comment]
https://projects.invisionapp.com/d/main#/console/8374235/237461973/preview
https://projects.invisionapp.com/d/main#/console/8374235/237461972/preview

**Comment by mmuller** [comment]
Working properly in version 4010cbf
