### ISSUE TITLE
Creating a project with a very very long name gives a JS error

### ISSUE THREAD

**Issue by asterite** [instedd/ask#102]
For example with 610 chars

**Comment by waj** [comment]
Limit the allowed length of the title component the allowed size in the database

**Comment by juanboca** [comment]
The limit on the DB is 255 chars. But with a name that long, the UI doesn't look good, even in 1920x1080px. Maybe we would want to limit it to a more reasonable size, or limit the size only when displaying the label. 

This is how the label looks with 255 chars:
![screen shot 2016-10-24 at 9 42 29 am](https://cloud.githubusercontent.com/assets/488553/19646184/a75074b6-99ce-11e6-9097-e193885cbf0a.png)

And this is how the input looks:
![screen shot 2016-10-24 at 9 44 47 am](https://cloud.githubusercontent.com/assets/488553/19646185/a7526bfe-99ce-11e6-873d-4dc76fc615ad.png)

**Comment by juanboca** [comment]
Created #174 to solve the style issues
