### ISSUE TITLE
Mobile web "Title" and "Survey already taken" message not being imported

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#1021]
Version: 0.9.0 (build 2357)

1. Export a complete questionnaire on Mobile web mode 
2. Create a new questionnaire
3. Import questionnaire exported in step 1.

Obtained:
Fields 'Title' and 'Survey already taken' appear blank, and the questionnaire is then incomplete

[443.zip](https://github.com/instedd/ask/files/1033026/443.1.zip)

**Comment by asterite** [comment]
The fix is very simple. What's the milestone for this?

**Comment by mmuller** [comment]
Working properly in version cc5d3df
