### ISSUE TITLE
[Survey] Fallback mode is not working properly.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#1033]
Found in version 0.9.2 (build 2424)

Preconditions:
There is a Questionnaire `Foo`.
`Foo` has two modes (`SMS` and `Phone call`).

Reproduce steps:
Create a Survey.
Select the Questionnaire `Foo`.
Select `Phone call` as `Primary mode`.
Try to select `No fallback` as `Fallback mode`. 

Obtained:
`SMS` is selected as `Fallback mode`. 
`No fallback` cannot be selected as `Fallback mode`.

<img width="912" alt="screen shot 2017-05-31 at 3 51 06 pm" src="https://cloud.githubusercontent.com/assets/518152/26648479/fcdbfac6-4618-11e7-9297-5cc9e61e73f1.png">

**Comment by juanboca** [comment]
This issue is related with #861 . 
Please check that everything still works as it was supposed from the specification on that issue.

**Comment by mmuller** [comment]
Working properly in version 51b2425

<img width="797" alt="screen shot 2017-06-02 at 1 50 22 pm" src="https://cloud.githubusercontent.com/assets/518152/26735937/7529bc3e-479a-11e7-9c28-f02578d006d1.png">
