### ISSUE TITLE
[Survey] In the Questionnaires comparison the Questionnaires name is displayed as `Untitled`.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#1047]
Found in version 0.9.3

Preconditions:
There are two Questionnaires (`Foo` and `Bar`).

Reproduce steps:
Create a Survey.
Enable the Questionnaires `Comparison`.
Select the Questionnaires `Foo` and `Bar`.
Complete the wizard.
Start the Survey.
Click on the `Settings` tab.
Observe the Questionnaires name.

Obtained:
The Questionnaires name is displayed as `Untitled` within the Survey settings.

Expected:
The Questionnaires name should be displayed within the Survey settings.

Screenshot:
<img width="1472" alt="screen shot 2017-06-05 at 11 08 38 am" src="https://cloud.githubusercontent.com/assets/518152/26787164/63005ddc-49df-11e7-8faa-fe98342eccfe.png">

**Comment by pmallol** [comment]
Ok in Version: 0.10.0-dev-893451e (build 2561)
