### ISSUE TITLE
[Survey]The quotas defined by the user are not displayed in the Survey settings.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#1049]
Found in version 9115861

Reproduce steps:
Create a Survey.
Define some `Quotas`.
Start the Survey.
Click on the `Settings` tab.

Obtained:
The quotas defined by the user are not displayed in the Survey settings.

Expected:
The quotas defined by the user should be displayed in the Survey settings.

Screenshot:

<img width="1372" alt="screen shot 2017-06-05 at 1 36 18 pm" src="https://cloud.githubusercontent.com/assets/518152/26793333/fd7a357c-49f3-11e7-969e-3428b41aac88.png">

<img width="1353" alt="screen shot 2017-06-05 at 1 36 12 pm" src="https://cloud.githubusercontent.com/assets/518152/26793334/fd7b9a20-49f3-11e7-977f-c05759786b3c.png">

**Comment by pmallol** [comment]
Ok in Version: 0.10.0-dev-9c51b93 (build 2566)
