### ISSUE TITLE
[Surveys] Cards are not correctly aligned in the Surveys listing.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#1050]
Found in version cc5d3df

Preconditions:
There are some Surveys already `Completed`.
There is at least a Survey still `Running`.

Reproduce steps:
Navigate to the Surveys listing.
Observe the cards displayed there.

Obtained:
Cards are not correctly aligned in Surveys index.

Screenshot:
<img width="1349" alt="screen shot 2017-06-06 at 11 24 16 am" src="https://cloud.githubusercontent.com/assets/518152/26834422/addc49ca-4aab-11e7-939a-4315d4dfff5a.png">

**Comment by jkicillof** [comment]
When a survey is out of time schedule don't show the _Running_ label, leave only de _Scheduled at..._ label in green

**Comment by mmuller** [comment]
Working properly in version c4efa94
