### ISSUE TITLE
Apply styling for expandable rows in survey overview

### ISSUE THREAD

**Issue by waj** [instedd/ask#1055]
https://projects.invisionapp.com/share/3U8BARPXJ#/screens/232431824

**Comment by pmallol** [comment]
Everything looks good except that the numbers displayed when expanding each row should also be colored to differentiate information easily. As for Version: 0.10.0-dev-55aca59 numbers appear in grey:
![screen shot 2017-06-09 at 5 19 46 pm](https://user-images.githubusercontent.com/9214460/26993462-7f9ae2ca-4d39-11e7-850b-582cfca40627.png)

**Comment by pmallol** [comment]
Ok in Version: 0.10.0-dev-b4a2461 (build 2538)
