### ISSUE TITLE
[Survey] There is no mention to the modes comparison in the Survey's overview.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#1057]
Found in version:
0d1e2db

Reproduce steps:
Create a Survey.
Enable the `Modes` comparison.
Complete the wizard.
Launch the Survey.
Go to the Survey's overview.
Observe the Dispositions table.

Obtained:
There is no mention to the modes comparison.

Expected:
The table should have a column for each mode.

Screenshot:
<img width="1438" alt="screen shot 2017-06-07 at 11 38 28 am" src="https://user-images.githubusercontent.com/518152/26884309-db08e0b4-4b75-11e7-87cc-c62d41a6be43.png">
<img width="1376" alt="screen shot 2017-06-07 at 11 38 15 am" src="https://user-images.githubusercontent.com/518152/26884311-dc18fe6c-4b75-11e7-87be-02c71955ceda.png">

**Comment by mmuller** [comment]
Design proposal: https://projects.invisionapp.com/d/main#/console/8374235/232431824/preview

**Comment by pmallol** [comment]
Ok in Version: 0.10.0-dev-9c51b93 (build 2566)
