### ISSUE TITLE
[Survey] The total count of respondents for each comparison condition is not displayed on the Survey's overview.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#1058]
Found in version: 0d1e2db

Preconditions:
There are two Questionnaires (`Foo` and `Bar`).

Reproduce steps:
Create a Survey.
Enable the Questionnaires comparison.
Select the Questionnaires `Foo` and `Bar`.
Complete the wizard.
Launch the Survey.
Navigate to the Survey's overview.
Observe the total count for each comparison condition.

Obtained:
The total count of respondents for each comparison condition is not displayed on the Survey's overview.

Expected:
The total count of respondents for each comparison condition should be displayed within the Dispositions group.

Screenshots:
Obtained:
<img width="1378" alt="screen shot 2017-06-07 at 1 58 23 pm" src="https://user-images.githubusercontent.com/518152/26891412-4ac6c0dc-4b8b-11e7-9768-559b8cc1aa53.png">

Expected:
<img width="1370" alt="screen shot 2017-06-07 at 2 02 15 pm" src="https://user-images.githubusercontent.com/518152/26891411-4ac1fd40-4b8b-11e7-853f-c32572e2523d.png">

**Comment by nekron** [comment]
Fixed in: e0c9a5644722e899e5841ac2de8c2c2df5b08a2e

**Comment by mmuller** [comment]
Working properly in version c4efa94
