### ISSUE TITLE
Unexpected error in simulation view.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#1061]
Found in version: 55aca59

Reproduce steps:
Navigate to the Questionnaire `Foo`.
Click on the `Test Sandbox` icon.
Fill the fields.
Press `Send`.
As respondent answer some questions.
Go to the Simulation view

Obtained:
An unexpected error is thrown.

Error log: https://sentry.io/instedd/ask-stg/issues/169759417/

**Comment by pmallol** [comment]
Ok in Version: 0.10.0-dev-9c51b93 (build 2566)
