### ISSUE TITLE
[Sandbox] Content div should not have scroll.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#1062]
Found in version 55aca59

Preconditions:
The Project `Foo` has more than 3 channels provided by Nuntium.
The Questionnaire `Bar` has enabled the `SMS` mode.

Reproduce steps:
Navigate to the Questionnaire `Bar`.
Click on the `Test Sandbox` icon.
Click on the arrow to display the Channels option.
Scroll to display the last option.

Obtained:
The Content div is scrolled.

Expected:
Only the Select element should have scroll.

<img width="1000" alt="screen shot 2017-06-08 at 1 39 33 pm" src="https://user-images.githubusercontent.com/518152/26940124-f01c8e9e-4c4f-11e7-9e1a-5b84debc6ec6.png">

**Comment by waj** [comment]
@Mscebba The problem here is that the dropdown cannot escape from the modal window. Is there an easy way to solve this?

**Comment by mmuller** [comment]
Working properly in version b4a2461
