### ISSUE TITLE
Cut off rules step: no invalid input feedback

### ISSUE THREAD

**Issue by fgasperij** [instedd/ask#107]
1. Input '----' on the cut off rule input.
2. Click on the submit button.

There's no feedback that the value is invalid.

**Comment by asterite** [comment]
Additionally, right now negative numbers can be written and no error is given

**Comment by waj** [comment]
Allow only values between 1 and the maximum value allowed by the database.

**Comment by asterite** [comment]
@waj I think in addition to that the cutoff rule shouldn't be greater than the number of respondents. Problem is, you can specify the cutoff rules **before** uploading the respondents
