### ISSUE TITLE
Rename output in reports for "failed:busy" errors

### ISSUE THREAD

**Issue by nditada** [instedd/ask#1070]
Verboice is "copying" a Twilio error-code for mid-call hangups, which is to report "failed:busy". Report files exported from Ask should say "user hangup" and not "failed:busy". 

For reference: https://github.com/instedd/ask/issues/602

cc @waj

**Comment by waj** [comment]
Note that we only need to handle the cases where the status is "failed" and the detail is "busy".

**Comment by mmuller** [comment]
Working properly in version 73cc296
