### ISSUE TITLE
Rename "failed:*" output in file reports 

### ISSUE THREAD

**Issue by nditada** [instedd/ask#1072]
Ask is reporting Verboice "errors" named as "failed:*" into the exported file reports. Those errors are being confused with "failed" status. Since those cases do not necessarily have a failed disposition, those can be perceived as mismatches. 

For these:
"failed: User alerting, no answer (ISDN:19)"
"no-answer"
"failed: Call Rejected (ISDN:21)"
"failed: Busy":

It seems like just removing the "failed:" prefix should work well. 

cc @waj

**Comment by mmuller** [comment]
Working properly in version 73cc296
