### ISSUE TITLE
[Survey] Percentages are not expressed properly in overview when the Survey has Quotas.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#1078]
Found in version 55aca59

When the Survey doesn't have Quotas the percentages are expressed as decimals in the Survey overview. But if the Survey has Quotas the percentages don't include decimals.

When there are Targets with a lot of respondents (~1k) the percentages are not correct.

<img width="1418" alt="screen shot 2017-06-12 at 2 47 48 pm" src="https://user-images.githubusercontent.com/518152/27047428-7aacb274-4f7e-11e7-939e-c2cec26ff32b.png">

**Comment by waj** [comment]
Closing this, because this page has drastically changed when the survey has quotas
