### ISSUE TITLE
[Survey] Percentage of target completed is not easy to calculate in overview's chart.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#1079]
Found in version: 55aca59 

Now we are showing something like `0.009999000099990002%` as target completed. That number doesn't represent useful information.

In my opinion we should display something like `0.009%`.

<img width="1348" alt="screen shot 2017-06-13 at 9 05 19 am" src="https://user-images.githubusercontent.com/518152/27081590-7674c16c-5017-11e7-81d7-425e56f23dab.png">

**Comment by waj** [comment]
Let's use two decimal places

**Comment by mmuller** [comment]
Working properly in version b4a2461
