### ISSUE TITLE
Invitation and account email UI details

### ISSUE THREAD

**Issue by edjez** [instedd/ask#1082]
- [ ] Aspect ratio of logo in collaboration and confirmation invite

- [ ] "Ask" in title of email account confirmation

![image](https://user-images.githubusercontent.com/1182549/27105900-17e267c4-5046-11e7-89d5-e8626eb04d11.png)
![image](https://user-images.githubusercontent.com/1182549/27105951-4b74c1ae-5046-11e7-9c0f-b4a72c44ecc8.png)

**Comment by mmuller** [comment]
Working properly in version 73cc296
