### ISSUE TITLE
[Survey] Color for quotas is not working

### ISSUE THREAD

**Issue by lmatayoshi** [instedd/ask#1086]
Steps to reproduce:
- Create a questionnaire with a multiple choice step containing 3 options an another one containing 2 options (3 x 2 = 6 quotas are required to reproduce the error)
- Create a survey, selecting the previous one as questionnaire
- Select quotas for both multiple options and launch the survey

Expected:
- One color is asigned for each quota in the survey overview

Obtained:
- There are quotas with no visible colors

![quotas-colors-not-working](https://user-images.githubusercontent.com/8591752/27149978-e0043108-511b-11e7-88bd-9a7dfd1fdb64.png)

**Comment by mmuller** [comment]
Working properly in version 6e66205
