### ISSUE TITLE
[Questionnaires] questionnaires already used in a survey cannot be removed.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#1089]
Found in version b4a2461

Preconditions:
There is a Questionnaire `Foo` created since 30 days ago.

Reproduce steps:
Navigate to the Questionnaires listing.
Press the icon to delete the Questionnaire `Foo`.

Obtained:
The Questionnaire cannot be removed
An unexpected error is thrown.

Error log:
```Unhandled promise rejection
Error ID:
582d5cec35164f33a5684c92efee3be9
Call stack
Error: Unhandled promise rejection
    at https://surveda-stg.instedd.org/js/app-f86cc5b3e4fadb9cb88854c89262afe1.js?vsn=d:91:349165
    at t (https://surveda-stg.instedd.org/js/app-f86cc5b3e4fadb9cb88854c89262afe1.js?vsn=d:119:109635)
```

Might be related with #1085

**Comment by waj** [comment]
Here's the reason: https://sentry.io/instedd/ask-stg/issues/295231376/

**Comment by waj** [comment]
Actually the problem occurs with questionnaires that were used in a survey at least once. I'll change the title of the issue to reflect this.

**Comment by mmuller** [comment]
Working properly in version 8e75560
