### ISSUE TITLE
[Permissions] 'Change color scheme' option is not hidden for Readers.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#1092]
Found in version: b4a2461

Preconditions:
- There is a Project `Foo`.
- `Foo` is shared with a Reader user.

Reproduce steps:

- As Reader user navigate to the Project `Foo`.
- Expand the Project options menu.
- Click on `change color scheme`.

Obtained result:

- The app redirects to the Projects listing.
- Readers cannot change the color scheme.

Expected:
- Since Readers should not edit the Project the option to `change color scheme` should be hidden for them.

**Comment by pmallol** [comment]
Ok in Version: 0.10.0-dev-8e75560 (build 2581)
