### ISSUE TITLE
[Survey] Unexpected error if an experimental condition has 0%.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#1094]
Found in version: b4a2461

Preconditions:

- There are two Questionnaires `Q1` and `Q2`.

Reproduce steps:

- Create a Survey.
- Enable the comparison between Questionnaires.
- Select `Q1` and `Q2` as Questionnaires.
- Don't fill an experimental condition. It will be stored as 0%.
- Complete the wizard.
- Start the Survey.

Obtained result:

- There is no error displayed in the UI.
- The following error is logged: https://sentry.io/instedd/ask-stg/issues/265485210/

Screenshot:
<img width="1421" alt="screen shot 2017-06-15 at 3 57 01 pm" src="https://user-images.githubusercontent.com/518152/27197354-46276bf8-51e4-11e7-896b-8fc54e8d411b.png">

**Comment by pmallol** [comment]
As for Version: 0.10.0-dev-9c51b93 (build 2566) there's still no error showing up in the UI. I'm not really sure what I should expect when verifying this ticket, @nekron can I verify this is there's no error logging on Sentry anymore?

**Comment by nekron** [comment]
The fix was to prevent the runtime from crashing and treating the 0% properly, even if stored as null. 

It should be safe to say that the ticket is fixed if there is no error reported on sentry anymore, and the survey worked as expected.

**Comment by pmallol** [comment]
Ok in Version: 0.10.0-dev-8e75560 (build 2581)
