### ISSUE TITLE
Export phone numbers as string in CSV

### ISSUE THREAD

**Issue by nditada** [instedd/ask#1099]
So that excel does not remove the leading zeroes.

**Comment by waj** [comment]
There is no such thing as data types in CSV files. Values can be quoted but that's just a way to include commas inside the values.

The attached file has two columns with the same value, with and without quotes. I don't have Excel to test. Google Spreadsheets have the same behavior for both values.

[numbers.csv.zip](https://github.com/instedd/ask/files/1092785/numbers.csv.zip)

A workaround is to tell Excel not to interpret the values as numbers and [import the desired column as text](https://answers.microsoft.com/en-us/msoffice/forum/msoffice_excel-mso_other/keeping-leading-zeros-in-csv-file-format/236e23cb-9a00-4c30-bd2b-267d7a3140ac) instead.

**Comment by nditada** [comment]
I was hoping that quoting would have lead Excel to not treat the numbers as text, but you are right, it's doing the same with both columns.
