### ISSUE TITLE
Problem with CSV encoding?

### ISSUE THREAD

**Issue by nditada** [instedd/ask#1100]
I'm quickly guessing this file is in UTF-16. It's failing when you try to upload it: "SyntaxError: Unexpected token I in JSON at position 0"
[Sample Pilot Test 11b.csv.zip](https://github.com/instedd/ask/files/1089179/Sample.Pilot.Test.11b.csv.zip)

Saving it as UTF-8 solved the problem.

**Comment by waj** [comment]
@nditada the file attached seems to be UTF-8 already. Did you upload the right file? I don't have any issues using that csv file (in my 0.10 dev environment).

**Comment by nditada** [comment]
Let's try again. I still see this failing in Zambia
[Sample Pilot Test 11b.csv.zip](https://github.com/instedd/ask/files/1095837/Sample.Pilot.Test.11b.csv.zip)

**Comment by mmuller** [comment]
Working properly in version 73cc296
