### ISSUE TITLE
[Questionnaire] There's a comma in layout when the 'Sandbox' button appears

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#1102]
Found in Version: 0.10.0-dev-9c51b93 (build 2566)

1. Create a questionnaire
2. Complete all required fields so that the 'Test Sandbox' button appears on top right corner

Obtained:
There's a comma floating on top of 'Primary language' section

![screen shot 2017-06-22 at 12 19 48 pm](https://user-images.githubusercontent.com/9214460/27441970-5db464b8-5745-11e7-8e93-2769b669369a.png)
![screen shot 2017-06-22 at 12 20 07 pm](https://user-images.githubusercontent.com/9214460/27441969-5db3e718-5745-11e7-92cd-08111532614b.png)

**Comment by nekron** [comment]
Fixed with 1f3378d874b11fc509b0b4dddf98573d41f6934d

**Comment by pmallol** [comment]
Ok in Version: 0.10.0-dev-8e75560 (build 2581)
