### ISSUE TITLE
[Survey] Card listing breaks when there's an scheduled survey

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#1106]
Found in Version: 0.10.0-dev-9c51b93 (build 2566)
Similar to #1050 

![screen shot 2017-06-22 at 6 09 19 pm](https://user-images.githubusercontent.com/9214460/27456319-04e927ba-5777-11e7-9575-c3dfbd8acb25.png)

**Comment by mmuller** [comment]
Working properly in version aaa1c34
