### ISSUE TITLE
Questionnaire editor showing inconsistent validation errors

### ISSUE THREAD

**Issue by edjez** [instedd/ask#1112]
Juniper  Version: 0.10.2 (build 2599) on Chrome
https://surveda-demo.instedd.org/projects/2/questionnaires/1/edit

Qx Editor is showing orange dots next to Language and Mode, but no error is seen in questionnaire settings or questions.

![image](https://user-images.githubusercontent.com/1182549/27803621-3f6e4ac6-5fdf-11e7-8bba-60b372c4d6a7.png)

**Comment by waj** [comment]
This should be fixed now. Please reopen if necessary.
