### ISSUE TITLE
[Questionnaire] Highlight and delete step message; text reappears

### ISSUE THREAD

**Issue by steesdale** [instedd/ask#1118]
I wrote an IVR message.  I decided I wanted to delete it all; highlighted the text with my mouse by holding shift and selecting at the beginning of the sentence; and hit delete.  the text disappears as expected.

I then clicked off the message line, and the text reappeared.  

at surveda.instedd.org  on Version: 0.9.5 (build 2505)

![bug1](https://user-images.githubusercontent.com/3987608/27920507-60fa25a4-623a-11e7-982e-ca0f2a99b423.gif)

**Comment by mmuller** [comment]
@steesdale I can't reproduce this issue in version 0.10.0. It should be already fixed.
