### ISSUE TITLE
The respondent list upload accepts letters on the phone numbers.

### ISSUE THREAD

**Issue by fgasperij** [instedd/ask#112]
The upload of respondents doesn't validate that the telephone numbers have only numbers.

**Comment by waj** [comment]
We should allow some other legal characters as well, like whitespaces, `+`, `(`, `)` and `-`
In the future we might want to also allow to reach respondents by email, but so far we only have phone numbers.

**Comment by lmatayoshi** [comment]
https://projects.invisionapp.com/d/main#/console/8374235/200241322/preview
