### ISSUE TITLE
Script is missing in reset password form

### ISSUE THREAD

**Issue by nekron** [instedd/ask#1124]
Steps to reproduce:
- Send reset password email
- Enter the link to reset the password

Error displayed:

The associated script is not loaded and the labels are not animated, overlapping with the input.

<img width="1438" alt="screen shot 2017-08-02 at 5 40 24 pm" src="https://user-images.githubusercontent.com/957103/28894059-0145f072-77aa-11e7-8787-b6fbd378f93f.png">

**Comment by mmuller** [comment]
Working properly in version be284eb
