### ISSUE TITLE
Contact attempts may not have been captured in Interactions file

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#1127]
Reported by Charles:
"In Zambia pre-test, there were 35 cases who should have been contacted by IVR (according to Survey Response file), but were contacted by SMS first (according to Interactions file). Martin suggested these cases were actually contacted by IVR, but the contact attempts may not have been captured in Interactions file. It is POSSIBLE that respondentid 0003b4ec094d is an example. Not positive though"

**Comment by nditada** [comment]
Issue here was:
1. Surveda scheduled the call in Verboice (but right not it's not logging that as an interaction).
2. Verboice call failed.
3. Verboice callback to Surveda failed (timeout or other, we can't determine now).
4. Surveda timeouted on waiting for the callback, contacted Verboice to check status and continued with the survey.

Solution is:
1. Add an additional log in the interaction when Surveda schedules the call in Verboice.
2. Log a failed attempt when Surveda checks for status of a call in Verboice (after no callback arrived).
