### ISSUE TITLE
The number of contacted cases is not displayed consistently

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#1128]
Reported by Charles:
"Zambia pre-test Response data file shows 34,854 cases had statuses other than Queued or Registered (i.e., they were contacted). But the Overview screen in the UI says 36,610 cases were contacted. Which is the right one?.
We must have an easy way to determine the number of cases we contacted. This is needed for accurate response rate calculations."

**Comment by waj** [comment]
Contacted cases is currently showing the number of respondents with `state != 'pending'`. It should show the number of respondents with `disposition NOT IN ('queued', 'registered') instead.

**Comment by nditada** [comment]
My response to Charles:

> You are correct, the issue is in the use of the word "Contacted" in that part of the UI, we are not using it in alignment with the definition for dispositions. In fact, I think that word has been there since before we even agreed on what dispositions we would have and which names they would take. 
> We'll adjust this in the next round of modifications to that screen.

**Comment by nditada** [comment]
Original conversation: https://mobilesurveys.freshdesk.com/helpdesk/tickets/38

**Comment by mmuller** [comment]
Working properly in version 5abc942
Now `Queued` and `Registered` are not included in the `Respondents contacted` group.
