### ISSUE TITLE
IDs are not consistent between Interactions and Responses files.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#1130]
Reported by Charles:
"I see 1,756 cases that were not in the Interactions file, but are in the Survey Response file (i.e., they have a variant)."

**Comment by waj** [comment]
There are exactly 1756 cases with disposition "queued" but the internal state is "cancelled". Those cases were enqueued in Verboice but the Survey was stopped before Verboice performed the calls (there was no contact with the respondents).

**Comment by nditada** [comment]
Should be solved by #1127
