### ISSUE TITLE
Long survey name

### ISSUE THREAD

**Issue by fgasperij** [instedd/ask#114]
When the survey name is long it overflows its card at the survey index.

**Comment by fgasperij** [comment]
<img width="1002" alt="screen shot 2016-10-13 at 3 06 42 pm" src="https://cloud.githubusercontent.com/assets/1685226/19360908/dc651e52-9156-11e6-8525-7823fbe25d02.png">

**Comment by waj** [comment]
Quite similar to #108. Closing as duplicate.
