### ISSUE TITLE
Increase the default batch size

### ISSUE THREAD

**Issue by nditada** [instedd/ask#1152]
Currently, if there are no quotas or cutoff target, the batch size is set to 1000. That number is too low for any meaningful test, so we should increase it to 10,000.

Original conversation: https://mobilesurveys.freshdesk.com/helpdesk/tickets/40

**Comment by waj** [comment]
The default was actually much lower (10) but it was set to 1000 in the server at Zambia. I just upgraded the default to 10k and also set the same value in the server.

**Comment by mmuller** [comment]
Working properly in version be284eb
