### ISSUE TITLE
Do more to convey the significance of stopping a survey.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#1157]
Reported by Adam Preston:

> "Stop survey" confirmation should also include a warning like "You cannot restart the survey" - i.e., you can't go back, this is final. This could be a huge stumbling block for people. Right now, the user is just asked to confirm they want to stop.
Relatedly, I think this should be called "Cancel Survey." That would make the irreversible point more clear. It would also be more consistent with other languages - "cancelled" shows up in the survey overview status after you STOP a survey. Also, cases in the data file are listed in the "canceled" disposition after you hit STOP.

Reference: https://mobilesurveys.freshdesk.com/helpdesk/tickets/52

**Comment by nditada** [comment]
Text for the message: "Once you stop the survey, all invitations will be halted immediately. Respondents who are currently answering the survey will be cut off. Once you stop, you cannot restart"

**Comment by jkicillof** [comment]
https://projects.invisionapp.com/d/main#/console/8374235/256870945/comments/87613463

**Comment by mmuller** [comment]
Working properly in version 44b6d5a
