### ISSUE TITLE
During the first day of survey, the chart doesn't draw anything

### ISSUE THREAD

**Issue by waj** [instedd/ask#117]
Even with some completed respondents, there is still no chart displayed. The X axis shows a "09 PM" that is partially off the bounds.

<img width="582" alt="screen shot 2016-10-13 at 3 25 52 pm" src="https://cloud.githubusercontent.com/assets/22697/19361744/353fc6c8-915a-11e6-8f37-d7e4be9946aa.png">

**Comment by waj** [comment]
@jkicillof what do you think we should display when there is little o no data yet? Should the chart have a X-axis with smaller steps (hours)? No chart at all?

**Comment by jkicillof** [comment]
https://projects.invisionapp.com/d/main#/console/8374235/198000671/preview

**Comment by waj** [comment]
Implemented long time ago
