### ISSUE TITLE
Consider voicemail answers as "Contacted"

### ISSUE THREAD

**Issue by nditada** [instedd/ask#1171]
If a call gets picked up, even if there's no interaction (picked up by a voicemail), lets considered that as disposition "Contacted".

**Comment by adam704a** [comment]
Also, no answer should be contacted too.

**Comment by adam704a** [comment]
Discussed with Nico, no answer is a code from MNOs that cannot be relied upon. So,  please disregard my last comment.

**Comment by nekron** [comment]
This is the application behavior since 0.9.0 (https://github.com/instedd/ask/commit/8f2b4fe70#diff-5de71ff0aa29249e2f49bf22956ce6a9R235)

Just verified that it's still working on 0.12 on our staging server.

**Comment by mmuller** [comment]
Working properly in version 44b6d5a
