### ISSUE TITLE
[Questionnaire] Clicking on the SMS Settings links to top of the screen

### ISSUE THREAD

**Issue by adam704a** [instedd/ask#1174]
Its happening here:
https://surveda-morocco.org/projects/3/questionnaires/72/edit

This is happening with Chrome.

**Comment by mmuller** [comment]
@adam704a I couldn't reproduce this issue.
What I do:
I open the Questionnaire.
I click on `SMS Settings`.

What I obtain:
The SMS settings are displayed.
The page doesn't scroll up.

**Comment by adam704a** [comment]
This is happening to me and Leenisha here at RTI.
![jump](https://user-images.githubusercontent.com/276936/31343807-f2a16372-accd-11e7-8740-0d1cf712e094.gif)

**Comment by mmuller** [comment]
This issue can be reproduced in Chrome 61.0.3163.100.
I couldn't reproduce it in version 59.0.3071.86.

**Comment by waj** [comment]
It's a bug in one of the FB libraries that we're using:
https://github.com/facebook/draft-js/issues/14

We need to upgrade `fbjs` to fix the problem.

**Comment by waj** [comment]
Fixed in versions 0.10.5, 0.11.2 and 0.12.2
