### ISSUE TITLE
Scheduled time label error in project/surveys overview

### ISSUE THREAD

**Issue by mmoreira-manas** [instedd/ask#1175]
Apparently the "Scheduled at.." label is showing the starting time taking into account browser timezone. In the screenshot below there was a survey scheduled at 8 am Africa - Casablanca timezone (GMT +1) but it shows 4 am which is the time for the timezone where it was accessed (GMT -3)  
<img width="1440" alt="screen shot 2017-10-04 at 5 48 44 pm" src="https://user-images.githubusercontent.com/31930782/31200309-d8940e58-a930-11e7-9a41-257f842a9b7b.png">

**Comment by mmuller** [comment]
Reference:  https://mobilesurveys.freshdesk.com/helpdesk/tickets/73

**Comment by mmuller** [comment]
Working properly in version 2116f6d
