### ISSUE TITLE
Add a visible notification to mobile web and a numeric value is outside the valid range

### ISSUE THREAD

**Issue by nditada** [instedd/ask#1179]
Right now the only indication is that the submit button is disabled

**Comment by jkicillof** [comment]
https://projects.invisionapp.com/d/main#/console/8374235/230456665/preview

**Comment by waj** [comment]
This was working before and now it's broken. The red line is displayed but the message is missing.

**Comment by mmuller** [comment]
Working properly in version 44b6d5a
