### ISSUE TITLE
Avoid unintentional capture of phone numbers

### ISSUE THREAD

**Issue by nditada** [instedd/ask#1180]
People are inputing by mistake their phone numbers in some questions. Though the results is rejected, it is still being captured in the interactions files, which results in a breach of PII. 

We need to add a check for responses after the validation. If after stripping all non-digit characters the last 6 digits of the phone number are found somewhere on the response, lets just replace all of that with ######.

**Comment by mmuller** [comment]
Working properly in version ca49ae7
