### ISSUE TITLE
Hide channel types when the provider is not configured

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#1182]
Version 0.10.4

<img width="717" alt="screen shot 2017-10-17 at 11 28 56 am" src="https://user-images.githubusercontent.com/518152/31670669-780741ce-b32e-11e7-8d8b-e6634197f0ed.png">

**Comment by waj** [comment]
In the example given by @mmuller, the server at Philippines doesn't have the Verboice provider configured. Let's hide the option when that happens.

**Comment by mmuller** [comment]
This feature should be verified in the next version of surveda-ph.org.
