### ISSUE TITLE
Short links to access CSV exports without authentication

### ISSUE THREAD

**Issue by waj** [instedd/ask#1184]
Store short links in a `short_links` table with the following information:

  - hash (random sequence of 32 characters from the [a-zA-Z0-9] set)
  - name (ie: survey/44/results)
  - target (controller/action/params stored in JSON format)

Add a ShortLinkController with a `link` action routed from the `/link/:hash` route. This controller will set a `:skip_auth` parameter in the current connection before forwarding the call to the target controller. This flag must be checked by the user helper to skip verification of memberships.

Implement the UI to generate and obtain short links for CSV downloads:
https://projects.invisionapp.com/d/main#/console/8374235/231393080/preview

**Comment by mmuller** [comment]
Users must be logged into Surveda to download the CSVs (version 44b6d5a)

**Comment by nekron** [comment]
Actually, the url was missing the `/link/`.
Fixed in 55ec5b505b73edc956b7939499adc894082f5214

**Comment by mmuller** [comment]
Working properly in version be284eb
