### ISSUE TITLE
Selecting "fallback mode" before "primary mode" raises an error

### ISSUE THREAD

**Issue by waj** [instedd/ask#1189]
Steps to reproduce:
  
- Create a survey and select a questionnaire
- Go to "Select mode" step
- Click the fallback mode dropdown and select an option

![bdm61phoqi](https://user-images.githubusercontent.com/22697/32175723-80669fe6-bd64-11e7-92a4-b400bfdc2fff.gif)

Related Sentry report: https://sentry.io/instedd/ask-stg/issues/395285140/events/8558395889/

**Comment by mmuller** [comment]
Working properly in version 0.14.0
