### ISSUE TITLE
Channel provider should display the full provider name

### ISSUE THREAD

**Issue by nekron** [instedd/ask#1191]
It's impossible to know to which verboice instance a channel belongs. It should display the name as is being shown in the providers list.

<img width="595" alt="screen shot 2017-10-30 at 14 46 50" src="https://user-images.githubusercontent.com/957103/32186592-3ba10e24-bd81-11e7-8570-cbeee1752f7c.png">
<img width="789" alt="screen shot 2017-10-30 at 14 46 17" src="https://user-images.githubusercontent.com/957103/32186593-3bc3c158-bd81-11e7-8355-ce305a4cbceb.png">

**Comment by waj** [comment]
When more than one provider of the same type is configured, let's add the "friendly name" inside parentheses. For the channel dropdowns, also add the same friendly name inside parentheses (but without adding the provider type name).

**Comment by mmuller** [comment]
Working properly in version 0.14.0
