### ISSUE TITLE
Changing the selected language doesn't change the loaded audio

### ISSUE THREAD

**Issue by nekron** [instedd/ask#1194]
Changing the selected language while a step with an audio file is expanded won't reload the audio.

If the step is collapsed, or the selected language uses TTS, then the component is redrawn and the right audio is selected.

<img width="1163" alt="screen shot 2017-10-30 at 15 42 41" src="https://user-images.githubusercontent.com/957103/32189356-43e2bb8e-bd89-11e7-9bba-7c2100b05d3e.png">

**Comment by mmuller** [comment]
Working properly in version 0.14.0
