### ISSUE TITLE
Long titles are not being truncated

### ISSUE THREAD

**Issue by nekron** [instedd/ask#1196]
<img width="1128" alt="screen shot 2017-10-30 at 16 31 47" src="https://user-images.githubusercontent.com/957103/32191527-2c2b450e-bd90-11e7-9243-6cbcda5b9ce2.png">
<img width="1295" alt="screen shot 2017-10-30 at 16 31 17" src="https://user-images.githubusercontent.com/957103/32191526-2bd60936-bd90-11e7-9ded-0695a5307083.png">

**Comment by mmuller** [comment]
Working properly in version c611d45
