### ISSUE TITLE
Questionnaire can be saved without a prompt question

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#120]
Version: 0.2.0-prod

1. Create a new Questionnaire
2. Add a questionnaire name
3. Click on Save

Obtained:
The questionnaire is saved with an Untitled multiple choice without a Prompt

Expected:
The field Prompt is a required field to save the questionnaire

**Comment by asterite** [comment]
There are no required fields. At most the questionnaire isn't ready to be used.
