### ISSUE TITLE
[Survey] Respondent group can be deleted when the survey is already running

### ISSUE THREAD

**Issue by juanboca** [instedd/ask#1203]
Steps to reproduce:
1- Create a survey
2- Complete all the mandatory fields until the "Launch" button appears
3- Open the survey edit in another tab of the browser
4- Start the survey on the new tab
5- Go back to the first tab and delete the respondent group

The survey goes back to `not_ready` state, but if any call or sms has been already enqueued, the broker might end up in an unexpected state.

**Comment by mmuller** [comment]
Working properly in version 602d30e
