### ISSUE TITLE
Support text responses for numeric questions

### ISSUE THREAD

**Issue by waj** [instedd/ask#1208]
https://invis.io/3U8BARPXJ#/243649898_Z_Index_-_Numeric

 - [x] Add the checkbox in the UI for numeric questions
 - [x] Add a boolean property (`allow_text`) to the numeric step in the schema
 - [x] At runtime read predefined translation files, one for each language stored at `priv/numbers` (ie: `priv/numbers/en.yml` will contain a dictionary where keys are the textual representation of a number and the values are the numbers)
  - [x] Compare the received text from the respondents using the Levenshtein distance. Matches are considered if the distance is less than the size of the numbers divided by 5 (rounded up). If two different numbers matches with the same distance, ignore the value and ask the question again.

**Comment by mmuller** [comment]
Working properly in version 7481cdb
