### ISSUE TITLE
Archive projects

### ISSUE THREAD

**Issue by waj** [instedd/ask#1216]
Projects can be archived/unarchived by an admin. Only projects without running surveys can be archived.

  - [x] Add the "archived" column in the projects table
  - [x] Show the archive/unarchive option in the project's context menu
  - [x] Add a dropdown to filter by "Active Projects" or "Archived"
  - [x] Existing surveys and questionnaires must be displayed in read only mode
  - [x] Do not allow adding new surveys or questionnaires to the archived project

**Comment by mmuller** [comment]
Working properly in version b9bd3bc
