### ISSUE TITLE
Localize UI

### ISSUE THREAD

**Issue by waj** [instedd/ask#1217]
Localization of the UI must be supported so the users can switch the language.

- [x] Analyze and choose a localization library for JS
- [x] Implement the library in the React app
- [x] Localize only some labels to verify the process
- [x] Ensure the process (ideally automated) where localized labels are extracted to a .po file to be sent to translators. Then, translated files must be injected back into the app.
- [ ] Add an UI component to change the language and store it on the user settings

**Comment by mmuller** [comment]
Working properly in version 602d30e
