### ISSUE TITLE
Enhance the "Remove respondents" confirmation messages

### ISSUE THREAD

**Issue by mverzilli** [instedd/ask#122]
<img width="1037" alt="screen shot 2016-10-13 at 15 35 54" src="https://cloud.githubusercontent.com/assets/651693/19362083/98a36ee4-915b-11e6-8c83-1041687dc049.png">

1. Ideally, instead of a modal confirmation, simply let the user remove it and show some way of undoing the operation.

2. In the meantime, make the verbatims more explicit. For example: 

a. Instead of "Please confirm" => "Please confirm you want delete the respondents list"
b. Instead of "Are you sure?" => "Are you sure you want to delete the respondents list? If you confirm, we won't be able to recover it, so you'll have to upload a new one."
c. Instead of "DELETE ALL" => "DELETE RESPONDENTS LIST"

**Comment by waj** [comment]
Also add a "cancel" button
