### ISSUE TITLE
[Autosave] Handle connectivity errors

### ISSUE THREAD

**Issue by waj** [instedd/ask#1225]
Check we handle the following scenarios:
 -  Wi-Fi is disconnected
 -  Wi-Fi is connected but network doesn't work or is not configured correctly
 -  Network is too slow (timeout)

When any of these conditions happen, let's show a message: "No connection: changes are not being saved" and keep retrying every 10 seconds (but sending the latest changes).

**Comment by mmuller** [comment]
Working properly in version 6a459a3
