### ISSUE TITLE
[Activity] Collaborators activities

### ISSUE THREAD

**Issue by waj** [instedd/ask#1229]
Generate activity logs for the following actions (the entity is the project):

| action | metadata |
| --- | --- |
| `create_invite` | `project_name`, `collaborator_email`, `collaborator_name`, `role` |
| `edit_invite` | `project_name`, `collaborator_email`, `collaborator_name`, `old_role`, `new_role` |
| `delete_invite` | `project_name`, `collaborator_email`, `collaborator_name`, `role` |
| `edit_collaborator` | `project_name`, `collaborator_email`, `collaborator_name`, `old_role`, `new_role` |
| `remove_collaborator` | `project_name`, `collaborator_email`, `collaborator_name`, `role` |

**Comment by mmuller** [comment]
Working properly in version f93b25b
