### ISSUE TITLE
[Activity] Survey reports

### ISSUE THREAD

**Issue by waj** [instedd/ask#1231]
Generate activity logs for the following actions (the entity is the survey):

| action | metadata |
| --- | --- |
| `download` | `survey_name`, `report_type` |
| `enable_public_link` | `survey_name`, `report_type` |
| `disable_public_link` | `survey_name`, `report_type` |
| `regenerate_public_link` | `survey_name`, `report_type` |

where `report_type` is one of: `survey_results`, `disposition_history`, `incentives`, `interactions`

**Comment by mmuller** [comment]
Working properly in version f93b25b
