### ISSUE TITLE
Clicking multiple times on the "+" icon for creating a Channel brings up multiple popups

### ISSUE THREAD

**Issue by asterite** [instedd/ask#124]
The button should be disabled until the channel creation dialog is closed

**Comment by asterite** [comment]
I tried to solve this but the first step is to detect when the popup window that is used to log into login.instedd.org is closed. But there's no way to detect that because it's in another domain.

**Comment by fgasperij** [comment]
@qa: it would be nice to test the following cases

- just one click to the add channel button
  - previously logged in at instedd
  - not logged in at instedd
- multiple clicks
  - previously logged in at instedd
  - not logged in at instedd
    - once the log in pop up is opened close it without logging in. Then try to add a channel with any number of clicks.
