### ISSUE TITLE
[Autosave] Avoid internal navigation with unsaved changes

### ISSUE THREAD

**Issue by waj** [instedd/ask#1254]
Capture location changes and avoid these actions to be executed when there are unsaved changes.

Let's discuss with @jkicillof about how to notify the user about this

**Comment by nekron** [comment]
It's creating an infinite loop when trying to prevent navigation events from the back browser button.

When the user closes the alert it is relaunched, at the same time that cycles through all previous urls in the browser history

**Comment by mmuller** [comment]
Working properly in version f93b25b
