### ISSUE TITLE
Survey's editor "create a questionnaire" link gets cut when the window is small enough

### ISSUE THREAD

**Issue by mverzilli** [instedd/ask#126]
To see that link, you need to create a survey with no questionnaires in your project.

See screenshot.

<img width="1326" alt="screen shot 2016-10-13 at 16 09 14" src="https://cloud.githubusercontent.com/assets/651693/19363182/ddeee4e8-915f-11e6-8f2a-9314c28ea8a5.png">

**Comment by asterite** [comment]
I can't reproduce this. What window size do you have? The scroll bar always appears for me.

**Comment by asterite** [comment]
Oh, it's the link that gets cur off...

**Comment by mverzilli** [comment]
Oh, right, I meant link. Sorry :)

**Comment by asterite** [comment]
The text is now "NEW QUESTIONNAIRE" and it doesn't get cut, so this isn't an issue anymore.
