### ISSUE TITLE
The name of a Survey already launched cannot be edited.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#1265]
Version 6a459a3

Preconditions:
There is a Survey 'S'.
'S' is already launched (cancelled, completed, still running).

Reproduce steps:

1. Navigate to the Survey 'S'.
2. Click on the Overview tab.
3. Replace the Survey's name.

Obtained:

- An unexpected error is thrown.

Screenshot:

![image](https://user-images.githubusercontent.com/518152/36915865-f4ff2fda-1e30-11e8-8ed7-00c25a6c1b89.png)

**Comment by waj** [comment]
Fixed in 61fe1495fc1258060d0232dcd18cc171f34f7af0

**Comment by mmuller** [comment]
Working properly in version f93b25b
