### ISSUE TITLE
Collaborator roles not appearing correctly

### ISSUE THREAD

**Issue by adam704a** [instedd/ask#1269]
I am set up as an admin collaborator and have the ability to export all files types (that part is working), yet I appear as an editor in the UI. 

<img width="1008" alt="screen_shot_2018-03-06_at_9_56_32_am" src="https://user-images.githubusercontent.com/276936/37046165-e68df412-2124-11e8-8060-45d14e53ff7f.png">

Version: 0.15.1 (build 2928)

**Comment by mmuller** [comment]
@adam704a  `apreston@rti.org` is an Administrator collaborator.
When you sign in as admin `apreston@rti.org` appears as admin, but when you sign in as editor `apreston@rti.org` appears as editor.  
We will fix it for a next version.

**Comment by mmuller** [comment]
Preconditions:
There is a Project `P`.
`P` has the following collaborators: 
- an owner `O` 
- an admin `A`
- an editor `E`

Reproduce steps:
Sign in as `E`.
Navigate to the Collaborators view.

Obtained:
`A` appears as `Editor`.
`E` can change the permissions of the Admin user.
