### ISSUE TITLE
Uncaught TypeError: Cannot read property 'sun' of undefined

### ISSUE THREAD

**Issue by asterite** [instedd/ask#127]
Assuming you have a project P with a survey S:

1. Enter project P
2. Enter survey S
3. Go to the schedule step
4. Click on the project name at the top bar to go to the projec
5. Click on "Projects" at the top bar
6. Hit the browser's "back" button
6. Hit the browser's "back" button a second time

An error dialog should appear

**Comment by mmuller** [comment]
Ok in version 0.2.0 (build 380)
