### ISSUE TITLE
Activity log is not generated when the Questionnaire settings are edited.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#1288]
Version f93b25b

Preconditions:

- There is a Questionnaire `Q`.

Reproduce steps:

1. Navigate to the Questionnaire `Q`.
2. Select the `SMS` mode.
3. Go to edit the `SMS settings`.
4. Fill the `Error message` field.
5. Navigate to the project's `Activity`.
6. Observe the entries added to the log. 

Obtained:

- Activity log is not generated when the Questionnaire settings are edited.

**Comment by waj** [comment]
Let's add another activity log:

| action | metadata |
| --- | --- |
| `edit_settings` | `questionnaire_name` |

**Comment by mmuller** [comment]
Working properly in version f85dc41
