### ISSUE TITLE
[survey] Schedule step appears completed by default

### ISSUE THREAD

**Issue by juanboca** [instedd/ask#129]
According with #85, the schedule was supposed to start with no days selected. 
Now it starts with all the days of the week selected.

<img width="1150" alt="screen shot 2016-10-13 at 4 24 23 pm" src="https://cloud.githubusercontent.com/assets/488553/19363616/888bcfa0-9161-11e6-8b9f-bb125adc5002.png">

**Comment by mmuller** [comment]
Ok in version 0.2.0 (build 380)
