### ISSUE TITLE
Archiving the 6th project (1st of the second page) draws the empty projects page

### ISSUE THREAD

**Issue by nekron** [instedd/ask#1291]
Steps to reproduce it:
- Have 6 projects on any account so it displays one full page and only one project in the second page.
- Go to the second page and archive that 6th project

<img width="1719" alt="screen shot 2018-03-26 at 12 43 35" src="https://user-images.githubusercontent.com/957103/37917231-3bf499e0-30f4-11e8-9927-1dcf24dcba17.png">

Expected:
It should draw the previous page

<img width="1786" alt="screen shot 2018-03-26 at 12 47 02" src="https://user-images.githubusercontent.com/957103/37917232-3c2106ce-30f4-11e8-81dc-87516d507dfc.png">

Obtained:
Empty projects page is rendered.

<img width="1832" alt="screen shot 2018-03-26 at 12 46 46" src="https://user-images.githubusercontent.com/957103/37917227-3836f186-30f4-11e8-8082-43bcb1fbc7c3.png">

**Comment by mmuller** [comment]
Working properly in version fea7645
