### ISSUE TITLE
[i18n] Translate missing strings

### ISSUE THREAD

**Issue by nekron** [instedd/ask#1292]
Some strings are missing in the translations file:

- Projects

- [x] "Project successfully archived"
- [x] "Project successfully unarchived"

- Collaborators

- [x] "Invite successfully removed"
- [x] "Invite level successfully updated"
- [x] "Collaborator successfully removed"
- [x] "Collaborator level successfully updated"

- Surveys

- [ ] Days displayed inside the forecast
- [ ] "Drop your CSV file here, or click to browse."
- [ ] Months inside the charts displayed in the surveys index.
- [x] New Survey: After selecting "Block dates" a date picker is displayed. Inside the date picker the days are displayed in english.

- Respondents

- [ ] Disposition name displayed in the table (i.e. "Failed")
- [ ] Dates displayed in the table (i.e. "Mar 12, 2018 12:21")

- Questionnaires

- [x] "Duplicate questionnaire" tooltip
- [ ] "Language selection” Step name.
- [ ] When splitting a message "Mensaje SMS (part 1)".
- [x] "Export questionnaire"
- [x] "Import questionnaire"
- [x] "Download contents as CSV"
- [x] "Upload contents as CSV"

**Comment by waj** [comment]
Closing this issue and moved missing items to #1392
