### ISSUE TITLE
Allow mapping of phone numbers

### ISSUE THREAD

**Issue by lmatayoshi** [instedd/ask#1397]
Add a section in channel configuration to support mapping of phone numbers.
Mapping will be provided as a pattern that includes 'X' characters to specify digit placeholders. For example:
`+36 (842) XXXX-XXXX -> 842XXXXXXXX`

The UI must validate that on both sides, only these characters are allowed: digits, `X`, `+`, `-`, `(`, `)` and whitespaces. Also input and output side of each mapping must contain the same amount of `X` characters.

At runtime, before the respondent is contacted through a channel, the original phone number must be sanitized and matched against the patterns. If none of the patterns matches (or if the channel doesn't have any mapping), use the sanitized phone number. The result must be stored in the `sanitized_phone_number` column.

https://projects.invisionapp.com/d/main#/console/8374235/289512561/preview

**Comment by mmuller** [comment]
Working properly in version ed98638
