### ISSUE TITLE
Add id column in the interactions file

### ISSUE THREAD

**Issue by manumoreira** [instedd/ask#1402]
The interactions file only show hours minutes and seconds in timestap and sometimes this affect the order of the messages <img width="550" alt="screen shot 2018-05-29 at 14 59 35" src="https://user-images.githubusercontent.com/31930782/40676398-0044cd18-6351-11e8-92d5-ae96a70e57a3.png"> Adding id will allow users to sort the interactions in the original order.

**Comment by mmuller** [comment]
Working properly in version 5ab25d2
