### ISSUE TITLE
Some dispositions are not being logged in the interactions file

### ISSUE THREAD

**Issue by manumoreira** [instedd/ask#1413]
This ticket https://mobilesurveys.freshdesk.com/a/tickets/101 identified discrepancies in dispositions between interaction file and results file. 
The dispositions: Breakoff, Unresponsive, Rejected and Registered are not being logged in the interactions file. We need to determine which internal event triggers the logging of that event, but dispositions in both files should be equal
Refer to #1406 for breakoff disposition

**Comment by pmallol** [comment]
Ok in Version: 0.20.0-dev-00fa649 (build 3254)
