### ISSUE TITLE
Setting up Channel - Confusing Redirect to Nuntium

### ISSUE THREAD

**Issue by steesdale** [instedd/ask#142]
What Happened: I wanted to create a new channel - I clicked to create this via the channel UI in ask.  Was redirected to login via my InSTEDD account and then after this was further redirected to my existing authorizations.  At this point it was not clear how to setup a channel -- see below:

![screen shot 2016-10-17 at 12 11 12 pm](https://cloud.githubusercontent.com/assets/3987608/19447396/f6ea43ba-9462-11e6-99ba-94a8d7827efd.png)

After going back and selecting the link again -- I was able to see the correct prompt to connect Nuntium.

Expected: I would receive some prompt to be able to set up a new channel via nuntium after logging in - w/o having to navigate back to ask and selecting the link again.

**Comment by waj** [comment]
This is a problem in Guisso: in https://github.com/instedd/guisso/issues/41
