### ISSUE TITLE
interim partials should be included in the dashboard

### ISSUE THREAD

**Issue by adam704a** [instedd/ask#1430]
<img width="748" alt="screen_shot_2018-08-09_at_1_31_16_pm" src="https://user-images.githubusercontent.com/276936/43921539-48d48990-9bd9-11e8-996a-2240cf5fb653.png">

**related**:
https://github.com/instedd/ask/issues/1206
https://github.com/instedd/ask/issues/1422

**Comment by adam704a** [comment]
@nditada flagging this to be added asap. Needs to be in for the next full scale survey.

**Comment by mmuller** [comment]
Working properly in version 5ab25d2
