### ISSUE TITLE
Allow to lock surveys 

### ISSUE THREAD

**Issue by lmatayoshi** [instedd/ask#1438]
Allow project admins to lock or unlock surveys to mitigate risks of erroneous stops and changes to sample size of running surveys

https://invis.io/2TMXFAVHVQM#/266351230_Cockpit_-_Simple
https://invis.io/2TMXFAVHVQM#/241966468_Cockpit
https://invis.io/2TMXFAVHVQM#/256870945_Stop_Survey

**Comment by pmallol** [comment]
Working ok in Version: 0.20.0-dev-00fa649
