### ISSUE TITLE
Setting up New Project - Edit option a bit confusing

### ISSUE THREAD

**Issue by steesdale** [instedd/ask#144]
When creating a new project, after giving it a name you arrive at a list of projects.  For each project there is the option to edit.  When selecting edit, you can again change the name.  After clicking around - I found selecting the name string allowed a user to open the project and continue working on it - but could be an early blocking point for new users. 

![screen shot 2016-10-17 at 11 51 56 am](https://cloud.githubusercontent.com/assets/3987608/19448613/32de58d4-9468-11e6-962b-0c7c29b2dc74.png)

What I expected / A suggestion:  I expected that when I selected "edit" I would be able to continue creating my project.  When that didn't work - I was stuck for a couple minutes clicking around looking for how to proceed.  Some clearer direction for a user on how to proceed could be helpful here.

**Comment by waj** [comment]
This is fixed already for 0.3.0. The "edit" button is gone, and the project name is edited in the title bar.
