### ISSUE TITLE
Create folder for surveys

### ISSUE THREAD

**Issue by nditada** [instedd/ask#1463]
Many projects have an explosion of surveys and it becomes unwieldy and difficult to navigate. A way to organize surveys either through folders would make the page much less congested.

For reference, see: https://invis.io/2TMXFAVHVQM#/344274727_Add_Menu

We need to: 

- [ ] Add the dropdown menu to create survey folders
- [ ] Enable a way to move surveys in/out folders (@jkicillof I can't find design for that)
- [ ] Implement folder navigation (a single level is more than enough)

**Comment by mmuller** [comment]
Working properly in version 9a11858
