### ISSUE TITLE
Call duration is not computed on failed calls

### ISSUE THREAD

**Issue by waj** [instedd/ask#1502]
If the call is interrupted during a running questionnaire, the verboice call ends and the partial duration is not added to the stats.

https://github.com/instedd/surveda/blob/915f307168a0ad28f1f2be80392644719199b96d/lib/ask/runtime/verboice_channel.ex#L259-L303

Let's use the `CallDuration` provided by Verboice in the status callback instead of computing the duration on the Surveda's side.

**Comment by mmuller** [comment]
Working properly in version 4f50b9c
