### ISSUE TITLE
If we hash phone numbers - we will need a unique id per user

### ISSUE THREAD

**Issue by steesdale** [instedd/ask#152]
We are planning to hash phone number for participant.  When downloading data - a unique id should be included per user.

**Comment by waj** [comment]
Why is the identification of each respondent important? Aren't the stats over the results all that matters?

**Comment by steesdale** [comment]
I anticipate downstream analysis needs by our partners   A few example to help articulate this better....  

1) As an analyst I want to easily refer to a call interaction that had some unusual behavior
2) As an analyst I want to easiyl analyze when Fall-backs occur for a respondent meaning:  They start with carrying out an IVR survey, stop, the tool falls back to try SMS and they then complete.  There is a desire to evaluate these types of behaviors that happen with users. 
3) Having a common record per user - and their results will be something they want as well.    e.g., for user 120301231, their responses were 1=A; 2=B; 3=C -- and their final determination is this disposition code. 

Hope this helps... happy to jump on a call to articulate better as well.

**Comment by steesdale** [comment]
this has been resolved.
