### ISSUE TITLE
[Quiz] Mode selectors

### ISSUE THREAD

**Issue by waj** [instedd/ask#167]
Add "SMS" and "IVR" mode selectors on the left side of the editor.

This must affect the "modes" field of the questionnaire.

**Comment by asterite** [comment]
**NOTE**: I'm missing the toggle icons, I couldn't find them in materialize, so for now I'm using the same toggles as for the schedule days.

@Mscebba Could you add the "toggle modes" icons that are shown [here](https://projects.invisionapp.com/d/main#/console/8374235/196343922/preview)

**Comment by asterite** [comment]
@Mscebba Nevermind, found it :-)
