### ISSUE TITLE
The EditableTitleLabel component looks strange when a long value is set

### ISSUE THREAD

**Issue by juanboca** [instedd/ask#174]
While editing the title, the input takes the full available width and it is displayed OK. But when the user leaves the edit mode, the label will be shown with line jumps, and disappear in lower resolutions. 

Editing in 1920 x 1080:
![screen shot 2016-10-24 at 9 44 47 am](https://cloud.githubusercontent.com/assets/488553/19657291/f58f47d0-99f9-11e6-9a97-678312299794.png)

Editing in lower resolution:

![screen shot 2016-10-24 at 2 53 49 pm](https://cloud.githubusercontent.com/assets/488553/19657293/f58fb3dc-99f9-11e6-9d77-164efab31164.png)

Label in 1920 x 1080:
![screen shot 2016-10-24 at 9 42 29 am](https://cloud.githubusercontent.com/assets/488553/19657292/f58fe4b0-99f9-11e6-905a-4c8047bf7326.png)

**Comment by Mscebba** [comment]
Fixed in previous commit: ticket #104

https://github.com/instedd/ask/commit/63adddaac1d055a5deb999cd1cbe3ec0b6691a01
