### ISSUE TITLE
[Quiz] Allow uploading file for audio resource

### ISSUE THREAD

**Issue by waj** [instedd/ask#175]
https://projects.invisionapp.com/d/main#/console/8374235/193623004/preview

**Comment by waj** [comment]
Store audio files in a "audios" table:
- id
- uuid
- data
- filename
- source: "upload" | "record"
- duration

**Comment by fgasperij** [comment]
### Pendings
- [ ] validate file type and size on the server (@fgasperij)
- [ ] check that the error flow on the `AudioController.create` works
- [ ] check that everything works with MP3 and WAV
- [ ] add controller tests
- [ ] integrate with auto save feature
- [ ] check that the dropzone reject flow works OK when #240 is solved
- [ ] save file duration
- [ ] style the UI as per https://projects.invisionapp.com/d/main#/console/8374235/193623004/preview
