### ISSUE TITLE
[Quiz] Split SMS messages

### ISSUE THREAD

**Issue by waj** [instedd/ask#179]
The quiz editor must support splitting the SMS prompt in multiple messages.
The current storage of SMS prompts must be modified to store the messages as an array.

https://projects.invisionapp.com/d/main#/console/8374235/193624221/preview
https://projects.invisionapp.com/d/main#/console/8374235/194469528/preview

**Comment by lmatayoshi** [comment]
Out of scope at the moment

**Comment by waj** [comment]
This is already done
