### ISSUE TITLE
Uploading CSV should ignore additional columns

### ISSUE THREAD

**Issue by edjez** [instedd/ask#188]
The upload says "CSV" but if I submit the following, the whole row gets interpreted as the number
`111111111,apple
2222222222,banana`

**Comment by waj** [comment]
Do we even know if the telcos will provide the phone numbers as CSV files? I have the feeling that using CSV files was totally our idea. Maybe I'm wrong, but maybe it just makes sense to accept any text file.

**Comment by edjez** [comment]
There are many sources - telcos are a possible but least likely one, there could also be CDC R scripts, RDD scripts implemented in excel, etc. CSV is the least common denominator we've agreed on that anyone can convert to. for the moment ignoring the other "columns" make sense.
