### ISSUE TITLE
Pages count fail in panel surveys

### ISSUE THREAD

**Issue by diegoliberman** [instedd/ask#1949]
In panel surveys with less than 9 waves, all the waves should be shown on page 1.
Something is not worlimng properly in the page counter (at the bottom right corner)

![image](https://user-images.githubusercontent.com/25181052/135128503-333d1ea6-cb0f-4da6-890c-ab7c3601bdf9.png)

**Comment by ysbaddaden** [comment]
The problem is here:
https://github.com/instedd/surveda/blob/master/web/static/js/components/surveys/PanelSurveyShow.jsx#L162-L163

I think we're simply missing a `pageSize`, which I understand is the number of surveys to list per-page.

**Comment by ysbaddaden** [comment]
Errata: there is no pagination of the list of surveys inside a panel survey. The backend merely returns the panel survey with all its surveys at once. We can work around the issue by faking it until we decide to implement it (or not).

I.e. display "1-X of X", for example "1-9 of 9".

**Comment by diegoliberman** [comment]
@manumoreira we need to decide if it's necessary to implement an actual pagination right now.

**Comment by ysbaddaden** [comment]
I implemented the workaround: fake it until you can make it.

To decide whether we should implement actual pagination, we should look at how many waves there usually are under a panel survey, if it's slowing things down (client and/or backend), displays too many things, or if it's acceptable. It can be done on the server (don't return too many surveys) or the client (server returns everything, client does the pagination).
