### ISSUE TITLE
A long project name breaks the breadcrumb

### ISSUE THREAD

**Issue by nekron** [instedd/ask#195]
It should have a max width and some ellipsis.

<img width="1648" alt="screen shot 2016-10-27 at 2 58 49 pm" src="https://cloud.githubusercontent.com/assets/957103/19779124/0decbff2-9c56-11e6-910c-f28274ff3fdb.png">

**Comment by juanboca** [comment]
The name doesn't need to be too long for it to break the UI:

<img width="1424" alt="screen shot 2016-10-26 at 12 13 07 pm" src="https://cloud.githubusercontent.com/assets/488553/19782687/4c5c2958-9c65-11e6-8608-e15a1c7759f7.png">

**Comment by pmallol** [comment]
Ok in Version: 0.4.0-dev-9e45973 (build 1031)
