### ISSUE TITLE
When creating a new questionnaire, each time the user presses SAVE, a new questionnaire is created

### ISSUE THREAD

**Issue by juanboca** [instedd/ask#196]
Instead of updating the recently created Questionnaire, each press to the SAVE button will create a new one, with the same data

Pressing 4 times the SAVE button
<img width="1273" alt="screen shot 2016-10-27 at 5 05 59 pm" src="https://cloud.githubusercontent.com/assets/488553/19783266/aa4b6d42-9c67-11e6-9d57-7c06ac51056a.png">
Will result on having this:
<img width="1110" alt="screen shot 2016-10-27 at 5 05 52 pm" src="https://cloud.githubusercontent.com/assets/488553/19783270/aedf85c8-9c67-11e6-97af-e579a84b7699.png">

**Comment by asterite** [comment]
I think the best/easiest thing to do is to immediately create a questionnaire in the database when you click the "+" icon. In this way the "+" icon behaves the same for every entity: project, survey, questionnaire.
