### ISSUE TITLE
Prompts are not log in the Interactions file in MobileWeb mode

### ISSUE THREAD

**Issue by manumoreira** [instedd/ask#2066]
Version: https://github.com/instedd/surveda/commit/5ab25d21a60986d031b73b9104fd030776a7b8ae

Steps to reproduce:

Create a questionnaire "q1", with mobile web mode.
Launch a survey.
Complete the survey with some respondents.
Download the Interactions file.
Obtained:
The interactions file doesn't include entries corresponding to the steps' prompts

We have reasons to believe it was working on 0.15.2 (we have an interactions file from a survey that most-probably ran with 0.15.2 that includes Prompt entries).

**Comment by manumoreira** [comment]
copy of #1434

**Comment by matiasgarciaisaia** [comment]
Any reason to have two different tickets instead of working with one?
