### ISSUE TITLE
Character count displaying misleading numbers

### ISSUE THREAD

**Issue by edjez** [instedd/ask#217]
When typing in characters the total char available (in the #wajbar) is wrong;
Expected: the content of the message affects characters available
E.g. - western characters adding up to a 140 total  (expected)
![image](https://cloud.githubusercontent.com/assets/1182549/19895261/4e5b8c7a-a00d-11e6-9b5d-eb9b6746b7c0.png)

Expected: Unicode characters outside 7-bit and 8-bit GSM encodings reduce message available character count to 130* / 70*
 (* or appropriate numbers, I'm just guessing from memory)

**Comment by edjez** [comment]
![image](https://cloud.githubusercontent.com/assets/1182549/19896429/7e2d509c-a011-11e6-9284-6fdbb18a23c5.png)

**Comment by waj** [comment]
Fixed in #649
