### ISSUE TITLE
Refactor respondents chart

### ISSUE THREAD

**Issue by lmatayoshi** [instedd/ask#232]
Refactor includes the following changes:

- [ ] Adapt empty chart to https://projects.invisionapp.com/d/main#/console/8374235/198000671/preview

- [ ] Fix 'x' axis range to 3 months. Formally, max value between 90 days and 'now' value

- [ ] Project the empty chart as snippet and draw the data on top of the snippet in order to show the evolution of the chart and improve the comparison criteria

- [x] In survey show, display respondentsReached/cutoff above the chart and respondentsReached/totalRespondents below

**Comment by pmallol** [comment]
Ok in Version: 0.4.0-dev-8ab670d (build 801)
