### ISSUE TITLE
[Survey] After uploading a respondents file the questionnaire step is marked as incomplete

### ISSUE THREAD

**Issue by waj** [instedd/ask#238]

**Comment by asterite** [comment]
Steps to reproduce? Works for me.

**Comment by waj** [comment]
Try this:
- Create new survey
- Turn WiFi off
- Select a questionnaire
- Turn WiFi on
- Upload respondents file

**Comment by pmallol** [comment]
Ok in Version: 0.4.0-dev-8ab670d (build 801)
