### ISSUE TITLE
[Survey] Cannot upload respondents file with a single respondent

### ISSUE THREAD

**Issue by waj** [instedd/ask#239]

**Comment by juanboca** [comment]
The parser works fine with files with only 1 respondent. From tests and from the browser (Chrome), works fine.

The error appears to be only in Safari 10. 
In Safari 9 the site doesn't even work. 
Please hold this ticket until we can identify the actual problem.

**Comment by asterite** [comment]
I was able to reproduce it in Chrome. I think the problem is that the logic is trying to detect the line separator but there's no such thing if the file has just one line.

**Comment by asterite** [comment]
To clarify this, it works with a file with a single line in it, which includes a single line separator like `"\n"`. The test that worked in Chrome was probably this case. It wasn't working when there were no newlines at all.

**Comment by juanboca** [comment]
Yes, this could be due to the Sublime setting `ensure_newline_at_eof_on_save`, that added a `\n` on the file I used to test it. Great you find it!

**Comment by pmallol** [comment]
Ok in Version: 0.4.0-dev-8ab670d (build 801)
