### ISSUE TITLE
[Survey] Some fields are not updated correctly when the survey is loaded from cache

### ISSUE THREAD

**Issue by waj** [instedd/ask#242]
When going back and forward into the survey editor, some fields are not updated correctly.

To reproduce:
- Create a new survey
- Select "Phone Call" mode
- Click "back" in the browser
- Click "forward" in the browser

Expected:
- "Phone Call" is not selected (because the survey was not saved)

Seems like the materialize components are not responding correctly to programmatic changes.

**Comment by mmuller** [comment]
Working properly in version 209d89d
