### ISSUE TITLE
[Questionnaire]  Incomplete Details Cause Error and Lost Questionnaire

### ISSUE THREAD

**Issue by steesdale** [instedd/ask#251]
What I did: 
- I created a new questionnaire at the demo server 0.2.1
- I left some key fields blank; e.g., the field name, the questionnaire name, etc... 
- I filled out some of the other fields
- I hit "save" and was presented with an error and lost the questionnaire - it was not saved
![screen shot 2016-11-10 at 9 51 13 am](https://cloud.githubusercontent.com/assets/3987608/20183529/42a84178-a72b-11e6-8bd7-b1e056f3a9a4.png)

What I expected
- That it would atleast save my questionnaire
- That if there was a required field it would notify me to fix it before saving 
- That it would direct me to what I was missing

**Comment by steesdale** [comment]
A further clarification --

if I select the "click to go home ..." I lose the questionnaire.  

if I select off the box, it disappears and I can continue editing. 

Suggestion -- it should be easier and more obvious to go back and keep editing, than to move away from the form and lose my progress.

**Comment by waj** [comment]
The behavior of the questionnaire editor has changed since this error was reported. Now the changes are automatically saved and many bug were fixed. I'll close this and let's open new issues with more specific details when needed.
