### ISSUE TITLE
Import Sample - Progress Uncertainty

### ISSUE THREAD

**Issue by steesdale** [instedd/ask#252]
**What Happens Now** 
- If you take a .csv with 250k phone numbers 
- You select to import it 
- You will likely have to wait for a while 
- You sit there now and just stare at the "select here to import" Ux - unsure if it is working in the background or not.  As an inpatient human, naturally it looks like it isn't working and I will try to re-import or give up. 

**What Would be Helpful** 
- After selecting the CSV 
- Progress bar to show how far along a large sample file is in upload
- And / Or a message that says --- this is currently underway, check back later and we will let you know when its done.

**Comment by mmuller** [comment]
This functionality was added in #793
