### ISSUE TITLE
[Quiz] Collapsed steps must be displayed without space between them

### ISSUE THREAD

**Issue by waj** [instedd/ask#253]
https://projects.invisionapp.com/d/main#/console/8374235/184295216/preview

**Comment by Mscebba** [comment]
Fixed on commit https://github.com/instedd/ask/commit/f763d0a05475e4946fb5f7c1d428b2a979f35256

**Comment by pmallol** [comment]
Ok in Version: 0.4.0-dev-8ab670d (build 801)
