### ISSUE TITLE
[Questionnaire] Style audio upload

### ISSUE THREAD

**Issue by fgasperij** [instedd/ask#257]
Style audio upload interface as per https://projects.invisionapp.com/d/main#/console/8374235/193623004/preview.

The current markup can be found at https://github.com/instedd/ask/blob/master/web/static/js/components/questionnaires/StepEditor.jsx

**Comment by Mscebba** [comment]
Fixed on commit: https://github.com/instedd/ask/commit/e5159b55416f736db2bb582749f63e6ccf8e44a8
