### ISSUE TITLE
Apply style to retry configuration step in Survey Wizard

### ISSUE THREAD

**Issue by lmatayoshi** [instedd/ask#260]
By now, the retry configuration step is being shown this way:

![retry_configuration_style](https://cloud.githubusercontent.com/assets/8591752/20217411/924649ae-a7fe-11e6-8353-e5aa6895f8a8.png)

It should be adapted to the following mockups:
https://projects.invisionapp.com/d/main#/console/8374235/182593580/preview
https://projects.invisionapp.com/d/main#/console/8374235/192582422/preview

**Comment by pmallol** [comment]
Ok in Version: 0.4.0-dev-8ab670d (build 801)
