### ISSUE TITLE
[Landing] Clicking on "about" does nothing

### ISSUE THREAD

**Issue by mverzilli** [instedd/ask#267]
1. Log out (should redirect you to landing)
2. Click About InSTEDD Platform.

Expected: app goes to some informative page about InSTEDD Platform.

Actual: nothing happens.

**Comment by mverzilli** [comment]
Still an issue in `0.5.0-dev-acdae70 `

**Comment by mmuller** [comment]
Still present in version  0.7.1-dev-209d89d.

**Comment by waj** [comment]
Let's link to http://instedd.org/technologies/

**Comment by mmuller** [comment]
Working properly in version 322bad2
