### ISSUE TITLE
[Landing] Effortless schedule setup pic does not project shadow

### ISSUE THREAD

**Issue by mverzilli** [instedd/ask#268]

**Comment by mverzilli** [comment]
<img width="1328" alt="screen shot 2016-11-14 at 14 16 57" src="https://cloud.githubusercontent.com/assets/651693/20274919/37ad14ae-aa75-11e6-8343-d59d907fbcd3.png">

Compare with "Easy questionnaire design". Note how the lack of shadow in "Effortless..." makes it look untidy.

<img width="1312" alt="screen shot 2016-11-14 at 14 18 36" src="https://cloud.githubusercontent.com/assets/651693/20274954/5ab857c4-aa75-11e6-9660-4eabadb1bf25.png">

**Comment by asterite** [comment]
This is because in the second case it's the window's shadow. The first case is just content inside a webpage and it doesn't have shadow. Not a bug to me.
