### ISSUE TITLE
[Questionnaire] Voice dropdown arrow is far from the select

### ISSUE THREAD

**Issue by fgasperij** [instedd/ask#269]
Steps:

1. Create a Questionnair
2. Add a Multiple Choice Step
3. Scroll to the Question Prompt section and click on the Voice dropdown.

The is a blue triangle on the right of the section.

**Comment by fgasperij** [comment]
<img width="860" alt="screen shot 2016-11-14 at 2 14 30 pm" src="https://cloud.githubusercontent.com/assets/1685226/20274934/445430e8-aa75-11e6-8fdc-0df30ebe051d.png">

**Comment by pmallol** [comment]
Ok in Version: 0.4.0-dev-8ab670d (build 801)
