### ISSUE TITLE
Step response autocomplete doesn't work when pressing enter

### ISSUE THREAD

**Issue by asterite** [instedd/ask#270]
Steps to reproduce:

1. Create a project
2. Create a questionnaire within that project
3. Create a multiple-choice step
4. In that step, add a response with value "Yes" and SMS "y, yes"
5. Create another multiple-choice step, add a response with value "Yes" and press Enter

Expected: the SMS fields get filled with "y, yes"
Actual: nothing happens

**Comment by pmallol** [comment]
Ok in Version: 0.4.0-dev-8ab670d (build 801)
