### ISSUE TITLE
[Project Editor] Editing title doesn't update project name in nav bar

### ISSUE THREAD

**Issue by mverzilli** [instedd/ask#272]
1. Create a project. Notice the name starts as "Untitled" both in the header and in the navigation bar.
2. Edit the project title.

Expected: the new project title displays both in header and in the nav bar.
Actual: navbar project title remains "Untitled". See screenshot:

<img width="451" alt="screen shot 2016-11-14 at 14 22 08" src="https://cloud.githubusercontent.com/assets/651693/20275085/e0ac6ae6-aa75-11e6-8115-e3fc22da2dc2.png">

**Comment by asterite** [comment]
@mverzilli In which page is this? There's no single page where the title bar shows the project name and the top bar shows the same thing. Can't reproduce.

**Comment by mverzilli** [comment]
I think I got confused and was editing a survey's title instead of project title. I think it's fair to say this is not an issue.
