### ISSUE TITLE
SMS recontact attempts fields is not being validated

### ISSUE THREAD

**Issue by asterite** [instedd/ask#274]
This is in the "Setup a schedule" section in the survey creation/edition.

For example, if you enter "verdura" and click outside the field, only "d" remains. If you type "cucurucho", only "h" remains. This should be validated and should show an error when the value is invalid.

**Comment by asterite** [comment]
Additionally, if "d" is left in the field, it crashes the entire broker

**Comment by juanboca** [comment]
<img width="640" alt="screen shot 2016-11-14 at 3 21 18 pm" src="https://cloud.githubusercontent.com/assets/488553/20277165/2ea2c8be-aa7e-11e6-9d4d-548c447f4b0e.png">

**Comment by juanboca** [comment]
Now that the style was applied, I found another issue: If the user enters several spaces, a lot of intervals are created:

![screen shot 2016-11-16 at 4 37 08 pm](https://cloud.githubusercontent.com/assets/488553/20362622/0b817972-ac1b-11e6-82e9-e13e2080ef2c.png)

**Comment by pmallol** [comment]
ok in Version: 0.4.0-dev-8ab670d (build 801)
