### ISSUE TITLE
[Quiz] When opening a step, the user has to scroll up to see all the content

### ISSUE THREAD

**Issue by juanboca** [instedd/ask#276]
The user has 5 steps on the questionnaire. If the user opens the first step, scrolls down to the bottom of the page, clicks to open the next one, it has to scroll up to edit the title and other fields.

<img width="905" alt="screen shot 2016-11-14 at 2 33 18 pm" src="https://cloud.githubusercontent.com/assets/488553/20275542/b5b0d0aa-aa77-11e6-879b-762e8338d5ce.png">

**Comment by mmuller** [comment]
Working properly in version 209d89d.
