### ISSUE TITLE
[Questionnaire] There is no hint indicating Responses added to a step are editable

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#277]
Version 0.3.0-dev-4f8644f (build 710)

1. Create a Project
2. Create a Questionnaire
3. Add a step
4. Add a response

Obtained:
There is no hint nor indicator for the user to understand the 'No Response' section is editable.
Same with SMS and IVR valid entries.

![screen shot 2016-11-14 at 3 57 57 pm](https://cloud.githubusercontent.com/assets/9214460/20278386/30251d22-aa83-11e6-8451-efff04bab687.png)

**Comment by waj** [comment]
When a new response is added the new row must be editable already with focus on the response field.

**Comment by mmuller** [comment]
Working properly in version cc5d3df
