### ISSUE TITLE
[Survey] Unexpected behavior when clicking on wizard navigation panel

### ISSUE THREAD

**Issue by mverzilli** [instedd/ask#279]
1. Create a survey.
2. Click on "Upload your respondents list". The window doesn't scroll up enough:

<img width="1102" alt="screen shot 2016-11-14 at 14 47 11" src="https://cloud.githubusercontent.com/assets/651693/20275992/421b7616-aa79-11e6-838d-14dff7706690.png">

Would have expected something more like:

<img width="1066" alt="screen shot 2016-11-14 at 14 47 40" src="https://cloud.githubusercontent.com/assets/651693/20276014/521b7dcc-aa79-11e6-9d0d-833df85dce58.png">

3. Click on "Setup cutoff rules".  Notice that it doesn't get bold as a result (probably because it doesn't scroll enough to be at the top, not sure).

<img width="1061" alt="screen shot 2016-11-14 at 14 48 32" src="https://cloud.githubusercontent.com/assets/651693/20276090/98bf7ed6-aa79-11e6-98e6-50691088a5f4.png">

**Comment by mmuller** [comment]
Working properly in version 209d89d.
