### ISSUE TITLE
[Layout] Header is not vertically aligned

### ISSUE THREAD

**Issue by mverzilli** [instedd/ask#282]
See screenshot, compare with Invision. Logo and title should be vertically aligned between the navbar and the page content that begins in the white area.

<img width="432" alt="screen shot 2016-11-14 at 14 51 37" src="https://cloud.githubusercontent.com/assets/651693/20276198/152025f2-aa7a-11e6-933e-05f204e5910f.png">

**Comment by pmallol** [comment]
Ok in Version: 0.4.0-dev-8ab670d (build 801)
