### ISSUE TITLE
[Survey] An error modal is open when 'from' field is set with a higher value than 'to' field

### ISSUE THREAD

**Issue by lmatayoshi** [instedd/ask#283]
Steps to reproduce:
- Create a new survey
- Go to 'Setup Schedule Step'
- Set a 'from' field with a higher value than 'to' field

Expected:
- Fields are marked as invalid, but user can still navigate

Obtained:
- 'Sorry, something went wrong' modal is shown

**Comment by mmuller** [comment]
Working properly in version 8a3fbff
