### ISSUE TITLE
[Survey] Wizard navigation panel movement makes it hard to find

### ISSUE THREAD

**Issue by juanboca** [instedd/ask#284]
When the user is on the first step, the navigation panel is floating a few pixels below the black header. When the user is on any other, the navigation panel is almost at the top of the screen. 
This makes that when switching between the first step and any other (and viceversa), the user has to move the cursor up and down to look for the navigation bar again.

Expected: The navigation bar should remain in the same position, to make it easier to use.

<img width="1291" alt="screen shot 2016-11-14 at 2 54 30 pm" src="https://cloud.githubusercontent.com/assets/488553/20276267/50d42cc4-aa7a-11e6-95fe-3ed9926b157f.png">
<img width="1294" alt="screen shot 2016-11-14 at 2 54 19 pm" src="https://cloud.githubusercontent.com/assets/488553/20276268/50d6b408-aa7a-11e6-9277-0b6116a7f2f8.png">

![](http://g.recordit.co/s3tnA2haLN.gif)

**Comment by waj** [comment]
This was fixed in 0d1e2dbf65ab841600fc8cb3dce19b092f5d5472
