### ISSUE TITLE
[Survey] Phone numbers sent to Nuntium must not have spaces

### ISSUE THREAD

**Issue by fgasperij** [instedd/ask#286]
Steps:

1. Create a LocalGateway channel.
2. Create a Survey.
3. Upload a respondent list that has spaces in between the digits of the phone numbers.
4. Run the survey.

Expected: the SMSs arrive succesfully.
Result: Nuntium fails to send the SMSs because the phone numbers contain spaces.

Verify what requirements Nuntium has regarding phone numbers to perform a sanitization of them before sharing them with Nuntium.

**Comment by fgasperij** [comment]
<img width="908" alt="screen shot 2016-11-14 at 3 00 09 pm" src="https://cloud.githubusercontent.com/assets/1685226/20276604/b49c0c4e-aa7b-11e6-9653-018e016ab83e.png">

**Comment by asterite** [comment]
This actually needs something more to be done: if we send the message to "sms://5491112345625" then when we get a reply from that number we won't find it in the respondents table. We need to have a separate column where the sanitized phone number is stored.

**Comment by pmallol** [comment]
Ok in Version: 0.4.0-dev-8ab670d (build 801)
