### ISSUE TITLE
[Questionnaire] Mode switch for "Phone calls" responds weirdly to window width

### ISSUE THREAD

**Issue by mverzilli** [instedd/ask#287]
At 1245 pixels:

<img width="394" alt="screen shot 2016-11-14 at 14 59 10" src="https://cloud.githubusercontent.com/assets/651693/20276707/27f06a32-aa7c-11e6-8145-683560ee76af.png">

At 1102 pixels:

<img width="394" alt="screen shot 2016-11-14 at 15 08 19" src="https://cloud.githubusercontent.com/assets/651693/20276715/3567eb68-aa7c-11e6-86c5-33e57e35f7c1.png">

At 935 pixels:

<img width="408" alt="screen shot 2016-11-14 at 15 09 02" src="https://cloud.githubusercontent.com/assets/651693/20276734/4c70f34a-aa7c-11e6-9623-a348ca51af28.png">

Expected: if "Phone calls" fits in 935px, it should fit in every other bigger width

**Comment by pmallol** [comment]
Ok in Version: 0.4.0-dev-9e45973 (build 1031)
