### ISSUE TITLE
[Survey] Provide a way to navigate to edit questionnaires from survey

### ISSUE THREAD

**Issue by mverzilli** [instedd/ask#289]
See screenshot. If I want to edit a Questionnaire when I'm at the Survey edit screen there's no affordance. I have to remember to go back to my project (which is also somehow complicated). I need 5 or 6 clicks to get to the questionnaire I want to edit. Just as we provide a shortcut to create a new quiz, we should be able to navigate to edit existing ones in a single click from the survey.

<img width="1067" alt="screen shot 2016-11-14 at 15 11 30" src="https://cloud.githubusercontent.com/assets/651693/20276900/1e693394-aa7d-11e6-8290-9d46c614370f.png">

**Comment by waj** [comment]
There is now a link to add a new questionnaire in the wizard
