### ISSUE TITLE
[Questionnaire] Multiple layout issues in step title

### ISSUE THREAD

**Issue by mverzilli** [instedd/ask#290]
<img width="767" alt="screen shot 2016-11-14 at 15 22 15" src="https://cloud.githubusercontent.com/assets/651693/20277266/9e9af286-aa7e-11e6-80e1-fb129836c33d.png">

<img width="767" alt="screen shot 2016-11-14 at 15 22 15" src="https://cloud.githubusercontent.com/assets/651693/20277336/d9107ada-aa7e-11e6-8601-12f788e3a5d4.png">

**Comment by pmallol** [comment]
Ok in Version: 0.4.0-dev-8ab670d (build 801)
