### ISSUE TITLE
[Questionnaire] Layout issues in step type selection overlay

### ISSUE THREAD

**Issue by mverzilli** [instedd/ask#292]
<img width="330" alt="screen shot 2016-11-14 at 15 36 30" src="https://cloud.githubusercontent.com/assets/651693/20277647/2eabf87e-aa80-11e6-8d64-e752b054c354.png">

**Comment by lmatayoshi** [comment]
<img width="1435" alt="blue_icon_at_right" src="https://cloud.githubusercontent.com/assets/8591752/20278036/f02c8f9e-aa81-11e6-8e43-02912aa638b6.png">

**Comment by Mscebba** [comment]
Fixed on commit: https://github.com/instedd/ask/commit/03d3c49e28c4e087d10e34787b091d47c6415614

**Comment by pmallol** [comment]
Ok in Version: 0.4.0-dev-8ab670d (build 801)
