### ISSUE TITLE
[Questionnaire] Store section of step misaligned

### ISSUE THREAD

**Issue by mverzilli** [instedd/ask#295]
<img width="739" alt="screen shot 2016-11-14 at 15 40 46" src="https://cloud.githubusercontent.com/assets/651693/20277787/c6a84c4a-aa80-11e6-9f04-66a656db2d22.png">

**Comment by Mscebba** [comment]
Fixed on commit https://github.com/instedd/ask/commit/53f4e4f3c75e567cd5d5156034e4cc9590f550d9
