### ISSUE TITLE
[Questionnaire] Layout issue with TTS/Audio select input

### ISSUE THREAD

**Issue by mverzilli** [instedd/ask#296]
Notice the blue arrow at the far bottom right (it's supposed to be hint that it's a select).

<img width="843" alt="screen shot 2016-11-14 at 15 43 20" src="https://cloud.githubusercontent.com/assets/651693/20277868/300c84e4-aa81-11e6-86a8-94d0ab6aa7e8.png">

Then click the select and notice how the TTS icon overlaps the "Text to speech" label

<img width="392" alt="screen shot 2016-11-14 at 15 44 37" src="https://cloud.githubusercontent.com/assets/651693/20277880/44dc8fc2-aa81-11e6-90b8-c9e211c92d7a.png">

**Comment by waj** [comment]
Duplicate of #269
