### ISSUE TITLE
[Quiz] An extra row is displayed when adding a numeric step

### ISSUE THREAD

**Issue by lmatayoshi** [instedd/ask#303]
Steps to reproduce:

- Click the 'Add questionnaire' button
- Click 'Add step' and select numeric step

An extra row between 'SMS message' and 'Save this response at' is displayed

<img width="1397" alt="extra_row_in_numeric_field" src="https://cloud.githubusercontent.com/assets/8591752/20278857/06e7e50a-aa85-11e6-9ad9-fe3cc9c3f709.png">

**Comment by waj** [comment]
Extra configuration is coming in that area (https://projects.invisionapp.com/d/main#/console/8374235/193624465/preview) so it wouldn't make sense to fix this now
