### ISSUE TITLE
[Questionnaire] On Windows the drag and drop of CSV files is not working

### ISSUE THREAD

**Issue by fgasperij** [instedd/ask#307]
Steps:

1. On your Windows PC create a survey.
2. Go to the 'Upload respondents' step.
3. Drag and drop a valid CSV files over the dropzone.

Expected: the file is accepted.
Result: the dropzone indicates that the file is invalid.

**Comment by juanboca** [comment]
It seems to be related with: https://github.com/okonet/react-dropzone/issues/276

**Comment by asterite** [comment]
I tried specifying other "accept" types and it doesn't seem to work. My advice is to drop the "accept" attribute: in any case we are still doing a validation on the server side, so...
