### ISSUE TITLE
[Questionnaire] SMS and IVR are in lower case in some places of the UI

### ISSUE THREAD

**Issue by fgasperij** [instedd/ask#308]

**Comment by fgasperij** [comment]
<img width="343" alt="screen shot 2016-11-14 at 4 40 00 pm" src="https://cloud.githubusercontent.com/assets/1685226/20279902/26a94542-aa89-11e6-825f-ebb29ce6f6e0.png">

**Comment by pmallol** [comment]
Ok in Version: 0.4.0-dev-8ab670d (build 801)
