### ISSUE TITLE
[Survey] If the cutoff is set, and the last respondent doesn't answer, the survey will take too long to be completed

### ISSUE THREAD

**Issue by juanboca** [instedd/ask#309]
When the cutoff is set, if it is close to be reached, it limits the number of running respondents to only met the desired number. So when there is only one respondent needed to reach the target, it will start only one respondent and wait until it completes the survey, or gives timeout. This can make the survey to take too long to finish.

**Comment by mverzilli** [comment]
What should we do in this case? Maybe set a minimum batch size and use that? 

More formally:

let M = minimum batch size
let R = number of not contacted respondents
let C = pending respondents to reach the cutoff

```
if C <= 0 then survey completed
if C <= M and M <= R then batch M respondents
if C <= and M > R then batch R respondents
```

**Comment by waj** [comment]
I think the batch size as the maximum number of respondents that must be active at any time, unrelated to the cutoff settings and how close the survey is to finish.

**Comment by mverzilli** [comment]
That's out of the question :). 

In the context of this is issue, we need to specify how Ask will behave when the survey it's almost at the cutoff, but not done. One way of tackling it is by agreeing on a minimum number of respondents. 

Do you have any alternative solutions?

**Comment by waj** [comment]
Please confirm, but I think this can be solved just removing these lines: https://github.com/instedd/ask/blob/master/lib/ask/runtime/broker.ex#L64-L69
