### ISSUE TITLE
[Quiz] Add validations

### ISSUE THREAD

**Issue by asterite** [instedd/ask#315]
Add the following validations. These must not trigger when a step is added, only if it's collapsed or if it's the second time it's being loaded.

- [x] SMS message must not be blank if "SMS" mode is on
- [x] Voice message must not be blank if "Phone call" mode is on and 
- [x] There must be at least two responses
- [x] A response's response must not be blank
- [x] A response's SMS must not be blank if "SMS" mode is on
- [x] A response's "Phone call" must not be blank if "Phone call" mode is on
- [x] A response's "Phone call" must only consist of digits or `#` or `*`
- [x] A response's "response" can't appear more than once in a same step
- [x] A response's SMS value must not overlap other SMS values
- [x] A response's "Phone call" value must not overlap other SMS values

**Comment by asterite** [comment]
I started working on this in this branch: https://github.com/instedd/ask/tree/feature/315_quiz_validations

**Comment by mmuller** [comment]
Working as expected.
0.5.0-dev-38873bb (build 1384).
