### ISSUE TITLE
[Survey] Wizard. Placeholder for initial default values for input fields (retries and cutoff) is not displayed when loading the page

### ISSUE THREAD

**Issue by lmatayoshi** [instedd/ask#320]
Steps to reproduce:

1) Click the 'Add Survey' button
2) Select 'SMS with phone callback' in Channels and modes
3) Go to 'Schedule step'.

Obtained:
- Placeholders for input are not displayed

![no_placeholders](https://cloud.githubusercontent.com/assets/8591752/20435467/fa34801c-ad8a-11e6-91cc-361e448d1fce.png)
 
Expected:
- Placeholder is displayed, according to the mockup: https://projects.invisionapp.com/d/main#/console/8374235/182593580/preview

Comments:
- If you click in the input and then lost focus, the placeholder is displayed
- Same thing happens with 'cutoff' input field

**Comment by pmallol** [comment]
Ok in Version: 0.4.0-dev-9e45973 (build 1031)
