### ISSUE TITLE
[Survey] Define quotas for multiple choice variables

### ISSUE THREAD

**Issue by waj** [instedd/ask#333]
Add the option in the cutoff step to define quotas based on multiple choice questions

**Comment by nekron** [comment]
Quotas will be defined in a separated table with the following structure:
```
condition: {
  smokes: yes,
  gender: female
}, # the bucket definition
quota: 200, # the total number of respondents that must be contacted to fulfill the quota
count: 10, # the current number of respondents contacted
survey_id
```

On the other hand, the survey will have field named `quotas` that will contain an array with the selected variables that generate those buckets. This will be used mostly in runtime to know if the current question defines a quota or not. The idea is to avoid having to load all the buckets to know if the respondent fits into one of them for every question in the questionnaire.

The buckets will be sent to the API as a part of the survey, inside a `buckets` array.
