### ISSUE TITLE
Error when starting a Survey.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#344]
Found in version:
0.4.0-dev-8ab670d

Preconditions:
There is a Questionnaire 'Q'.
'Q' has a Numeric step 'N'.

Reproduce steps:
Create a Survey and use 'Q' as Questionnaire.
Start the Survey.
Go to edit 'Q'.
Replace the Numeric step 'N' with a Multiple choice step.
Create another Survey and use 'Q' as Questionnaire.
Start the Survey.

Actual result:
An error is displayed.
The following error is logged in the browser's console:
```PromiseRejectionEvent {isTrusted: true, promise: Promise, reason: TypeError: Cannot read property 'count' of undefined at t.value (http://ask-stg.instedd.org/js/a…, type: "unhandledrejection", target: Window…}```

Expected result:
The Survey can be started properly after editing the Questionnaire.

Additional information:
https://sentry.io/instedd/ask/issues/185511408/

**Comment by juanboca** [comment]
Errors found in:
Line 156 of SurveyShow.jsx
```<tr>
              <td>Pending</td>
              <td>{ respondentsStats.pending.count }</td>
              <td>{ Math.round(respondentsStats.pending.percent) }%</td>
            </tr>```

Called from line 105 of SurveyShow.jsx
```table = this.dispositions(respondentsStats)```
`respondentsStats.pending` is ```undefined```


The error is only on the view, the survey is started correctly.

**Comment by asterite** [comment]
I don't think this is critical. Once a survey is started its associated one shouldn't be able to modify its questionnaire. I think that's out of the scope for now.

**Comment by juanboca** [comment]
The questionnaire doesn't need to be modified. This error happens also with an unedited questionnaire.

**Comment by mmuller** [comment]
Ok in version 0.4.0-dev-ab1556c
