### ISSUE TITLE
Survey status is not immediately updated

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#345]
Found in version:
0.4.0-dev-8ab670d

Reproduce steps:
Start a Survey 'S'.
Complete the Survey 'S' (send the responses for each question).
In the Survey overview observe the percent value for the status 'Completed'.
Observe the Surveys index.

Actual result:
The Survey 'S' status is 'running'.
The Survey chart reads '100% of target completed'.

Expected result:
The Survey status should be immediately updated.

<img width="514" alt="screen shot 2016-11-24 at 10 48 04 am" src="https://cloud.githubusercontent.com/assets/518152/20602813/a7fc75ae-b23d-11e6-8017-574e74428dc7.png">

**Comment by mverzilli** [comment]
Did you refresh the page after completion?

**Comment by mmuller** [comment]
@mverzilli yes, I did.
