### ISSUE TITLE
Create a test questionnaire

### ISSUE THREAD

**Issue by nditada** [instedd/ask#35]
Straight into the DB with 1 multiple choice question

**Comment by waj** [comment]
Questionnaire
 - name
 - modes (array)

QuestionnaireStep
 - questionnaire_id
 - type
 - settings (map)

**Comment by waj** [comment]
There is no QuestionnaireStep entity. `Questionnaire` stores a JSON in the `steps` field like:
```json
[
  {
    "id": "17141bea-a81c-4227-bdda-f5f69188b0e7",
    "type": "multiple-choice",
    "title": "Do you smoke?",
    "choices": [
      {
        "value": "Yes",
        "responses": ["Yes", "Y", "1"]
      },
      {
        "value": "No",
        "responses": ["No", "N", "1"]
      }
    ]
  }
]
```

**Comment by waj** [comment]
Make this flow the default of any newly created Questionnaire
