### ISSUE TITLE
Text Wrap - Phone Call Selector

### ISSUE THREAD

**Issue by steesdale** [instedd/ask#353]
The "Phone CALL" text for the IVR slider wraps a bit oddly when screen is not at full width... 

<img width="1080" alt="screen shot 2016-11-30 at 10 01 31 am" src="https://cloud.githubusercontent.com/assets/3987608/20759968/2bde6ad0-b6e4-11e6-8cb0-39a3d1101ab7.png">

**Comment by mverzilli** [comment]
Fixed in 0.5.0
