### ISSUE TITLE
[Questionnaire] Add option to end survey or go to specific question in Numeric question

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#371]
As for Version: 0.4.0-dev-542c1ec (build 917), there is no option to End survey when a certain number is answered or to continue to an specific question.

It would be useful to have that option if, for example, the following questions would vary if the respondent is more or less than 50 years old, or if instead of answering the question, the respondent would rather end it.

**Comment by fgasperij** [comment]
The skip logic for numeric steps was added in this ticket https://github.com/instedd/ask/issues/322
