### ISSUE TITLE
[Questionnaire] 'Add language' link is missing its style

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#374]
Version: 0.4.0-dev-76a6b57 (build 964)

1. Open a Project
2. Click on Questionnaires
3. Create a new Questionnaire

Obtained:
The 'Add language' link has a different style considering the [design](https://projects.invisionapp.com/d/main#/console/8374235/196343921/preview)
![screen shot 2016-12-06 at 3 36 23 pm](https://cloud.githubusercontent.com/assets/9214460/20938454/f25a8f42-bbc9-11e6-8577-583b657a6828.png)

**Comment by juanboca** [comment]
Duplicated of: https://github.com/instedd/ask/issues/357
