### ISSUE TITLE
[Questionnaire] Improve the name of the CSV of translations.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#383]
Now the name of the file is `download.csv`.
In order to provide more information it would be useful to replace that name with something like `questionnaire_1_translations.csv`.

**Comment by mverzilli** [comment]
@juanboca I'd suggest to move this to the next milestone so we don't need to maintain it in the Douglas Fir branch.

**Comment by mmuller** [comment]
Ok in version 0.4.0-dev-ab1556c
