### ISSUE TITLE
[Quiz] Quota completed message in plural/singular

### ISSUE THREAD

**Issue by juanboca** [instedd/ask#386]
Also, when the message is closed, its not a Card component
![screen shot 2016-12-07 at 10 53 34 am](https://cloud.githubusercontent.com/assets/488553/20970256/6cfe7cee-bc6b-11e6-938b-942a53b1b2f5.png)
![screen shot 2016-12-07 at 10 53 27 am](https://cloud.githubusercontent.com/assets/488553/20970257/6d241134-bc6b-11e6-820b-b1df5153d1a2.png)

**Comment by asterite** [comment]
Which one should stay?

**Comment by juanboca** [comment]
There is no design for this on Invision, but since there are 2 different prompts, I would say that it should be in plural
