### ISSUE TITLE
Guisso does not redirect to ask permission if logged out

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#390]
- Ensure the user is currently signed out of guisso and the instedd platform
- Navigate to create a new channel in Ask
- A guisso popup asking to login is shown
- Login with instedd user

Expected: Ask asks the user for permission to access her data
Actual: User is redirected to authorizations page, and must close the popup and request to create a channel again

http://recordit.co/Azt0f8wX56

**Comment by juanboca** [comment]
This should be fixed when #339 is implemented

**Comment by mverzilli** [comment]
#339 is closed and I just verified this works in ask-stg.instedd.org (which has 0.5.0).

**Comment by mmuller** [comment]
Working fine in version 0.5.0-dev-38873bb (build 1384)
