### ISSUE TITLE
Changing language in a questionnaire should keep the phone call keys

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#394]
- Create a question of type Multiple choice in a questionnaire with multiple languages and SMS+Voice 
- Enter a few options with SMS and Phone call keys
- Change the language

Expected: Though the keys for SMS are cleared out, the ones for Voice should be kept, since they are numeric values and not language-dependent
Actual: Both SMS and Voice keys are cleared out

**Comment by mmuller** [comment]
Ok in version 0.5.0-dev-261e4c8 (build 1196)
