### ISSUE TITLE
[Questionnaire] Error uploading audio

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#399]
Error when uploading audio for a non-English language (Spanish) in a questionnaire with multiple langs. File is in m4a format. Link to download: https://www.dropbox.com/s/zrbdnzi3tfymx57/fuma.m4a?dl=0

`"Cannot read property 'join' of undefined"`

**Comment by juanboca** [comment]
The system only accepts `.mp3` or `.wav` audio files. 
This should be explained to the user, and should be validated on the audios controller to only accept the correct file types.
