### ISSUE TITLE
[Questionnaire] Other languages listed display a right arrow that has no particular use

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#400]
Version: 0.4.0-dev-511e025 (build 1007)

1. Create a Questionnaire
2. Add 'Spanish' as another language
3. Hover Spanish listed under Other languages

Obtained:
Spanish shows two arrows when hovered, one to make the language the primary one and another right facing arrow that has no purpose and is somewhat confusing on what it should or should not do.

![screen shot 2016-12-07 at 11 53 47 am](https://cloud.githubusercontent.com/assets/9214460/20972741/a3d12240-bc74-11e6-8362-3329e09e173f.png)

**Comment by fgasperij** [comment]
The right arrow should give the idea that the buttons help the user to navigate through the different languages. In the future, the whole button will be clickable (not only the right arrow) and it will switch the language the questionnaire is displaying.
