### ISSUE TITLE
[Survey] Respondent remains in Active state if call is incomplete

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#401]
- Create a survey with a questionnaire with several questions and several languages (for this test, the survey was created with Phone with SMS fallback, with one retry for each channel)
- Start the survey with a single respondent
- Ask calls the user, who answers the call, but does not enter anything in the phone, thus the first step (language selection, though might happen the same with other step) timeouts and Ask/Verboice hangs up

Expected: the call is considered failed, and Ask retries calling the user
Actual: the call is marked as completed in Verboice, and stuck as Active in Ask

<img width="351" alt="screen shot 2016-12-07 at 12 03 02 pm" src="https://cloud.githubusercontent.com/assets/429604/20972886/21c737c0-bc75-11e6-819f-c72992ad6c6f.png">
<img width="1073" alt="screen shot 2016-12-07 at 12 02 45 pm" src="https://cloud.githubusercontent.com/assets/429604/20972888/23de774e-bc75-11e6-83c4-d6f1f43d5580.png">

**Comment by juanboca** [comment]
The respondent was switched to `stalled` state after the channel was changed to the fallback one, and the 10 minutes of timeout were reached.
