### ISSUE TITLE
[Quiz] When swtiching default language, the language selection step prompts gets changed

### ISSUE THREAD

**Issue by juanboca** [instedd/ask#404]
If the user writes SMS and IVR prompts for the language selection step, and then switches the default language to a different one, the texts are cleared. If the user changes to the original default language the texts are still there. 
The language selection step should have the same texts and audio files independently of the default language

**Comment by asterite** [comment]
Keep the language selection step inside the steps array, just don't let it have `sms` and `ivr` properties inside a language key.

**Comment by mmuller** [comment]
Ok in version 0.5.0-dev-38873bb (build 1384)
