### ISSUE TITLE
[Survey] Overview table is missing the Undeliverable label

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#408]
Version: 0.4.0-dev-c76692f (build 1011)

1. Run a survey
2. Go to Overview

Check the [design](https://projects.invisionapp.com/d/main#/console/8374235/198000671/preview)
At the moment the table only shows Full and Partials
![screen shot 2016-12-07 at 2 11 58 pm](https://cloud.githubusercontent.com/assets/9214460/20978580/1fd5a77c-bc88-11e6-85a4-07b0f19e1e41.png)

**Comment by asterite** [comment]
Closing as invalid: there's no way to know what quota a respondent will fall in if you never could contact it. The provided design screenshot is **wrong**.
