### ISSUE TITLE
[Quotas] Error when quota is completed

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#416]
When a respondent answers the last question for a quota criteria, Ask fails with the following error, delivery from Nuntium fails, and the message is marked as delayed/failed.

Happened with a questionnaire with a quota message set, and via SMS.

```
20:57:45.953 [error] #PID<0.692.0> running Ask.Endpoint terminated
Server: ask-stg.instedd.org:80 (http)
Request: GET /callbacks/nuntium/?application=Ask+%28dev%29&application=Ask+%28dev%29&body=8&channel=FakeChannel&country=RB&from=sms%3A%2F%2F9992001&guid=c2ed7571-a583-23b2-14e2-1a63e5844edf&subject=&to=sms%3A%2F%2F0
** (exit) an exception was raised:
    ** (CaseClauseError) no case clause matching: {:end, {:prompt, "Quota has been completed"}}
        (ask) lib/ask/runtime/nuntium_channel.ex:70: Ask.Runtime.NuntiumChannel.callback/2
        (ask) web/controllers/callback_controller.ex:1: Ask.CallbackController.action/2
        (ask) web/controllers/callback_controller.ex:1: Ask.CallbackController.phoenix_controller_pipeline/2
        (ask) lib/ask/endpoint.ex:1: Ask.Endpoint.instrument/4
        (ask) lib/phoenix/router.ex:261: Ask.Router.dispatch/2
        (ask) web/router.ex:1: Ask.Router.do_call/2
        (ask) lib/plug/error_handler.ex:64: Ask.Router.call/2
        (ask) lib/ask/endpoint.ex:1: Ask.Endpoint.phoenix_pipeline/1
```

<img width="968" alt="screen shot 2016-12-07 at 5 59 37 pm" src="https://cloud.githubusercontent.com/assets/429604/20986332/f5b6f148-bca6-11e6-8526-ca265d8e82e1.png">

**Comment by spalladino** [comment]
Note that the answer *is* registered, and bucket completeness set to 200%

<img width="757" alt="screen shot 2016-12-07 at 6 00 44 pm" src="https://cloud.githubusercontent.com/assets/429604/20986376/31f68d6c-bca7-11e6-9474-6c270154d0f6.png">

<img width="1006" alt="screen shot 2016-12-07 at 6 00 53 pm" src="https://cloud.githubusercontent.com/assets/429604/20986377/33e757aa-bca7-11e6-8921-c3335438c445.png">

**Comment by juanboca** [comment]
Fixed on https://github.com/instedd/ask/commit/b040c1ca838b57865c775b021b73cdd19b390ede
