### ISSUE TITLE
Remove last saved timestamp from the Survey view.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#425]
Found in version: 0.4.0-dev-9e45973

Reproduce steps:
Create a Survey.
Fill all the mandatory fields.
Start the Survey.

Actual result:
A message reads 'Last saved 23 hours ago'.

Expected:
The last saved timestamp should not be displayed on the Survey view.
https://projects.invisionapp.com/d/main#/console/8374235/186815707/preview

Screenshot:
<img width="1443" alt="screen shot 2016-12-13 at 4 31 54 pm" src="https://cloud.githubusercontent.com/assets/518152/21155628/9bba223c-c151-11e6-8e93-e209397f2e9b.png">

**Comment by juanboca** [comment]
This is not working well. 
On top of that, on the designs there is no "last saved" message for this screen. Maybe we should remove it.


https://projects.invisionapp.com/d/main#/console/8374235/190849673/preview

**Comment by nekron** [comment]
Besides that, when switching from one survey to another you get a glimpse of the last saved timestamp of the previous one. There is also a sync issue here that we should check out.

**Comment by mmuller** [comment]
Ok in version 0.4.0-dev-ab1556c
