### ISSUE TITLE
Show invalid state for quotas that are pointing to a variable without question

### ISSUE THREAD

**Issue by nickdit** [instedd/ask#426]
If the question that was storing a value in a variable gets deleted and there was a quota using that variable, that quota is now in an invalid state, i.e. it would never be filled. We need to show that somewhere.

**Comment by nditada** [comment]
We should not delete the quota in this situation, it is highly likely the user might be creating that new variable in a following action.

**Comment by jkicillof** [comment]
https://projects.invisionapp.com/d/main#/console/8374235/229271470/preview
