### ISSUE TITLE
Files cannot be uploaded if its name includes comma.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#427]
Found in version: 0.4.0-dev-9e45973

Preconditions:
There is a Questionnaire 'Q'.
There is a file 'F'.
The name of 'F' includes comma. 'December 14, 2016 at 11_35_42 AM.wav' was used in this test.

Reproduce steps:
Go to edit 'Q'.
Enable the 'Phone call' mode.
Add a Step.
Select 'Upload a file'.
Choose the file 'F'.

Obtained:
Nothing happens, the file cannot be uploaded.

**Comment by juanboca** [comment]
Solved on this commit: https://github.com/instedd/ask/commit/32bcdc5c59b5cc19c2889b8cdaa3a395337fdb9e

**Comment by mmuller** [comment]
Ok in version 0.4.0-dev-ab1556c
