### ISSUE TITLE
CSV Upload of Language Error

### ISSUE THREAD

**Issue by steesdale** [instedd/ask#438]
What happened: 
- I create a short questionnaire in english 
- I added two languages, french and arabic
- I downloaded the english version and translated the french and arabic, adding it to the csv
- I uploaded it to the tool 
- translations for options came through.  translations for sms/ivr scripts did not appear. 

What I expected
- That the ivr sms translations for the step / SMS message would have appeared. 

See here for file
https://drive.google.com/file/d/0B_RUEKy5Lc7BMU0teF9TWEhMMlE/view?usp=sharing

**Comment by nditada** [comment]
@steesdale the arabic translations are missing the quotes. Can you describe how you created the .csv?

**Comment by steesdale** [comment]
I used google sheets to do the translations.  Downloaded the .csv directly from sheets.

**Comment by asterite** [comment]
It works for me. I see some translations have a semicolon at the end... do you have this semicolon in the questionnaire prompts too?

**Comment by steesdale** [comment]
ah that did it. thanks!
