### ISSUE TITLE
Audio File Upload - Multiple Languages

### ISSUE THREAD

**Issue by steesdale** [instedd/ask#439]
What I did: 
- I created a questionnaire and added two languages (english / french) 
- I promoted french to the primary language
- I changed the text to speech option to audio file upload
- I loaded a french audio file, to support the french call flow content. 
- I received a generic error that there was an issue. 
![screen shot 2016-12-16 at 1 09 58 pm](https://cloud.githubusercontent.com/assets/3987608/21275133/fa4ae48a-c390-11e6-9704-7af85136e62a.png)

What I expected: 
- That for each new language we add
- For each step we could use text to speech or an audio file
- That when promoting a language, I could load an audio recording for that specific language.

**Comment by mverzilli** [comment]
@mmuller would you verify whether this still happens and close the issue if it doesn't?

**Comment by steesdale** [comment]
working ok now, closing.
