### ISSUE TITLE
Invite other users to a project

### ISSUE THREAD

**Issue by waj** [instedd/ask#442]
Invitations can be sent by email (or sharing a link). This link can be used only once to join an existing project.

The invitation must already indicate the level of access of the new user (editor or reader).

- [x] Invite link popup
- [x] Invites table
- [x] Accept invitation screen
- [x] Mail sender

**Comment by lmatayoshi** [comment]
Design for invitations:

![invite](https://cloud.githubusercontent.com/assets/8591752/21457179/e7c711f0-c90b-11e6-8b28-344e86ee4b51.JPG)

**Comment by mmuller** [comment]
Working as expected.
Version: 0.5.0-dev-38873bb (build 1384)
