### ISSUE TITLE
[Quiz] Error message for invalid options

### ISSUE THREAD

**Issue by waj** [instedd/ask#444]
https://projects.invisionapp.com/share/3U8BARPXJ#/screens/193624627

**Comment by fgasperij** [comment]
- which options should the skip logic combo offer?
- how should the error message be used on the flow?

**Comment by waj** [comment]
Ignore the skip logic dropdown. The error message will be used on #451.

**Comment by mmuller** [comment]
Ok in version 0.5.0-dev-261e4c8 (build 1196)
