### ISSUE TITLE
[Survey] Allow selecting more than one mode

### ISSUE THREAD

**Issue by waj** [instedd/ask#449]
https://projects.invisionapp.com/share/3U8BARPXJ#/screens/183286761

Currently the modes are stored as a JSON array (i.e.: ["sms", "ivr"]). In order to allow many modes selected, store this as an array of arrays. Migrate existing questionnaires.

**Comment by mmuller** [comment]
Ok in version 0.5.0-dev-261e4c8 (build 1196)
