### ISSUE TITLE
[Survey] Comparisons step

### ISSUE THREAD

**Issue by waj** [instedd/ask#450]
When more than one questionnaire and/or more than one mode is selected, display the comparisons step in the survey wizard.

https://projects.invisionapp.com/share/3U8BARPXJ#/screens/182593571

Please let's talk about how to store this info in the DB before starting.

**Comment by waj** [comment]
Store the ratios in a new field on the survey table, containing a JSON like:

```json
[
  {
    "questionnaire_id": 1,
    "mode": ["ivr"],
    "ratio": 0.15
  },
  {
    "questionnaire_id": 2,
    "mode": ["sms"],
    "ratio": 0.35
  }
]
```

**Comment by mmuller** [comment]
Working as expected.
Version: 0.5.0-dev-38873bb (build 1384)
