### ISSUE TITLE
[Questionnaire] Error when trying to edit 'Quota completed messages'

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#454]
Found in Version: 0.4.0-dev-183b0b5 (build 1080)

1. Open a project
2. Go to Questionnaires
3. Create a new questionnaire
4. Click on step 'Quota completed messages'

Obtained:
A 'Sorry, something went wrong. Please go to the home page" error message pops up.
The console shows an ErrorEvent reading: `"Uncaught TypeError: Cannot read property 'en' of null"
`

**Comment by waj** [comment]
Fixed with 5015fc29f2b6fc7df99281367f17263d357d8a55 (cherry pick of 248419af68117431e1a6e7a4b2b0f1f51e943f6c)
