### ISSUE TITLE
Add SMS and Voice Clarifications in Channels setup

### ISSUE THREAD

**Issue by edjez** [instedd/ask#455]
![image](https://cloud.githubusercontent.com/assets/1182549/21369961/581a3360-c6be-11e6-9761-8efa037c50d2.png)
Expected : Descriptions would read something that doesnt require InSTEDD jargon
Nuntium (SMS and messaging)  ; Verboice (Voice)

**Comment by mverzilli** [comment]
Fixed in 0.5.0

**Comment by mmuller** [comment]
Ok in version 0.5.0-dev-38873bb (build 1384)
