### ISSUE TITLE
Redesign initial state for Quiz

### ISSUE THREAD

**Issue by nditada** [instedd/ask#456]
The current initial state for a Quiz puts a lot of emphasis in the Quota Message and the "Add Step" looks like a smaller action in comparison. 

![screen shot 2016-12-21 at 10 30 05 am](https://cloud.githubusercontent.com/assets/1359189/21391003/574d002a-c768-11e6-8b56-66e74b0d5be9.png)

**Comment by waj** [comment]
The design already contemplates an "onboarding" screen the first time and after that every questionnaire should start with an empty multiple choice step.

**Comment by mverzilli** [comment]
This is addressed by #491.
