### ISSUE TITLE
[Survey] Quotas popup is scrollable

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#458]
Version: 0.5.0-dev-6b4a50c (build 1092)

![screen shot 2016-12-21 at 2 04 43 pm](https://cloud.githubusercontent.com/assets/9214460/21398554/812c1f20-c786-11e6-835e-9fe3c75cac04.png)

**Comment by Mscebba** [comment]
Fixed on commit https://github.com/instedd/ask/commit/c0f62a14635bb87cf10955b0aa6db916e7002eb8

**Comment by mmuller** [comment]
Ok in version 0.5.0-dev-261e4c8 (build 1196)
