### ISSUE TITLE
[Survey] 402 error when trying to launch a survey

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#461]
Version: 0.5.0-dev-6b4a50c (build 1092)

1. Open a project
2. Create a survey
3. When reaching a 100% progress, click on the launch survey button

Obtained:
![screen shot 2016-12-21 at 3 58 43 pm](https://cloud.githubusercontent.com/assets/9214460/21402245/74cee2d4-c796-11e6-970c-da2579cccea3.png)

**Comment by waj** [comment]
This was probably a configuration error on the server or on any of the channels. A better error message describing the problem might be displayed after #524 is completed.
