### ISSUE TITLE
[Survey] Percentage of target completed exceeds 100% in survey overview

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#465]
Version: 0.5.0-dev-6b4a50c (build 1092)

Preconditions:
There is a survey running and all 10 respondents were contacted

1. Navigate to survey overview

Observed:
The percentage of completed target exceeds the 100% limit.

![screen shot 2016-12-22 at 4 06 47 pm](https://cloud.githubusercontent.com/assets/9214460/21455968/51146d64-c903-11e6-82cd-8f44666a7969.png)

**Comment by waj** [comment]
Let's show 100% when that happens
