### ISSUE TITLE
[Quiz] Variable name autocomplete shows duplicate variables

### ISSUE THREAD

**Issue by waj** [instedd/ask#470]
Check if the variable names aren't stored with spaces

**Comment by waj** [comment]
Variable names should never contain spaces. Let the reducer trim all spaces when setting the value.

**Comment by asterite** [comment]
Should be fixed by https://github.com/instedd/ask/commit/5ecf921e9496cda98e62813c5e755d6348f0e686

**Comment by mmuller** [comment]
Ok in version 0.5.0-dev-38873bb (build 1384)
