### ISSUE TITLE
[Quiz] Autocomplete primary language

### ISSUE THREAD

**Issue by waj** [instedd/ask#475]
While typing a prompt text in the primary language, lookup up for translations options that matches:

- same project
- same mode
- same source language
- containing typed text (case insensitive)

If one of the autocomplete options is selected by the user, the text for all the available translations are automatically filled.

## Progress

- [x] SMS Prompt
- [x] IVR Prompt
- [x] Choice SMS
- [x] Quota completed msg
- [x] Error msg

**Comment by asterite** [comment]
- [ ] SMS Prompt
- [ ] IVR Prompt
- [ ] Choice SMS
- [ ] Quota completed msg
- [ ] Error msg

**Comment by mmuller** [comment]
Working as expected.
0.5.0-dev-38873bb (build 1384)
