### ISSUE TITLE
[Quiz] Autocomplete other languages

### ISSUE THREAD

**Issue by waj** [instedd/ask#476]
While typing a prompt text in other languages, lookup up for translations options that matches:

- same project
- same mode
- same target language
- same text for the primary language
- containing typed text in the translation (case insensitive)

## Progress

- [x] SMS Prompt
- [x] IVR Prompt
- [x] Choice SMS
- [x] Quota completed msg
- [x] Error msg

**Comment by asterite** [comment]
- [x] SMS Prompt
- [x] IVR Prompt
- [ ] Choice SMS
- [ ] Quota completed msg
- [ ] Error msg

**Comment by mmuller** [comment]
Working as expected.
Version 0.5.0-dev-38873bb (build 1384).
