### ISSUE TITLE
Users are not receiving "Error messages".

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#483]
Found in version 0.5.0-dev-261e4c8 (build 1196)

Preconditions: 
There is a Questionnaire 'Q'.
'Q' has a Multiple Choice step 'S' with two response options ('1' and '2').
'Q' has an Error Message.

Reproduce steps:
Create an Survey using the Questionnaire 'Q'.
Run the Survey.
Send '3' as response.

Obtained:
The error message is not received by the user.

Expected:
The error message should be received by the user because '3' is an invalid response.

**Comment by nekron** [comment]
Unable to reproduce. Error messages are working fine in staging: version 0.5.0-dev-38873bb (build 1384).

It could be related to #576.

**Comment by mmuller** [comment]
This functionality is working as expected in version 0.5.0-dev-38873bb (build 1384).
I think that this issue was not related to #576 because I couldn't reproduce that issue in the current version.
