### ISSUE TITLE
[Questionnaires] Add tooltip to duplicate icon

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#485]
Found in version 0.5.0-dev-261e4c8 (build 1196)

<img width="1415" alt="screen shot 2016-12-30 at 9 12 53 pm" src="https://cloud.githubusercontent.com/assets/518152/21574610/af8b1704-ced4-11e6-9d99-646634eb48bd.png">

**Comment by asterite** [comment]
Should this be a browser tooltip or a materialize tooltip?

**Comment by mmuller** [comment]
Working as expected.
Version: 0.5.0-dev-38873bb (build 1384)
