### ISSUE TITLE
[survey] Mode and Questionnaire selection marks the step as incompleted when switching between single mode and comparison

### ISSUE THREAD

**Issue by nekron** [instedd/ask#488]
Steps to reproduce:
- Enable comparison
- Select 2 or more quizzes or modes
- Disable comparison
- Enable comparison
- Select a second quiz or mode
- The step is marked as incomplete

After reaching this point, selecting and deselecting the original mode or quiz has the opposite behavior on the step: selecting it marks the step as incomplete, but deselecting it marks it completed.

**Comment by mmuller** [comment]
Working as expected.
Version: 0.5.0-dev-38873bb (build 1384)
