### ISSUE TITLE
[Quiz] Questionnaire onboarding

### ISSUE THREAD

**Issue by waj** [instedd/ask#491]
The first time a user creates a questionnaire, show the onboarding screen (the questionnaire is created without any step)
https://projects.invisionapp.com/share/3U8BARPXJ#/screens/196343921

Once the user clicks on the "understood" link, create an empty step. After that, every new questionnaire created must have the same empty step.

**Comment by lmatayoshi** [comment]
Will be the onboarding_enabled info stored in the database? In which format?

**Comment by lmatayoshi** [comment]
The decision resulted in having an 'onboarding' column in 'users' table containing a JSON value with different onboarding configurations

**Comment by lmatayoshi** [comment]
Final approach resulted in having a 'settings' column in 'users' containing various configurations, including onboarding

**Comment by lmatayoshi** [comment]
Still pending in back-end:
- [ ] Set 'settings' to empty JSON when creating a new user. At the moment, user creation is managed by 'Addict' so some configuration will be needed in order to do that.

**Comment by mverzilli** [comment]
Due to limitations in Addict, we're going to replace it with Coherence. This issue now depends on that, which we're tracking in #552.

**Comment by mmuller** [comment]
On-boarding added as expected. (Version ee7b498)
