### ISSUE TITLE
[Quiz] Audio component is not refreshed when switching language

### ISSUE THREAD

**Issue by juanboca** [instedd/ask#495]
Steps to reproduce:
- Create a questionnaire
- Add a step
- Switch IVR to upload a file
- Upload an audio file
- Add a language
- Switch to the new language (by changing the primary language or just selecting it)
- Switch IVR to upload a file
- Upload a different audio file
- Switch to the first language

The audio component will keep showing the audio for the second language, instead of the audio for the first language.

This happens with a normal questionnaire step, and also with the Quota Completed Message and Error message.

**Comment by mmuller** [comment]
Ok in version 0.5.0-dev-38873bb (build 1384)
