### ISSUE TITLE
[Quiz] An exception is raised when navigating through different questionnaires

### ISSUE THREAD

**Issue by juanboca** [instedd/ask#500]
On a project that has at least 2 questionnaires, go to the questionnaires list.
Enter on one, wait until the page loads completely, and press the back button.
Click on other questionnaire. An exception is raised:
![screen shot 2017-01-06 at 11 32 35 am](https://cloud.githubusercontent.com/assets/488553/21720766/c160614e-d403-11e6-97fa-054bd235a5dd.png)

**Comment by mmuller** [comment]
Working as expected.
Version 0.5.0-dev-38873bb (build 1384).
