### ISSUE TITLE
Apply style to invite modal

### ISSUE THREAD

**Issue by lmatayoshi** [instedd/ask#501]
Navigate to /projects/projectId/collaborators

At the moment, the invite modal looks like this:

![invite_1](https://cloud.githubusercontent.com/assets/8591752/21723874/d6b0ea98-d410-11e6-94ca-a9e99580fc1b.png)
![invite_2](https://cloud.githubusercontent.com/assets/8591752/21723873/d6b0d198-d410-11e6-8e1f-026abb30e2dc.png)

It should be adapted to the following mockup:

https://projects.invisionapp.com/d/main#/console/8374235/212897400/preview

**Comment by lmatayoshi** [comment]
Instead of appear and disappearing, 'SEND' button and 'invite link' should toggle between 'inactive' and 'active', depending if both 'email' and 'role' were completed

**Comment by mmuller** [comment]
Ok in version  0.5.0-dev-38873bb (build 1384)
