### ISSUE TITLE
Apply style to Invite Confirmation screen

### ISSUE THREAD

**Issue by lmatayoshi** [instedd/ask#502]
Login with a new user and paste an invitation link in the url generated with the invite modal.

At the moment, the confirmation screen looks like this:

![confirm_invitation](https://cloud.githubusercontent.com/assets/8591752/21724326/b11592aa-d412-11e6-808f-e801bc688aa5.png)

It should be adapted to the following mockup:

https://projects.invisionapp.com/d/main#/console/8374235/212897398/preview

**Comment by mmuller** [comment]
Ok in version 0.5.0-dev-38873bb (build 1384)
