### ISSUE TITLE
[Quiz] SMS and IVR prompts input fields are taller after edit

### ISSUE THREAD

**Issue by juanboca** [instedd/ask#503]
After clicking once on the input field and losing focus, the SMS and IVR input fields get 10 or 15px taller than when the component was first rendered. 
![screen shot 2017-01-06 at 2 44 49 pm](https://cloud.githubusercontent.com/assets/488553/21727138/9e9ec306-d41e-11e6-8d2e-418bfad5aa57.png)
![screen shot 2017-01-06 at 2 44 59 pm](https://cloud.githubusercontent.com/assets/488553/21727137/9e78a734-d41e-11e6-9045-a7016d9c8617.png)

**Comment by mmuller** [comment]
Working as expected.
Version 0.5.0-dev-38873bb (build 1384).
