### ISSUE TITLE
Error in Broker don't show up in console

### ISSUE THREAD

**Issue by asterite** [instedd/ask#507]
Now that Sentry was added in the backend, whenever an exception happens it is reported to Sentry but never shown in the console. This makes it impossible to understand what went wrong when a test fails.

Showing the exception with `IO.inspect(e)` helps, but you loose the location of the error.

**Comment by asterite** [comment]
A workaround for this, which I'm using, is to comment all the `try do` blocks in the source code, but this obviously isn't a long-term solution.

**Comment by waj** [comment]
This is already fixed
