### ISSUE TITLE
Respondents table is not correctly displayed for long questionnaires.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#515]
Found in version: 0.4.1 (build 1121)

Reproduce steps:
Create a long Questionnaire (in this test the Questionnaire has up to 15 questions).
Create a Survey for that Questionnaire.
Run the Survey.
Complete the Survey.
Navigate to the Respondents tab.
Observe the Respondents table.

Obtained:
The Respondents table is not correctly displayed.

Screenshot:
<img width="1669" alt="screen shot 2017-01-10 at 10 46 08 am" src="https://cloud.githubusercontent.com/assets/518152/21808611/c6a78cc8-d722-11e6-92ad-bb2d4dbac1d9.png">

**Comment by waj** [comment]
Let's make the table horizontally scrollable

**Comment by mmuller** [comment]
The table is horizontally scrollable properly in version 82e4a29
