### ISSUE TITLE
[Channels] Ask confirmation before disabling a provider

### ISSUE THREAD

**Issue by waj** [instedd/ask#525]
Right now when a channel provider is disabled, all the channels are deleted.

Let's add a confirmation popup with the message: "Do you want to delete the channels provided by [provider]?" and the buttons "Yes", "No", "Cancel".

The channels then must be deleted only if "Yes" is replied. If the users replies "No", only the OAuth authorization is removed from the system.

**Comment by asterite** [comment]
What happens when you re-enable the provider? Channels with the same name should be overwritten, right?

Also, what's the use case for disabling a provider? Why not let a single option to refresh the channel list?

**Comment by waj** [comment]
When the provider is re-enabled the channels are synchronized again (this is already working). 

The option to refresh the channels is already there. The idea of disabling/enabling the provider is to have the chance to link with a different user or to fix auth issues.

**Comment by mmuller** [comment]
In version 24d37f0 the functionality is working as expected.
