### ISSUE TITLE
[Survey] Respondent dropzone is not highlighting when hovering with a file

### ISSUE THREAD

**Issue by waj** [instedd/ask#526]
https://projects.invisionapp.com/d/main#/console/8374235/188748963/preview

**Comment by asterite** [comment]
The style works if we remove the `accept=".csv"` attribute. But if we remove it then any file could be uploaded (which is of course not true because we ca check that on the server side). Other variants of the `accept` attribute value don't work well on IE. What should we do?

**Comment by juanboca** [comment]
This was a temporary fix to allow the dropzone to work on IE. I don't know if there is a permanent solution for this to work properly both on Chrome and IE.
Perhaps we will need to change the library

**Comment by mverzilli** [comment]
I think a cool compromise would be to conditionally set the `accept` attribute based on the detected browser. If it's IE, we set `accept=".csv"`. It won't react to hover, but at least it'll work. If it's not IE, we configure it properly and get back the highlighting effect on hover.

**Comment by mverzilli** [comment]
Or, just remove the `accept` and validate the extension

**Comment by mmuller** [comment]
Working properly in version b706119
