### ISSUE TITLE
[Collaborators] An invitation can be accepted by a user that's already a collaborator

### ISSUE THREAD

**Issue by waj** [instedd/ask#536]
After the invitation is accepted, the project fails to load.

If the user is already a collaborator of the project, redirect to the project page instead.

**Comment by asterite** [comment]
@waj Should the user be redirected before even accepting the invitation (because he already belongs to the project) or after accepting it?

**Comment by waj** [comment]
The invitation must not be accepted because the user is already a member. We could show a message to the user explaining that he/she is already a member and redirect to the project page. As we currently don't have a design for this I thought it could be acceptable to just redirect to the project page without any message.

**Comment by mverzilli** [comment]
This now depends on the move to Coherence (#552).

**Comment by pmallol** [comment]
The user invited is redirected to project as expected in Version: 0.6.0-dev-9b892e8 (build 1526)
