### ISSUE TITLE
[Copywriting] Lorem Ipsum texts in landing page

### ISSUE THREAD

**Issue by mverzilli** [instedd/ask#537]
All sections in the landing page (except "Collect opinions") have "lorem ipsum" stubs.

**Comment by waj** [comment]
@nditada @edjez we need contents for this

**Comment by nditada** [comment]
https://docs.google.com/document/d/1-td_RnxhPlhdYrrGzu0WJplITl8_V4fdy4BBT0eAHqI/edit?usp=sharing

@jkicillof @Mscebba you might need to adapt the layout/design of the landing page to conform to this copy.

**Comment by nditada** [comment]
And let's replace the screenshots with these: 
![questionnaire designer](https://cloud.githubusercontent.com/assets/1359189/26498983/5620a764-4207-11e7-8b31-89d53ea80366.png)
![respondents](https://cloud.githubusercontent.com/assets/1359189/26498984/562517c2-4207-11e7-9d68-121c3725875a.png)
![survey designer](https://cloud.githubusercontent.com/assets/1359189/26498985/562c659a-4207-11e7-89eb-8f3c75661827.png)

**Comment by mmuller** [comment]
Working properly in version 73cc296

@waj the screenshots were not replaced.
