### ISSUE TITLE
[Login/Sign up] Pressing enter should submit

### ISSUE THREAD

**Issue by mverzilli** [instedd/ask#539]
Fill the log in or sign up forms. Press enter.

Expected: the same as clicking the main action (Sign In/Sign Up) button.
Actual: nothing happens.

Version: 0.5.0-dev-acdae70

**Comment by asterite** [comment]
https://github.com/trenpixster/addict/issues/103

**Comment by mverzilli** [comment]
Thanks, anyway we'll probably move to Coherence.

**Comment by asterite** [comment]
Yeah, I think we should, I reported that issue on Aug 12, 2016 :-)

**Comment by mverzilli** [comment]
LOL, hadn't noticed the date

**Comment by mverzilli** [comment]
This depends on #522

**Comment by mverzilli** [comment]
Fixed through https://github.com/instedd/ask/issues/597

**Comment by mmuller** [comment]
Working properly in version b706119
