### ISSUE TITLE
Review wording for Channels screen

### ISSUE THREAD

**Issue by mverzilli** [instedd/ask#543]
At least as of the current version, Channels aren't actually created, they're synchronized from external services (Nuntium and Verboice). 

When you click on "Create a channel", a pop up appears that let's you connect to or disconnect from external services. So:

1. You don't really create a channel, you just connect to a service to pull existing channels from there.

2. You don't just get new channels, you can also remove channels from the list by disconnecting from an external service.

Each time I use this screen I find these details a bit cognitively dissonant.

Version: 0.5.0-dev-acdae70 (build 1381)

**Comment by waj** [comment]
The channels page is currently being redesigned
