### ISSUE TITLE
[Collaborators] Email field is not being validated

### ISSUE THREAD

**Issue by juanboca** [instedd/ask#547]
The user can input anything, and an email will try to be sent to the wrong email address.

![screen shot 2017-01-13 at 3 26 32 pm](https://cloud.githubusercontent.com/assets/488553/21940796/b0616176-d9a4-11e6-9bef-ec2432ec65e8.png)

![screen shot 2017-01-13 at 3 25 26 pm](https://cloud.githubusercontent.com/assets/488553/21940773/98aade90-d9a4-11e6-8ea2-bb02431d6885.png)

**Comment by mmuller** [comment]
Working properly in version b706119
