### ISSUE TITLE
[Collaborators] If the project is untitled, no name is displayed on the invite confirmation

### ISSUE THREAD

**Issue by juanboca** [instedd/ask#548]
It should say "Untitled project" instead of appearing blank

![screen shot 2017-01-13 at 5 52 54 pm](https://cloud.githubusercontent.com/assets/488553/21945289/3642c0f0-d9b9-11e6-9e38-5ebe53816954.png)

**Comment by mverzilli** [comment]
Good catch. And it should say "has invited you".

**Comment by steesdale** [comment]
Could we mimick google docs and require a user to have a name before sharing?

- Scott

**Comment by pmallol** [comment]
Ok in Version: 0.6.0-dev-9b892e8 (build 1526)
