### ISSUE TITLE
[Sign-In] email label overlaps with text box

### ISSUE THREAD

**Issue by steesdale** [instedd/ask#550]
What happens now: 
- Currently if you go to sign in 
- You start writing your email address
- The text box overlaps with the string of text "email" 
- When you hit tab - the "email" string moves - and now looks correct. 

![screen shot 2017-01-13 at 4 14 01 pm](https://cloud.githubusercontent.com/assets/3987608/21947537/5a1758f0-d9ab-11e6-8afb-d5a043ee902a.png)

- seen in production 
- Version: 0.4.5 (build 1397)

**Comment by mmuller** [comment]
This issue is no longer reproducible in version 0.5.0-dev-38873bb (build 1384)
