### ISSUE TITLE
[Projects] Update Project Label to Fix Grammar

### ISSUE THREAD

**Issue by steesdale** [instedd/ask#551]
Currently: When you start a brand new project there are no projects; You do see some nice Gx and some text.  The grammar is a bit off ... 

Suggest updating to something like: 
![screen shot 2017-01-13 at 4 33 53 pm](https://cloud.githubusercontent.com/assets/3987608/21948117/a1c72cae-d9ae-11e6-8e14-96486cf1ba19.png)

**Comment by pmallol** [comment]
Ok in Version: 0.6.0-dev-9b892e8 (build 1526)
