### ISSUE TITLE
SMS prompts spanning multiple SMS messages (Frontend)

### ISSUE THREAD

**Issue by mverzilli** [instedd/ask#553]
As a questionnaire designer, I want to be able to enter questions longer than 140 chars. That means there will be questions I can't fit in a single SMSs, so I want to be able to specify how to split my question prompt in multiple SMSs.

# Graphics design 
You can find the related mockups here: https://projects.invisionapp.com/d/main#/console/8374235/193624221/preview
https://projects.invisionapp.com/d/main#/console/8374235/194469528/preview

# Interaction design
Notice that you introduce a new message by hitting SHIFT+ENTER while writing the prompt. 

When you click the X to remove a step, join that step's text to the previous one (instead of erasing the text).

# Data representation
Don't introduce any changes to the way SMS prompts are represented in a step. The only difference is that now we'll interpret the line break char (`\n`). For example:

1. Let's say there's a single message SMS prompt that says: "Peter Piper picked a peck of pickled peppers; A peck of pickled peppers Peter Piper picked; If Peter Piper picked a peck of pickled peppers, Where's the peck of pickled peppers Peter Piper picked?"
1. The user then introduces a new step (by pressing SHIFT+ENTER). That leaves the SMS prompt as:
"Peter Piper picked a peck of pickled peppers; \n A peck of pickled peppers Peter Piper picked; If Peter Piper picked a peck of pickled peppers, Where's the peck of pickled peppers Peter Piper picked?"

# Validations
Each chunk has to be shorter than 140 chars. There must be at least one step and it must not be blank. Only the last step can be blank, provided it's not the only one (the widget should actually make it impossible to introduce blank steps in the middle, so it is not necessary to validate this).

# Translations
Given we're not going to split the prompt in lines, instead keeping all content in a single line, translations should work just as they are. Notice that it makes sense for translators to introduce line breaks at different places based on their language.

**Comment by steesdale** [comment]
Follow-up Point from Moroc:
- The multiple sms feature may require a different number of message.
 e.g., a message in english vs. arabic of the same content would have
different lengths given arabic script limitations.

- Scott

**Comment by mmuller** [comment]
Working properly in version b706119
