### ISSUE TITLE
SMS prompts spanning multiple SMS messages (Runtime)

### ISSUE THREAD

**Issue by mverzilli** [instedd/ask#554]
When an SMS prompt contains line breaks (`\n`), interpret them as message separators and send each line as an SMS. If the prompt contains a trailing `\n`, don't send an empty message, just ignore it.

**Comment by edjez** [comment]
This is potentially dangerous as new lines in SMS are used for visual
separation too!
Also please test with copy and paste from different tools and the resulting
occasional /r/n

**Comment by edjez** [comment]
Suggest "the last /n before the required message cutoff" also remember
cutoff length is a function of content in each message as they get
constructed.

**Comment by mverzilli** [comment]
Thanks, Ed! We'll review the design then. As it is right now, ENTER confirms the message content, and SHIFT+ENTER would introduce new steps (`\n`). So there's no way to introduce line breaks from the UI without pasting the content. If we want to allow for multiple lines in a single SMS, that should change. 

Anyway the bulk of this issue is to make the runtime aware of purposeful multi-SMS messages, we can later change which char or char sequence we use as a separator.

**Comment by edjez** [comment]
Thanks @mverzilli agree whatever separator char is a good idea in the meantime and agree /n may not be the best one - 2 backslashes \\ seem a good alternative too that doesnt have large impact on other things eg character counting.

**Comment by mmuller** [comment]
Working properly in version b706119
