### ISSUE TITLE
[Respondent groups] Move "Select mode and channels" to the second step of wizard

### ISSUE THREAD

**Issue by mverzilli** [instedd/ask#555]
See: https://projects.invisionapp.com/d/main#/console/8374235/183286761/preview

This is in preparation to support respondent groups. Once we've got respondent groups, we'll assign them to different channels, and the menu of available channels depends on the selected modes, so the mode selection step needs to happen before the respondents lists step.

**Comment by pmallol** [comment]
Ok in Version: 0.6.0-dev-9b892e8 (build 1526)
