### ISSUE TITLE
[Respondent groups] Introduce "Respondent Group" entity

### ISSUE THREAD

**Issue by mverzilli** [instedd/ask#556]
- [x] Introduce a `Respondent Group` table which belongs to a `Survey` and has many `Respondents`. 
- [x] Write a migration that assigns a respondent group to each existing respondent. 
- [x] When the user creates a respondent list, ensure that it gets assigned to a new respondent group.

**Comment by pmallol** [comment]
Ok in Version: 0.6.0-dev-9b892e8 (build 1526)
