### ISSUE TITLE
[Collaborators] If the invite code does not exist, the server throws an internal error

### ISSUE THREAD

**Issue by juanboca** [instedd/ask#559]
Besides checking that the invite exists before asking its `project_id` as in the line 35 of the `invite_controller`, we should decide how to communicate this to the user

**Comment by mverzilli** [comment]
Line 35 in which file? :O). Also, in general it is a good idea to link to specific lines in specific commits, because source code changes fast.

**Comment by juanboca** [comment]
Sorry, it was supposed to be a mental note to write it properly after, and ended up being the whole description.
This is the line:
https://github.com/instedd/ask/blob/a338baf5e8aab57e2b1383555f6aafdad8f91adb/web/controllers/invite_controller.ex#L35

**Comment by mmuller** [comment]
Working properly in version b706119
