### ISSUE TITLE
In IVR mode the "Quota completed message" and "Error message" cannot be translated.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#566]
Found in version: 0.5.0-dev-38873bb (build 1384)

Reproduce steps:
Create a Questionnaire with IVR mode
Add a message to `Quota completed message`
Add a message to `Error message`
Add the Spanish language
Download the contents as CSV
Open the downloaded file and complete the rows with the texts in Spanish
Upload contents as CSV
Change main language to Spanish

Obtained:
The `Quota completed message` and `Error message` were not translated.

Screenshot:
<img width="1378" alt="screen shot 2017-01-16 at 5 34 47 pm" src="https://cloud.githubusercontent.com/assets/518152/21998130/cb0b452c-dc11-11e6-99d5-df1403a35751.png">

**Comment by asterite** [comment]
I was able to reproduce this :-)

**Comment by pmallol** [comment]
Ok in Version: 0.6.0-dev-9b892e8 (build 1526)
