### ISSUE TITLE
Explanation steps cannot be removed.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#571]
Found in version:
0.5.0-dev-38873bb (build 1384)

Reproduce steps:
Create a Questionnaire.
Add an `Explanation` step.
Within the `Explanation` step press the `Delete` button.

Obtained:
An unexpected error is thrown.
The following exception is logged on the browser's console: `TypeError: i is not a function`
The `Explanation` step cannot be removed.

Additional information:
https://sentry.io/instedd/ask-stg/issues/206860915/

**Comment by pmallol** [comment]
Ok in Version: 0.6.0-dev-9b892e8 (build 1526)
