### ISSUE TITLE
Improvements on export of results of a survey

### ISSUE THREAD

**Issue by edjez** [instedd/ask#572]
- Must always have ALL columns for all possible fields even if empty for all respondents
- Move timestamp to second column
- Columns for a same version of the questionnaire must come in same order - suggest: order by the sequence in which they were created in the designer, i.e. timestamp. 
- include a column for the mode in which the answers were collected

**Comment by nditada** [comment]
The mode can change during a survey, let's just list the two if there was a fallback. The detail of when that fallback happened is on the step by step export.

**Comment by mmuller** [comment]
Working properly in version 55aca59
