### ISSUE TITLE
Add Roboto-medium fonts to served assets or hunt down all references to them and remove them

### ISSUE THREAD

**Issue by mverzilli** [instedd/ask#573]
A big share of the loading time of Ask's landing page is spent by the browser trying to load Roboto-medium fonts, the server looking for them, not finding them and redirecting to login. The redirect part is solved through https://github.com/instedd/ask/commit/1b2e7ada4b8866eb3959bbfd58adb72a74dd6d18, but now the console shows 3 errors due to 404 not found responses.

We should either make them available (easy) or remove all references to it (more tricky, because there might be deps like Materialize that use them even though its absence doesn't seem to visually break anything).

See the current impact of this in the loading times in ask-stg:

<img width="1419" alt="screen shot 2017-01-20 at 11 57 56 am" src="https://cloud.githubusercontent.com/assets/651693/22153908/01891c34-df08-11e6-9bdb-2cc281a46ee1.png">

**Comment by waj** [comment]
Seems like I introduced this issue with b199ba803058befb72a3dad59a67df67499de31c, where I replaced the link to fonts from Google to built in fonts.

Let's remove the reference from the `_fonts.css` file. Leave only references to weights 300, 400 and 700 (light, regular and bold).
