### ISSUE TITLE
[Quiz] Improve validations for empty prompt messages.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#574]
Version 0.5.0-dev-38873bb (build 1384).

Reproduce steps:
Create a Questionnaire.
Enable the modes SMS and Phone Call.
Add a Step.

Obtained:
The following validation messages are displayed:
`SMS prompt must not be blank`
`Voice prompt must not be blank`

Expected:
The validation messages must be displayed after trying to save the step.

<img width="987" alt="screen shot 2017-01-20 at 12 53 06 pm" src="https://cloud.githubusercontent.com/assets/518152/22155768/6988be00-df0f-11e6-831a-f969e6efc5b9.png">

**Comment by asterite** [comment]
There's no way to manually save the step, it's saved automatically. So there's no way to display things after trying to save the step.

**Comment by nekron** [comment]
Same as #826
