### ISSUE TITLE
[Quiz] Implement refusal for numeric steps

### ISSUE THREAD

**Issue by waj** [instedd/ask#587]
"*" is the option to refuse a question. It can be used in IVR and SMS for multiple choice. The user can assign the skip logic for a refusal. If the designer wants to make the question mandatory, * should not be an option or it can be assigned a skip logic of "End Survey". For optional questions, it would simply fall to the next question.

For numeric options, there should be a checkbox that reads "Accepts refusals" and that allows the designer to enter the refusal text for SMS and an IVR key (1-9 or *) for IVR. We should NOT add * as another row because that would not allow custom text for SMS or other options for future modes.

https://projects.invisionapp.com/d/main#/console/8374235/211482979/preview

**Comment by asterite** [comment]
@waj How should this be stored in the JSON?

**Comment by waj** [comment]
Let's use this format (inside `numeric` steps):

```json
"refusal": {
  "responses": {
    "sms": {
      "en": ["skip"]
    },
    "ivr": ["*", "#"]
  },
  "skip_logic": "..."
}
```

**Comment by mmuller** [comment]
When I set a numeric value (like `1`) as refusal and I response with the value (`1`) to refuse the question, the Survey is marked as `Failed` and `1` is stored as value of the response. Here the Survey should be marked as `Completed` and `1` should not be stored as value of the response.

When I set `*` as refusal and I response with the value `*` to refuse the question, the Survey is marked as `Completed` but `*` is stored as value of the response. Here `*` should not be stored as value of the response.

Tested in version b706119

**Comment by nditada** [comment]
@mmuller Was there a specific problem we know of or expected with storing the "*" or a "REFUSED"? RTI would like an explicit value in the results field so that people can clearly see that the question was asked but refused.

**Comment by nditada** [comment]
The initial spec here had "REFUSED" as the value to store: https://instedd.storiesonboard.com/m/ncd-surveys/!card/LMIjWa_9JJiB5TnaExJc3Q

**Comment by mmuller** [comment]
@nditada the problem was with showing the value entered by the user as value of the variable on the Responses tab (e.g. `Age->1`; `Age->*`). I think that it would be helpful to display `REFUSED`  on the Responses tab.

**Comment by nditada** [comment]
ok, opened https://github.com/instedd/ask/issues/1077
