### ISSUE TITLE
Download disposition history

### ISSUE THREAD

**Issue by waj** [instedd/ask#589]
Allow to download the history of disposition changes in a CSV file like this:

```
Respondent hash, Disposition, Timestamp
17772535842, Partial, 2016-11-15 15:56:39 UTC
17772529358, Completed, 2016-11-15 15:57:39 UTC
```

**Comment by asterite** [comment]
@waj For this it would be convenient to have a `survey_id` field in the `respondent_disposition_history` table, to avoid a join and simplify logic. For now I'll go with the join but let me know if you think adding that field would be better.

**Comment by asterite** [comment]
Since there's no design attached to this issue, for now I put the download button as shown here:

![screenshot 2017-02-06 14 24 22](https://cloud.githubusercontent.com/assets/209371/22658415/bc4ced70-ec78-11e6-8643-9e5a8af544af.png)

The tooltip reads "Download disposition history CSV"
