### ISSUE TITLE
False positive in validation of duplicate responses in questionnaire editor

### ISSUE THREAD

**Issue by mverzilli** [instedd/ask#591]
Found in ask-demo.instedd.org, version 0.5.0

Repro:

1. Create a questionnaire with a multiple choice question and enable SMS and IVR modes.
2. Add two choices with the same value in "SMS" column. 
3. Fill the rest of the question properly: enter prompts for both modes, different non-blank values for the response column in each choice, and different digits for the IVR column in each choice.
4. At this point, the question should only be invalid because you used the same SMS value for 2 different choices. Confirm this by closing the question and checking that it looks orange. 
5. Switch off the SMS mode.

Expected: 
Since the only validation error was due to an SMS mode value, the question should become valid when only IVR mode is enabled.

Actual:
The question remains orange. When you open it, there's no visual indication that there were problems (because there aren't). If you switch on the SMS mode, you get to see the problem.

-----------

To fix:
1. Please write a regression test.
2. Modify this: `https://github.com/instedd/ask/blob/release/0.5/web/static/js/reducers/questionnaire.js#L842`

That call should be enclosed by an 
```
if (context.sms) {
...
}
```

**Comment by mmuller** [comment]
Working properly in version b706119
