### ISSUE TITLE
Minor details in Respondents table. 

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#593]
Found in version: 82e4a29

Preconditions:
There is a Survey `Foo`.
`Foo is completed`.
`Foo` sent the Questionnaire `Bar`.
`Bar` has a Step `S`.
`S` has a variable where its name is short (`Smoke` in this test).
`S` has response options where the text is longer than the variable name (`1-ALWAYS` in this test).

Reproduce steps:
Go to the Survey `Foo`.
Navigate to the tab `Respondents`.
Observe the column of the variable `Smoke`.

Screenshot:
<img width="708" alt="bad_line_break" src="https://cloud.githubusercontent.com/assets/518152/22311451/44a8f646-e332-11e6-84ec-f250db581e40.png">

**Comment by nditada** [comment]
Can we do this 2 things?
1. Increase the width of the column automatically to fit larger responses
2. Put a reasonable (15 chars ?) limit to that and add ellipsis to responses when those exceed the limit.

**Comment by mmuller** [comment]
Working properly in version 55aca59
