### ISSUE TITLE
Show respondent numbers instead of respondent hashes when uploading respondent lists

### ISSUE THREAD

**Issue by mverzilli** [instedd/ask#606]
<img width="620" alt="screen shot 2017-02-03 at 10 56 23 am" src="https://cloud.githubusercontent.com/assets/651693/22593918/96cce7a6-e9ff-11e6-9616-3d11d397f74a.png">

Otherwise it is very difficult for the user to evaluate whether the upload worked as intended.

**Comment by waj** [comment]
The phone numbers must be masked

**Comment by mmuller** [comment]
Ok in version ee7b498
