### ISSUE TITLE
Server error when inviting a new collaborator

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#607]
Found in Version: 0.5.1 (build 1466) ask-demo.instedd.org

Preconditions:
There is a project

1. Open Project and click on tab Collaborators
2. Click the + button to invite a collaborator
3. Fill the Email input and select a Role 
4. Click the Send button

Obtained:
An error notice pops out, a 500 server error appears in the console and the invitation is no sent.

**Comment by waj** [comment]
Fixed now. SMTP configuration was missing on the server.

**Comment by mmuller** [comment]
Ok in version ee7b498
