### ISSUE TITLE
Unused `step` variable in `flow.ex`

### ISSUE THREAD

**Issue by asterite** [instedd/ask#610]
The `step` argument is not used [here](https://github.com/instedd/ask/blob/master/lib/ask/runtime/flow.ex#L180-L185) because it's immediately overwritten in the next line. The compiler is currently giving a warning. @nekron Could you take a look at this? I'm tempted to remove that argument, or remove the first line, but I'm not sure which one is correct (seems to be a copy-paste from the function above)

**Comment by nekron** [comment]
Fixed with fe8d336fd9ac2c5871977391c5c55d928818a0c1
