### ISSUE TITLE
[Questionnaires] Invalid skip logic is only shown when the step is expanded

### ISSUE THREAD

**Issue by juanboca** [instedd/ask#615]
When moving a step to a position that invalidates the skip logic defined on it (or in other that pointed to the moved step), the only way to see that there is an error is expanding the step.
This can lead to incorrect questionnaires being launched without the user knowledge.

<img width="755" alt="screen shot 2017-02-08 at 2 40 33 pm" src="https://cloud.githubusercontent.com/assets/488553/22749648/d3c36f2a-ee0c-11e6-96ff-2ba1d807c5fe.png">
<img width="746" alt="screen shot 2017-02-08 at 2 39 59 pm" src="https://cloud.githubusercontent.com/assets/488553/22749647/d3c1541a-ee0c-11e6-9bf5-5d24ee5617c9.png">

**Comment by nekron** [comment]
Also if the step is untitled, the skip logic does not display the ~Untitled question~ label

**Comment by nekron** [comment]
Moved to a separate issue: #617

**Comment by mmuller** [comment]
Working fine in version ee7b498.
