### ISSUE TITLE
[Questionnaires] The variable name can be repeated on different steps without firing an error

### ISSUE THREAD

**Issue by juanboca** [instedd/ask#616]
The user can define the same variable name on all the steps and no error is shown.
This will cause some issues when the responses are listed

<img width="755" alt="screen shot 2017-02-08 at 2 47 21 pm" src="https://cloud.githubusercontent.com/assets/488553/22749857/89ac0ac2-ee0d-11e6-9894-b36d72cccd6d.png">
<img width="766" alt="screen shot 2017-02-08 at 2 47 16 pm" src="https://cloud.githubusercontent.com/assets/488553/22749858/89ae157e-ee0d-11e6-9386-bf3b10d8ae5e.png">

**Comment by waj** [comment]
It's ok to have different steps storing in the same variable (maybe there are two different paths in the questionnaire) but we should make sure the response is stored only once.

Right now this can lead to duplicate entries in the db. The last value is displayed in the respondents page, but the CSV will have the corresponding column empty.

**Comment by waj** [comment]
On second thought, allowing to change the value of a variable could make the respondent to "fall" in a different bucket. Also, setting the quotas is based on the type of steps that stores on each variable. I think it's desirable then to forbid dupliate vars in the same questionnaire.

**Comment by asterite** [comment]
I'll add a validation that disallows a same variable name across steps, even across quota completed steps.

**Comment by mmuller** [comment]
Working properly in version cc5d3df
