### ISSUE TITLE
[Questionnaires] Invalid skip logic is not being displayed for untitled questions

### ISSUE THREAD

**Issue by nekron** [instedd/ask#617]
The skip logic does not display the ~Untitled question~ label.

Steps to reproduce:
- Select an untitled question as skip logic
<img width="821" alt="screen shot 2017-02-08 at 4 28 14 pm" src="https://cloud.githubusercontent.com/assets/957103/22753725/e731cdf4-ee1b-11e6-9323-7693a5d02e55.png">
- Move it before the skip logic step, so the jump is backwards and therefore invalid:
<img width="842" alt="screen shot 2017-02-08 at 4 28 23 pm" src="https://cloud.githubusercontent.com/assets/957103/22753714/e04946a2-ee1b-11e6-86ca-290077080e68.png">

Expected result:

It should display ~Untitled question~ the same way it does for labeled questions:
<img width="864" alt="screen shot 2017-02-08 at 4 28 56 pm" src="https://cloud.githubusercontent.com/assets/957103/22753732/eead05e4-ee1b-11e6-8638-cb80716d617b.png">

**Comment by mmuller** [comment]
Ok in version ee7b498
