### ISSUE TITLE
[Quiz] Responses column values has disappeared

### ISSUE THREAD

**Issue by waj** [instedd/ask#620]
<img width="976" alt="screen shot 2017-02-09 at 3 28 38 pm" src="https://cloud.githubusercontent.com/assets/22697/22797318/8ed611c6-eedc-11e6-9012-9cd9b439358c.png">

**Comment by asterite** [comment]
The column disappears when you put a value inside it

**Comment by mmuller** [comment]
Working fine in version ee7b498.
