### ISSUE TITLE
[Quiz] Error when changing a disposition step to any other step type

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#622]
Version: 0.6.0-dev-d445c84 (build 1566)

1. Create a questionnaire
2. Add a Flag step
3. Change the Flag step to any other type of step

Obtained:
An error message pops up and anotherone appears in the console
`ErrorEvent {isTrusted: true, message: "Uncaught TypeError: Cannot read property 'en' of undefined", filename: "http://ask-stg.instedd.org/js/app-6b47e08076786f5272fca8a6f7576c17.js?vsn=d", lineno: 85, colno: 5506…}`

**Comment by mmuller** [comment]
Working fine in version ee7b498.
