### ISSUE TITLE
[channels] Arrow right in channel creation popup should lead to verboice and nuntium

### ISSUE THREAD

**Issue by nekron** [instedd/ask#623]
(Or be deleted)

<img width="791" alt="screen shot 2017-02-09 at 3 43 42 pm" src="https://cloud.githubusercontent.com/assets/957103/22797877/b54eecae-eede-11e6-83dd-b59020fd7176.png">

**Comment by mmuller** [comment]
Arrows are linked properly in version ee7b498.
