### ISSUE TITLE
Explanation step has a 'Question prompt' subtitle but it should say 'Message'

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#625]
Version: 0.6.0-dev-d445c84 (build 1566)

1. Create a Quiz
2. Add an Explanation step

Obtained:
The subtitle displays 'Question prompt'
![screen shot 2017-02-09 at 3 42 24 pm](https://cloud.githubusercontent.com/assets/9214460/22797927/df50dd0a-eede-11e6-9a95-9c42bdf0573b.png)

Expected:
The subtitle should be 'Message'
https://projects.invisionapp.com/d/main#/console/8374235/193624442/preview

**Comment by mmuller** [comment]
Ok in version ee7b498
