### ISSUE TITLE
[Survey] Uploading an empty respondents CSV should give an error

### ISSUE THREAD

**Issue by asterite** [instedd/ask#626]
Right now it's allowed but doesn't make much sense:

<img width="656" alt="screenshot 2017-02-09 15 52 46" src="https://cloud.githubusercontent.com/assets/209371/22798241/f9092026-eedf-11e6-8366-003d132a4ed4.png">

**Comment by nekron** [comment]
At least we shouldn't mark the survey as ready if there are no respondents.

**Comment by nditada** [comment]
Let's leave the step as incomplete and display a message with "the file you uploaded does not contain any phone number"

**Comment by mmuller** [comment]
Working properly in version 322bad2
