### ISSUE TITLE
[Collaborators] You shouldn't be able to invite yourself

### ISSUE THREAD

**Issue by asterite** [instedd/ask#631]
In the collaborators modal, you can now enter your email and select a role, and it works. The number of collaborators is incremented, though only one is listed. This should be disallowed altogether.

<img width="1148" alt="screenshot 2017-02-09 16 10 31" src="https://cloud.githubusercontent.com/assets/209371/22798902/910000f0-eee2-11e6-924d-e9110f0e066f.png">

**Comment by mmuller** [comment]
Working fine in version ee7b498.
