### ISSUE TITLE
[Quiz] Questions can't be opened after importing a questionnaire

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#634]
Version: 0.6.0-dev-d445c84 (build 1566)

1. Create a Questionnaire
2. Import the following file:
[236.zip](https://github.com/instedd/ask/files/764755/236.zip)
3. Try opening a question

Obtained:
An error message pops up

![screen shot 2017-02-09 at 4 23 02 pm](https://cloud.githubusercontent.com/assets/9214460/22799390/625e24d2-eee4-11e6-87be-84a7571fd415.png)

**Comment by mmuller** [comment]
Working fine in version ee7b498.
