### ISSUE TITLE
[Collaborators] A GET request is made when collaborator_mail input looses focus

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#637]
Version: 0.6.0-dev-d445c84 (build 1566)

1. Open a project
2. Navigate to the Collaborators tab
3. Click the + button to invite a collaborator
4. Start typing an email in the 'Enter collaborator's email' input field and click outside to loose focus

Obtained:
A 404 error message appears in the console

![screen shot 2017-02-09 at 4 36 44 pm](https://cloud.githubusercontent.com/assets/9214460/22799836/f8efa438-eee5-11e6-9fc7-1e7e4cc8b42b.png)

**Comment by mmuller** [comment]
Working fine in version ee7b498.
