### ISSUE TITLE
[Collaborators] Add collaborator modal card breaks when resizing window

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#638]
Version: 0.6.0-dev-d445c84 (build 1566)

![screen shot 2017-02-09 at 4 30 03 pm](https://cloud.githubusercontent.com/assets/9214460/22799910/5ae4eea0-eee6-11e6-94d4-13ca2cf7b4d7.png)

**Comment by mmuller** [comment]
Working properly in version b706119
