### ISSUE TITLE
IVR survey will retry calling after 10 minute timeout is completed

### ISSUE THREAD

**Issue by nekron** [instedd/ask#641]
Steps to reproduce:
- Create a survey with only one respondent and a quiz with one prompt
- Add several 1m retries, like: 1m 1m 1m 1m 1m 1m 1m
- Start it, answer the phone, but don't answer the question, so it timeouts
- The survey will call you back after 10 minutes

Expected:
- Answering the phone in the first place should clear the retries. Any timeouted respondent should not be contacted again.

**Comment by waj** [comment]
That would be true if #564 but it was left out of scope of this release. I'll close this issue for now.
