### ISSUE TITLE
Skip logic dropdown for the last step must display "next step" option

### ISSUE THREAD

**Issue by waj** [instedd/ask#642]
The current behavior is misleading. When a new step is added the skip logic option shows "End Survey", but if another step is added the skip logic will change to "Next Step". However, if the dropdown clicked and the "End Survey" item is selected, now when adding another step the skip logic will stay as "End Survey". In other words, there is a change in the behavior of the questionnaire without any visible UI changes.

To solve this, let's show both "Next Step" and "End Survey" options in the last step. This allows the user to choose the right option even when the following steps were not created yet.

**Comment by mmuller** [comment]
Ok in version 0ecc5c6
