### ISSUE TITLE
[Quiz] Apply style to questionnaire onboarding

### ISSUE THREAD

**Issue by lmatayoshi** [instedd/ask#643]
Steps to reproduce:

1) create a new user and log in
2) create your first project
3) create your first questionnaire

At this moment, onboarding looks like this:

<img width="1435" alt="questionnaire_onboarding" src="https://cloud.githubusercontent.com/assets/8591752/22828896/77edc29a-ef7e-11e6-8705-9ec0733a24e3.png">

Style should be applied in order to look like the original mockup:
https://projects.invisionapp.com/share/3U8BARPXJ#/screens/196343921

**Comment by lmatayoshi** [comment]
Also, the "HASH" material icon is missing in the third step of the caroussel:

<img width="529" alt="hash-material-icon" src="https://cloud.githubusercontent.com/assets/8591752/22829006/064ba566-ef7f-11e6-8b41-79d5f109e71f.png">

**Comment by mmuller** [comment]
Working fine in version ee7b498.
