### ISSUE TITLE
[Survey] When uploading an invalid file type, the system throws an error

### ISSUE THREAD

**Issue by juanboca** [instedd/ask#646]
The invalid file type message is shown, but a second after an internal error message is displayed, forcing the user to reload the page.

If the file type is invalid, nothing should be sent to the server.

![screen shot 2017-02-13 at 12 28 21 pm](https://cloud.githubusercontent.com/assets/488553/22889655/a2a949f2-f1e8-11e6-9653-6843d9c1003a.png)

**Comment by mmuller** [comment]
Working fine in version b706119
