### ISSUE TITLE
Sign in button doesn't work anymore

### ISSUE THREAD

**Issue by asterite** [instedd/ask#647]
Now that we can sign in by pressing Enter, we can't sign in by clicking the sign in button...

**Comment by waj** [comment]
I cannot reproduce this issue. I am able to login clicking the button both in staging and in my machine.

**Comment by waj** [comment]
Ok, it works when clicking on the "Sign In" label, but it doesn't when clicking in the blue zone.

**Comment by mmuller** [comment]
Ok in version 0ecc5c6
