### ISSUE TITLE
SMS Character counter

### ISSUE THREAD

**Issue by waj** [instedd/ask#649]
Implement a character counter that takes into account the GSM 03.38 encoding (https://en.wikipedia.org/wiki/GSM_03.38)

If the SMS message doesn't contain unicode characters, the limit will be 160. Otherwise 70 is the limit.

Useful links:
- https://www.npmjs.com/package/gsm
- https://www.smsgatewaycenter.com/sms_length_calculator.php

**Comment by mmuller** [comment]
Implemented properly in version b706119
