### ISSUE TITLE
Store Verboice call ids and use them to cancel queued calls when the survey is stopped

### ISSUE THREAD

**Issue by waj** [instedd/ask#653]
Store these call ids inside the respondent sessions (channel_state).

If the user stops the survey (#652) use these IDs to cancel queued and active calls in Verboice.

**Comment by asterite** [comment]
The call ids are now stored inside the Session's `channel_state` as a list (it can be nil if no calls were still enqueued).

The next step depends on #652: when the survey is stopped we must use these ids to stop the calls in Verboice.

**Comment by asterite** [comment]
Store the state as `%{verboice_call_id: call_id}`

**Comment by asterite** [comment]
We need to add an API endpoint in verboice to cancel a call

**Comment by asterite** [comment]
@waj To cancel the queued calls in the background we need to know what channel is assigned to each respondent. This is currently stored in the respondent's session. But when a survey is stopped the session is set to nil. Should we, before setting the session to nil, extract all this information to memory (a list), spawn a process and cancel calls? Or maybe we should store the channel in the respondent?
