### ISSUE TITLE
[Survey] Re-contact attempts shouldn't be validated for non-selected modes

### ISSUE THREAD

**Issue by asterite** [instedd/ask#655]
Steps to reproduce:

1. Create a Survey
1. Select the Phone Call mode in the "Select mode" section
1. Complete the "Setup a schedule" section (select a day or two)
1. Set an invalid value like "hello" in the "Phone re-contact attempts" in the "Setup a schedule" section
1. Select the SMS mode in the "Select mode" section

Actual: the "Setup a schedule" section appears as incomplete and there's no indication of what the error is
Expected: the "Setup a schedule" section should be marked as completed, because the old, hidden "Phone re-contact attempts" shouldn't be validated anymore

**Comment by mmuller** [comment]
Working properly in version b706119
