### ISSUE TITLE
[Questionnaire] Autofill for Response Options Includes Question Prompts

### ISSUE THREAD

**Issue by steesdale** [instedd/ask#661]
What Happened: 
- I was creating a new questionnaire
- I created several fields. 
- I then created a categorical field 
- I started entering the response options for SMS. 
- When I got to the SMS response option, I typed "1" and the autocorrect generated a list of every string that included the text "1" - including those strings from the Question prompts from previous questions. See below: 
![screen shot 2017-02-16 at 1 35 03 pm](https://cloud.githubusercontent.com/assets/3987608/23037798/53e72674-f44d-11e6-95e7-8a30ca77cd61.png)

What I expected: 
- That the pre-populated options for responses for SMS, would only include other response options from categorical fields. 

Why: 
It is messy to have the full strings from the questions pull in as options for responses.  Specifically, because the SMS response options are often re-stated in the question prompts.  I don't believe there is a scenario where I would want the SMS response input to match exactly an SMS message from my questionnaire.  My suggestion would be to limit the recommended input strings to just past input strings.

**Comment by mmuller** [comment]
Related to #562

**Comment by spalladino** [comment]
Scope autocompletes by:
- Prompt (question or explanation)
- Response
- Quota-completed
- Error

Regenerate existing translations to scope them

**Comment by mmuller** [comment]
Working properly in version 02bcf64
