### ISSUE TITLE
Disposition history export file should include mode.

### ISSUE THREAD

**Issue by adam704a** [instedd/ask#662]
Or channel. Just an indication of the mode.

Current:
Respondent hash, Disposition, Timestamp

Proposed:
Respondent hash, Disposition, Mode, Timestamp

![screen shot 2017-02-16 at 3 01 09 pm](https://cloud.githubusercontent.com/assets/276936/23043203/cc1db8aa-f458-11e6-8c8f-79effb974472.png)

**Comment by adam704a** [comment]
Hey guys, I spoke to @nditada about this a few weeks ago to get this implemented as soon as possible. This one is important for doing analysis.

@steesdale

**Comment by spalladino** [comment]
@adam704a we'd be releasing this in Hazel in a few weeks. Does that work, or is it needed in surveda-zambia?

**Comment by mmuller** [comment]
Working properly in version 9c248ee
