### ISSUE TITLE
[Questionnaire]  Drag and Drop of step Inhibits Selecting Text Strings

### ISSUE THREAD

**Issue by steesdale** [instedd/ask#663]
What Happens: 
- I wanted to edit a few words in a question prompt
- I tried to select the words by clicking and dragging my mouse over the words, like you would in an email or other document.
- Instead of selecting the text, the UI  started to allow me to drag and move the entire step. 

What I expected: 
- That if I click and try to select a text string, I can select multiple words and copy/delete/etc. 
- That if I click off of the strings, I can drag and move the step.

**Comment by mmuller** [comment]
Reproduced in version ee7b498.

**Comment by asterite** [comment]
This is a side-effect of drag-and-drop, I don't think it can be "fixed". For example in GMail you can drag and drop emails in the list, but because of that you can't select their text (the subject). The mouse/trackpad gesture to drag is the same as to select text.

**Comment by steesdale** [comment]
It seems odd that we would not expect a user to click and select a string of text though.

Say I want to delete a 45 word question, I then have to hold down the delete button to remove it.
Or
I want to copy a string and paste it somewhere…

Also the pointer is acting like you are interacting with text when you hover over the string.  It is this one…


The desired behavior I believe is if the pointer is indicating you are working in a text box, there is no drag and drop.  When you leave the box for the text string; then the cursor changes to the hand; and you can drag and drop.


- Scott

**Comment by waj** [comment]
@asterite what you say makes sense for a collapsed step, but no for a prompt field for example. Let's see if we can disable dragging from certain areas. Otherwise we'll need to allow dragging from the title only.

**Comment by asterite** [comment]
@steesdale Regardless of the issue, which we'll try to fix, doing triple click on a text will select it all, so there's no need to drag to select a whole text section, and triple click is much faster and accurate. Same for delete: triple click then hit "delete".

**Comment by asterite** [comment]
I made a few changes to allow selecting texts in inputs inside steps more easy. There's still the issue that trying to select text that's not inside an input (like a title, or header) will start the drag, but I don't know if that's a real issue.

**Comment by mmuller** [comment]
Working properly in version cc5d3df
