### ISSUE TITLE
[Survey] Max Time Range Ends at 11pm 

### ISSUE THREAD

**Issue by steesdale** [instedd/ask#665]
Currently
- When setting the time range, the last hour available is 11pm 

Expected
- That I could set the time zone to end at 11:59

**Comment by mmuller** [comment]
Version ee7b498.

Screenshot:
<img width="780" alt="screen shot 2017-02-17 at 9 58 53 am" src="https://cloud.githubusercontent.com/assets/518152/23066124/b7621d3a-f4f7-11e6-902f-216ac071b4e4.png">

**Comment by asterite** [comment]
I think 12 AM is the next one, and that's at the beginning of the list (12 AM is the same as 12 PM but it will only show once in the list). However, there currently seems to be a bug in which you can't set the second option to 12 AM...

**Comment by steesdale** [comment]
agreed - for example you can never send out surveys at 11:30pm.  Low priority issues here - but something to consider.

- Scott

**Comment by mmuller** [comment]
This behavior was improved in #674
