### ISSUE TITLE
Make it clear to users how to use the multiple SMS messages with Shift + Enter

### ISSUE THREAD

**Issue by adam704a** [instedd/ask#668]
Not sure if this would be some on screen text, call out, etc....

![screen shot 2017-02-17 at 8 43 27 am](https://cloud.githubusercontent.com/assets/276936/23071934/3d14f9f8-f4ed-11e6-99c5-69de865d819c.png)

**Comment by steesdale** [comment]
+1

**Comment by asterite** [comment]
This was implemented some time ago. When the text is long an explanation appears just below:

![screenshot 2017-05-18 13 33 41](https://cloud.githubusercontent.com/assets/209371/26213233/a827a8b2-3bce-11e7-81d3-b675ac65fd0a.png)
