### ISSUE TITLE
Error after replying with value less than the min value.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#669]
Found in version: a1328a5

Reproduce steps:
1. Create a Questionnaire with a Numeric step.
2. Add an error message to the Questionnaire.
3. Set a min value ('18' in this test).
4. Execute a Survey using the Questionnaire created in the first step
5. Reply with a value less than the min value ('15' in this test).

Actual result:
An error is logged.
Verboice: `Fatal Internal Error: {case_clause,<<"error message">>}`

Additional information:
This issue may be related to #632

**Comment by waj** [comment]
Did the questionnaire have an error message filled for the mode you were using? We're still not validating that the questionnaire doesn't have any errors before launching the survey. So it's possible to launch the survey and have crashes like this one if there are missing prompts for example.

**Comment by mmuller** [comment]
No, the questionnaire didn't have an error message configured.

**Comment by mmuller** [comment]
@waj Another error is logged when the Questionnaire has an error message configured. I will edit this issue and reopen it.

**Comment by waj** [comment]
@mmuller please try again. There was an issue in Verboice (staging) that should be now fixed.

**Comment by mmuller** [comment]
Working properly in version b706119
