### ISSUE TITLE
[Questionnaire] Add mobile web mode to questionnaires

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#675]
- [x] Add a toggle to enable/disable mobile web mode to questionnaires (just like SMS and Voice)
- [x] Add a textarea for each step to include the text to be displayed in mobile web mode
- [x] Add another column in the responses table for mobile web
- [x] Serialize all the mobile web mode data in the questionnaire
- [ ] Add textarea for error messages and quota completed

**Comment by spalladino** [comment]
Done!

**Comment by mmuller** [comment]
Working properly in version 9c248ee
