### ISSUE TITLE
[Form] Create new web application for mobile web forms

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#681]
Setup a separate client webapp from the main one, with a different set of assets, that will be used for displaying the mobile web form to respondents. Consider sharing part of the CSS (such as colour variables) and common JS, but the bundles should be different to ensure faster loading times for this app. Ensure it is responsive, favouring rendering in mobile devices over desktop.

Serve this second app from a different endpoint in the phoenix app.

**Comment by asterite** [comment]
Implemented in #702
