### ISSUE TITLE
Character counter doesn't get updated when deleting all the content from the textbox

### ISSUE THREAD

**Issue by waj** [instedd/ask#686]
The issue is that the materialize's autocomplete is canceling the event when the textbox doesn't have any content.

**Comment by mmuller** [comment]
<img width="846" alt="screen shot 2017-02-21 at 11 11 41 am" src="https://cloud.githubusercontent.com/assets/518152/23168332/91715bfe-f826-11e6-91b4-2561a9f7454c.png">

**Comment by mmuller** [comment]
Working properly in version c8d6eab
