### ISSUE TITLE
Unable to upload Sample using Chrome on Windows

### ISSUE THREAD

**Issue by adam704a** [instedd/ask#691]
I am not having this problem with Chrome on OSX. This is working with IE on windows.

Steps to recreate:
1. Download the sample CSV file: phone_numbers_example.csv
2. Either  drop or browse to the same same file

Details:
Chrome: Version 56.0.2924.87 (64-bit)
Windows: Windows 8/10

![screen shot 2017-02-22 at 10 47 18 am](https://cloud.githubusercontent.com/assets/276936/23224628/5e511c66-f8ec-11e6-856f-de737e6a4321.png)

**Comment by mmuller** [comment]
Reproduced in version c8d6eab.

**Comment by steesdale** [comment]
@adam704a I believe our plan was to not specifically support IE at this time.  Can you confirm if that was your understanding as well?

**Comment by adam704a** [comment]
@steesdale yes, that is my understanding too.

**Comment by mmuller** [comment]
Working properly in version 9c248ee
