### ISSUE TITLE
[Questionnaire] Splitted SMS messages are not divided in autocomplete.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#694]
Found in version b706119

Reproduce steps:
1. Create a Questionnaire.
2. Enable the `SMS` mode.
3. Add a Multiple Choice step.
4. Fill the `SMS Message` with a text greater than 160 chars.
5. Split the text.
6. Add a choice.
7. Within the `SMS` column fill the field with the first char of the text added in (4)

Obtained:
The splitted `SMS message` is displayed using one line.

Expected:
The splitted `SMS message` should be displayed in two lines.

Screenshot:

<img width="1656" alt="splitted" src="https://cloud.githubusercontent.com/assets/518152/23262250/c897d372-f9b8-11e6-9b8a-6bfed7a124aa.png">

**Comment by spalladino** [comment]
Check why the </1> tag is not displayed in the dropdown. 

Also, add at least a whitespace as a separator between both messages, if not a newline.

**Comment by asterite** [comment]
Well, it seems the autocomplete component we are using suffers from JS injection...

**Comment by asterite** [comment]
Reported: https://github.com/icefox0801/materialize-autocomplete/issues/38

**Comment by asterite** [comment]
Not an issue of materialize-autocomplete...

**Comment by asterite** [comment]
It seems it's an issue of materialize-autocomplete after all :-P

**Comment by mmuller** [comment]
Working properly in version b706119
