### ISSUE TITLE
[Questionnaire] Autocomplete throws an unexpected error in "Quota completed message".

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#697]
Found in version b706119

Preconditions:
The autocomplete has a variable "Foo" already stored.

Reproduce steps:
1. Create a Questionnaire.
2. Expand the "Quota completed message".
3. Click on the "Voice message" field.
4. Type "Fo". The autocomplete show the variable "Foo".
5. Select the variable "Foo".

Obtained:
"Sorry, something went wrong" is displayed.
The following error is logged in the browser's console 
`PUT http://ask-stg.instedd.org/api/v1/projects/84/questionnaires/269 422 (Unprocessable Entity)
(anonymous) @ raven.js:1052
g @ api.js:43
b @ api.js:55
y @ api.js:51
w @ api.js:114
j @ api.js:122
e.updateQuestionnaire @ api.js:243
(anonymous) @ questionnaire.js:328
(anonymous) @ index.js:15
dispatch @ applyMiddleware.js:49
(anonymous) @ autosave.js:15
(anonymous) @ middleware.js:26
(anonymous) @ index.js:18
value @ QuestionnaireMsg.jsx:258
autocompleteOnSelect @ QuestionnaireMsg.jsx:398
onSelect @ IvrPrompt.jsx:147
onSelect @ Autocomplete.jsx:129
select @ jquery.materialize-autocomplete.js:446
setValue @ jquery.materialize-autocomplete.js:361
(anonymous) @ jquery.materialize-autocomplete.js:299
dispatch @ jquery.js:5205
m.handle @ jquery.js:5013
t @ raven.js:293
console.js:30 `

Screenshot:

<img width="1670" alt="screen shot 2017-02-23 at 3 53 26 pm" src="https://cloud.githubusercontent.com/assets/518152/23274153/68f4860e-f9e0-11e6-88b4-13af541f2f4c.png">

**Comment by asterite** [comment]
I can't reproduce this locally. Can someone else try to reproduce this?

**Comment by asterite** [comment]
Oh, actually I can

**Comment by mmuller** [comment]
Working properly in version c8d6eab
