### ISSUE TITLE
[Questionnaire] Steps are invalid when "End survey" is selected.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#698]
Found in version: b706119

Reproduce steps:
1. Create a Questionnaire.
2. Add a "Multiple choice" step.
3. Add two choices to the step.
4. Within a choice select "End survey" from "Skip logic".

Obtained:
The step remains orange.

Expected:
The step should be valid.

Screenshots:

<img width="953" alt="ends1" src="https://cloud.githubusercontent.com/assets/518152/23275495/792dcc42-f9e5-11e6-9fa6-5723702197c4.png">
<img width="853" alt="ends2" src="https://cloud.githubusercontent.com/assets/518152/23275494/792981aa-f9e5-11e6-92e7-e6f76ded6433.png">

**Comment by juanboca** [comment]
Also, when the user opens the step to see what error has, nothing is showed as an error. But the Questionnaire is marked with an orange dot as invalid

**Comment by mmuller** [comment]
Working properly in version 5c13734
