### ISSUE TITLE
[Questionnaire] Cannot delete content of SMS response

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#700]
On a multiple choice question, add a new response, enter any text in the SMS response field, and then try to delete it. On lost focus of the row, the text is re-added.

![aijpiqqwl4](https://cloud.githubusercontent.com/assets/429604/23313968/96b3b0f6-fa9e-11e6-8e04-bd68fb351c6e.gif)

**Comment by asterite** [comment]
Isn't this the same issue as another one (can't remember the number) where, because of the autocomplete component the onChange event isn't triggered?

**Comment by spalladino** [comment]
@asterite I think you mean the one that caused the character counter to fail to reach 0. @lmatayoshi had been working on that one if I recall.

**Comment by spalladino** [comment]
Yep: https://github.com/instedd/ask/issues/686

**Comment by pmallol** [comment]
Ok in Version: 0.7.0-dev-02bcf64 (build 1752)
