### ISSUE TITLE
Crash when uploading large respondents file

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#704]
On ask-demo server, version 0.6.1. When uploading a CSV file with 2 million respondents, the server crashes with OOM:

```
[app-1]2017-02-28T15:56:23.882242724Z 2017-02-28T15:56:23.882Z request_id=v3cs6c404pj4apj56bapmna3lp204uqa [info] POST /api/v1/projects/6/surveys/20/respondent_groups
[app-1]2017-02-28T15:57:05.515950834Z eheap_alloc: Cannot allocate 212907632 bytes of memory (of type "old_heap").
[app-1]2017-02-28T15:57:05.535628860Z 
[app-1]2017-02-28T15:57:07.617511948Z Crash dump is being written to: erl_crash.dump...done
```

**Comment by adam704a** [comment]
Here is the large file: https://www.dropbox.com/sh/cs2jl2f55daz0e9/AAB6UJwM1Rl8Xw8oeHi75Ilma?dl=0

**Comment by nekron** [comment]
Check that this is still happening

**Comment by asterite** [comment]
I couldn't reproduce this locally, but of course in staging/production sever the memory limits are different.

**Comment by waj** [comment]
Let's try to avoid creating all the respondent structures into memory all at once to minimize the required amount of memory.

**Comment by mmuller** [comment]
Working properly in version cc5d3df
For the record: when uploading more than 400k respondents the App. throws an error but the Respondents are uploaded successfully.
