### ISSUE TITLE
[Survey] Usability Feedback - No Next Button after cutoff rules

### ISSUE THREAD

**Issue by steesdale** [instedd/ask#715]
Currently: 
- When you fill out a survey there are these nice buttons to help you continue to scroll down, if you are not expecting the vertical format. 
- When you get to the end, and you finish doing your cut-off rules, users were expecting another "next" type button. 
- There is an arrow button hovering in the lower left, which is very useful. but to the first time user - its not clear that you need to go back to the top to start. 

Expected / Ideas for Enhancements
- Users expected a button to go "next" after finishing cutoff rules.  This is synonymous with "start" 
- Idea 1: Make the start button materialize in the progress bar on the left when at 100% ready.
- Idea 2: have some button more obvious to "get survey started" after cutoff / comparisons, that scrolls a user to the top. 

![screen shot 2017-03-01 at 11 21 24 pm](https://cloud.githubusercontent.com/assets/3987608/23494127/60dae242-fed6-11e6-9d18-530d5eda1786.png)

**Comment by juanboca** [comment]
Going for Idea 1, as is the proposed design on Invision: https://projects.invisionapp.com/d/main#/console/8374235/182593571/preview

**Comment by mmuller** [comment]
Working properly in version 02bcf64
