### ISSUE TITLE
[Respondent] Question - Retry timing seems imprecise

### ISSUE THREAD

**Issue by steesdale** [instedd/ask#716]
Question: Can you confirm if retries are rounded up to the nearest 10min?  

What happened: 
- I configured a survey for IVR with 2 retries.  I set the retry duration to 2m 10m. 
- I got a call within 30 seconds
- I started to participate, hung up after 2nd question. 
- Waited 10min, got a retry w/ 2nd voice call. 
- Answered a few more questions, hung up. 
- Waiting 10 min, got a retry w/ the 3rd call. 
- Answered a few more questions, hung up. 
- No more retries occurred as expected.

What I expected: 
- That the retry duration would follow closer to 2min and 10min; not 10min and 10min. 
- Or that we let a user know that a retry must be no smaller than 10min.

<img width="766" alt="screen shot 2017-03-01 at 11 56 51 pm" src="https://cloud.githubusercontent.com/assets/3987608/23494844/cbfed11a-feda-11e6-8474-04ddaecb4bfc.png">

**Comment by lmatayoshi** [comment]
It seems that each retry following a hang-out is being replaced by a 10 min retry. This issue can be reproduced consistenly in localhost and staging

**Comment by pmallol** [comment]
Ok in Version: 0.7.0-dev-fac231d (build 1781)
