### ISSUE TITLE
[Questionnaire] Paste Text for Quota Message Disapeared

### ISSUE THREAD

**Issue by steesdale** [instedd/ask#717]
What Happened: 
- I wanted to paste text into the voice/sms message script for quota complete. 
- I did a ctrl v, but my text disappeared after it showed up.
- I tried again, and it stayed.

![test](https://cloud.githubusercontent.com/assets/3987608/23537979/5a3b0c04-ff95-11e6-9b24-5c62bc45282f.gif)

**Comment by mmuller** [comment]
Working properly in version 9c248ee
