### ISSUE TITLE
Change survey CSV download control

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#718]
Currently there are 4 buttons with almost identical icons shown when the download action button is pressed.

Change this to open a modal that shows the different options along with a brief description, and allows the user to choose which CSV to download.

**Comment by juanboca** [comment]
Apply this design: https://projects.invisionapp.com/d/main#/console/8374235/222166048/preview

**Comment by mmuller** [comment]
Working properly in version 9c248ee
