### ISSUE TITLE
[Questionnaire] Double clicking on the explanation dots moves the explanation halfway

### ISSUE THREAD

**Issue by juanboca** [instedd/ask#724]
If the user double clicks on the dots below the explanation, the carrousel ends up showing a piece of each explanation, instead of moving it to fully show the desired one

Example 1:
![screen shot 2017-03-06 at 2 52 12 pm](https://cloud.githubusercontent.com/assets/488553/23622337/fb694368-027c-11e7-9304-1789e40d436e.png)

Example 2:
![screen shot 2017-03-06 at 2 47 20 pm](https://cloud.githubusercontent.com/assets/488553/23622338/fb8cd2ba-027c-11e7-8ec4-7ff1ad79e281.png)

**Comment by mmuller** [comment]
Working properly in version 322bad2
