### ISSUE TITLE
[Quiz] A disabled delete button appears in a accepts_refusals option in numerical step

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#725]
Found in version Version: 0.7.0-dev-02bcf64 (build 1752), also present on Version: 0.6.1 (build 1652)

1. Add a numerical step
2. Check the 'Accepts refusal' option
3. Click on Valid entries so that the focus is on either input field
4. Click on the delete trashcan icon 

Obtained:
The delete icon appears when the focus is on the input field but clicking on it [does nothing](http://g.recordit.co/RIKuQ1MNUg.gif)

**Comment by mmuller** [comment]
Working properly in version 5c13734
