### ISSUE TITLE
[Questionnaire] If the range delimiters are invalid, the change is not saved

### ISSUE THREAD

**Issue by juanboca** [instedd/ask#727]
On a numeric question, if the user enters an invalid range (the comma-separated numbers are not consecutive, or the range is smaller than the minimum or greater than the maximum), the new value is not saved. And the user gets no feedback, other than seeing the values lost. 
The field should marked as having an error, but allow the user to save it, or give a little more feedback.

**Comment by mmuller** [comment]
Working properly in version cc5d3df
