### ISSUE TITLE
[Questionnaire] If it has invalid ranges no error is shown

### ISSUE THREAD

**Issue by juanboca** [instedd/ask#728]
If the ranges are invalid (min value greater than the first element of the range, and/or max value smaller than the last element of the range), no error is shown, and the ranges shown are the last valid ones.

![screen shot 2017-03-06 at 3 30 37 pm](https://cloud.githubusercontent.com/assets/488553/23623796/1942ceb8-0282-11e7-858c-c7bf17402c8a.png)

**Comment by mmuller** [comment]
Working properly in version cc5d3df
