### ISSUE TITLE
[Survey] Flag steps are not working properly

### ISSUE THREAD

**Issue by juanboca** [instedd/ask#729]
If a flag step is created to mark the respondent as "ineligible" or "partial", when the respondent passes through this step it ends up being marked as "completed", but in the dispositions history it only appears marked as completed.

The questionnaire used is:
[298.zip](https://github.com/instedd/ask/files/822557/298.zip)

Dispositions history csv:
[respondents_disposition_history_2017-03-06-21-22-42.csv.zip](https://github.com/instedd/ask/files/822565/respondents_disposition_history_2017-03-06-21-22-42.csv.zip)

Screenshot of the Local Gateway showing that the response was the correct and the respondent should be marked as ineligible:
![screen shot 2017-03-06 at 6 23 09 pm](https://cloud.githubusercontent.com/assets/488553/23630512/28c967c6-029a-11e7-8647-fe3582c7a012.png)

Screenshot of the Local Gateway showing that the response was the correct and the respondent should be marked as partial:
![screen shot 2017-03-06 at 6 26 33 pm](https://cloud.githubusercontent.com/assets/488553/23630623/86e613ae-029a-11e7-9942-e19898d97d93.png)

**Comment by mmuller** [comment]
Working properly in version fac231d
