### ISSUE TITLE
[Quiz] Add hint for when questionnaires are being imported

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#733]
Version: 0.7.0-dev-02bcf64 (build 1752)

When importing a large zip file questionnaire, it may take some time for the process to finish and see changes on the screen, leading to think the file hasn't been imported.
I'd suggest adding a hint or notice for the user to understand the questionnaire is being imported.

**Comment by mmuller** [comment]
The same happens when importing a large CSV with respondents.

**Comment by mmuller** [comment]
Related to #594

**Comment by mmuller** [comment]
This functionality was added in #794
