### ISSUE TITLE
When there's an error resetting password the page reloads within the main div

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#737]
Version: 0.7.0-dev-02bcf64 (build 1752)

1. Click on Reset password when login in and add user email
2. Click on link 'Change my password' in the email
3. Type two different passwords in password inputs

Obtained:
![screen shot 2017-03-07 at 3 45 27 pm](https://cloud.githubusercontent.com/assets/9214460/23673591/9cac444e-0351-11e7-9c69-084bc6a8b3d8.png)

**Comment by mmuller** [comment]
Working properly in version cc5d3df
