### ISSUE TITLE
[Survey] Disable hand cursor for reader users

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#738]
Version: 0.7.0-dev-02bcf64 (build 1752)

As reader of Project 'Foo':
1. Acces a survey
2. Move the cursor over disabled checkboxes and radio buttons

Obtained:
The cursor changes from arrow to hand as if the element was active
![screen shot 2017-03-07 at 4 28 45 pm](https://cloud.githubusercontent.com/assets/9214460/23674823/ffc751be-0355-11e7-82a7-f49bfe44e13f.png)

**Comment by mmuller** [comment]
Working properly in version 8fcc4de
