### ISSUE TITLE
Cutoff is not working properly.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#740]
Found in version:
02bcf64

Preconditions:
There is a Questionnaire `Foo`.
'Foo' has enabled the SMS mode.

Reproduce steps:
Create a Survey.
Select the Questionnaire `Foo`.
Select `SMS` as Channel.
Upload 20 respondents.
Define a Cutoff rule equal to 1 respondent.
Start the Survey.
Answer the Survey using 1 respondent.

Obtained:
The Survey is sent to 10 respondents, and after that the Survey is sent to the `pending` respondents (10 in this test).

Expected:
`pending` respondents should not receive the Survey when the cutoff was covered.

**Comment by lmatayoshi** [comment]
It also happens when using IVR mode

**Comment by mmuller** [comment]
Working properly in version 5c13734
