### ISSUE TITLE
Surveys with long names break style of card because of trashcan icon

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#745]
Found in Version: 0.7.0-dev-fac231d (build 1781)

Similar to #108 

![screen shot 2017-03-10 at 2 44 20 pm](https://cloud.githubusercontent.com/assets/9214460/23806459/8bbdb842-05a0-11e7-8d18-a120f260d828.png)

**Comment by lmatayoshi** [comment]
Reference to this issue (#745) in commit e6d8ea6 is incorrect. It should reference to #750

**Comment by mmuller** [comment]
Working properly in version 9c248ee
