### ISSUE TITLE
[Quiz] IVR Mode appears active after importing a SMS only questionnaire

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#749]
Found in Version: 0.7.0-dev-e9019a7 (build 1792)

1. Create a new Questionnaire
2. Import a questionnaire designed for SMS mode only (e.g. [311.zip](https://github.com/instedd/ask/files/839722/311.zip) )
3. Observe questionnaire Modes

Obtained:
IVR Mode appears active but the steps show _only_ SMS inputs.
When deactivating the IVR Mode the steps now show IVR inputs

![screen shot 2017-03-13 at 6 55 47 pm](https://cloud.githubusercontent.com/assets/9214460/23876962/c2c31514-081e-11e7-860c-07d298fac941.png)
![screen shot 2017-03-13 at 6 55 59 pm](https://cloud.githubusercontent.com/assets/9214460/23876963/c2c36c58-081e-11e7-84a0-b5ddb35fc29c.png)

Expected:
After importing a Questionnaire with SMS inputs, the IVR mode appears inactive. When activated, IVR inputs appear inside the questionnaire steps.

**Comment by asterite** [comment]
This should be fixed in master, please verify :-)

**Comment by pmallol** [comment]
Ok in Version: 0.9.0-dev-dafd799 (build 2168)
