### ISSUE TITLE
Support 2 different colour schemes per project

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#750]
Add a configuration at project-level to use two different colour schemes: default and better data for health initiative.

In all pages within a project, use the selected colour scheme.

**Comment by spalladino** [comment]
To choose the colour scheme: on the project page, when hovering on the project name, show a [palette icon](https://material.io/icons/#ic_palette) next to it. When the user clicks on the icon, show a modal with the two colour options.

**Comment by spalladino** [comment]
Logo: [logo.svg.zip](https://github.com/instedd/ask/files/841882/logo.svg.zip)

**Comment by spalladino** [comment]
Fixed by @lmatayoshi @asterite @Mscebba in #771

**Comment by mmuller** [comment]
Working properly in version 85e0ca6
