### ISSUE TITLE
[Survey] Both primary/fallback mode show IVR when running a mode comparison survey

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#752]
Version: 0.7.0-dev-85e0ca6 (build 1804)

1. Create a survey, select a questionnaire
2. In select mode check the 'Run a comparison' option and also check 'Phone call w/SMS fallback' and 'SMS w/phone call fallback'
3. Finish configuring the survey and launch it
4. Go to survey Overview and observe the Modes displayed under the graph

Observed:
Both Primary and Fallback modes show IVR modes.
![screen shot 2017-03-14 at 3 42 42 pm](https://cloud.githubusercontent.com/assets/9214460/23917622/c334d36a-08ce-11e7-8729-12c2a6dfe8b5.png)

Expected:
Primary and Fallback modes display both IVR and SMS modes

**Comment by mmuller** [comment]
Working properly in version 6baaa96
