### ISSUE TITLE
[Quiz] Audio file upload is not being validated thus calls are failing

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#755]
Version: 0.7.0-dev-85e0ca6 (build 1804)

1. Create a questionnaire
2. Set mode to IVR only
3. In multiple choice step add any Voice message
4. Click on 'Text to speech' and change it to 'Upload a file' **and do not upload any file**
5. Complete steps 'Quota complete messages' and 'Error messages'
6. Test questionnaire via call with Callcentric

Obtained:
The call fails and the following error appears in Verboice:
`<Gather action="http://ask-stg.instedd.org/callbacks/verboice?respondent=1005928"> <Play>http://ask-stg.instedd.org/audio/d91bca13-b787-48c9-a76a-590e4cd11b40</Play> </Gather>
Unknown file type
`

Expected:
Voice messages with option 'Upload a file' without uploaded files should be set automatically to 'Text to speech'

**Comment by spalladino** [comment]
The questionnaire should be invalid if no audio file is uploaded for an "Upload a file" option. 

After #763, this should also prevent to run a survey with a questionnaire with this issue.

**Comment by asterite** [comment]
Since there's no design for how to show that error yet, I decided to show the dropzone's text in orange:

![screenshot 2017-03-22 15 18 43](https://cloud.githubusercontent.com/assets/209371/24213966/e6acd3d4-0f12-11e7-8245-22db0f66c55d.png)

**Comment by spalladino** [comment]
@asterite looks good to me!

**Comment by pmallol** [comment]
Ok in Version: 0.8.0-dev-9c248ee (build 1938)
