### ISSUE TITLE
Disable total cutoff if group quotas are set and vice versa

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#759]
Either total cutoff or group quotas should be set in a questionnaire, not both at the same time. Disable one if the other is set. 

Reported by Jason Kim via freshdesk ticket 10.

**Comment by spalladino** [comment]
@jkicillof we'd need to redesign this part of the survey form, so it's clear that either one or the other can be selected.

**Comment by spalladino** [comment]
See https://projects.invisionapp.com/d/main#/console/8374235/182593572/preview

**Comment by mmuller** [comment]
Working properly in version 6baaa96
