### ISSUE TITLE
Do not start a survey if questionnaire is invalid

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#763]
Do not allow a user to start a survey if the questionnaire is invalid. Show an invalid mark next to invalid questionnaires in the survey form.

Consider adding a "valid" flag to the questionnaire model. If a questionnaire does not have the "valid" flag set (it's null), then it is has never been validated client side; then do validate it when setting up the survey.

**Comment by spalladino** [comment]
When a questionnaire is edited, and it changes its valid/invalid status, loop through its related pending surveys to update them between "editing" and "ready".

**Comment by spalladino** [comment]
Note that a questionnaire without SMS mode shouldn't allow SMS mode to be selected. Same for Voice.

**Comment by mmuller** [comment]
Working properly in version 9c248ee
