### ISSUE TITLE
Fixes for survey index

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#766]
General
- [x] Sort surveys by most recent first

Chart
- [ ] The completion line in completed surveys should be black, not green
- [ ] The dotted line, to be shown only if there is any data, should start at the end of the green completion line, with the same slope as the one between 0,0 and the end of the green completion line, and go until 100%
- [ ] The X axis should show the time from the beginning to the end of the survey (if completed/stopped), or to the projected end date. If there is no data, show 3 months since the beginning date or current date.
- [ ] The Y axis should show completion rate, based either on the total cutoff, the sum of quota groups, or on the total number of respondents

Proposal
- [ ] Show different lines for different modes/questionnaires/quota groups

**Comment by waj** [comment]
Fixed some time ago
