### ISSUE TITLE
Getting 502 error exporting questionnaire

### ISSUE THREAD

**Issue by adam704a** [instedd/ask#768]
This is for the Zambia Pilot. We don't need this to work, but we need this zip file.

http://ask.instedd.org/projects/125/questionnaires/174/edit

![screen shot 2017-03-21 at 10 48 44 am](https://cloud.githubusercontent.com/assets/276936/24159165/03038aa4-0e24-11e7-8a02-9c72a246252d.png)

@steesdale

**Comment by spalladino** [comment]
The app is raising an OOM error when trying to generate the file. RAM consumption reaches up to almost 2GB, when the process is killed.

[erl_crash.dump.zip](https://github.com/instedd/ask/files/859620/erl_crash.dump.zip)

**Comment by spalladino** [comment]
Allowing about ~8GB of RAM the download is successful. Note that uploading the ZIP will not work unless #770 is deployed.

**Comment by spalladino** [comment]
Fixed through #777
