### ISSUE TITLE
Nice to have a total count of Surveys in the Surveys index.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#774]
<img width="1520" alt="screen shot 2017-03-23 at 9 25 05 am" src="https://cloud.githubusercontent.com/assets/518152/24247487/a3394766-0faa-11e7-8aae-f6fe5300c880.png">

<img width="1486" alt="screen shot 2017-03-23 at 9 24 31 am" src="https://cloud.githubusercontent.com/assets/518152/24247488/a33c3278-0faa-11e7-9c86-ff74ca249f7d.png">

**Comment by asterite** [comment]
Fixed by #990

**Comment by mmuller** [comment]
Working properly in version c4efa94
