### ISSUE TITLE
Compress wav audio files on upload

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#777]
To avoid having to work with large wav files (larger transfer times to twilio or verboice, larger questionnaire zips), compress them to mp3 on upload.

**Comment by spalladino** [comment]
Should handle #768

**Comment by spalladino** [comment]
To verify this issue, upload a `wav` file, download the full questionnaire zip, uncompress it, check the audios folder, and verify that they are actually `mp3` files with a smaller size than the original `wav`s.

**Comment by mmuller** [comment]
Working properly in version 9c248ee
