### ISSUE TITLE
If call is disconnected, case disposition is set to Complete.

### ISSUE THREAD

**Issue by adam704a** [instedd/ask#781]
In version 0.7.2, there appears to be something that is setting the case to complete if the call is dropped (but not ended by the user).  This can be observed by responding with 3 invalid answers to disconnect the call (on age question for example). You can use this [this](https://github.com/instedd/ask/files/866328/set_to_comlete_questionnaire.zip) questionnaire.

I also saw this same behavior when the call was dropped by Twilio once as well.

**Expected**:
If the call is disconnected, the case disposition is not updated.

**Actual**
If the call is disconnected, the disposition is set to Complete.

Here is an example [survey_response_file_too_many_completes.xlsx](https://github.com/instedd/ask/files/866351/survey_response_file_too_many_completes.xlsx) with rows highlighted that demonstrate the problem.

**Comment by mmuller** [comment]
Working properly in version 9c248ee
