### ISSUE TITLE
Projects shared with a user don't show up

### ISSUE THREAD

**Issue by edjez** [instedd/ask#782]
When a project has been shared with a user, they don't show up in the users' list until they have gone back and clicked on a share link. If the user never got a share link because they were invited before they had an account, then they have to bother the admin of the project for it (if they happen to know they have to) or more likely, they will just never join until someone realizes they're not in and invites them again.

Expected: if a user was invited to a project, it appears in the project list. We could consider adding a 'join / refuse' button.
Also: if a non-existing user email is invited to join, they should get an email with the invitation

**Comment by mmuller** [comment]
Reproduce steps:
For non-users:
As admin of the Project ‘Foo’ send and invitation to a non-user.
The non-user receives an invitation (confirmation code) via email.
As non-user click on the `Accept invitation` link from the email.
Ask redirects to the login page.
The user must confirm the account. An account confirmation is sent.
An non-user click on the `Confirm account` link.
The Project `Foo` is not displayed in the Projects listing. 
As user (already confirmed) click on the `Accept invitation` link from the email.
The Project `Foo` is displayed and the user can accept the invitation.

For users:
As admin of the Project ‘Foo’ send and invitation to user `1234`.
The user `1234` receives an invitation (confirmation code) via email.
As user `1234` click on the `Accept invitation` link from the email.
Ask redirects to the login page.
Sign in as user `1234`.
The Project `Foo` is not displayed in the Projects listing. 
Click on the `Accept invitation` link from the email.
The Project `Foo` is displayed and the user can accept the invitation.

**Comment by nditada** [comment]
Let's reverse the "burden" of accepting project invites and add them to the user list without requiring them to accept. In this way, after the user registered, he would see all the projects to which his email has been already invited. 

This would require adding a feature to remove projects from your list after you've been invited to them.

**Comment by juanboca** [comment]
@jkicillof can you provide a way for a user to leave a project he is collaborating in?

It should appear in the projects list a way to leave the projects he is a collaborator, but not on the ones he is an owner.

**Comment by jkicillof** [comment]
Let's put that option in a menu like [this one](https://projects.invisionapp.com/d/main#/console/8374235/231390779/preview). *Leave project* is not a common action, it doesn't need to be visible at first glance.

**Comment by juanboca** [comment]
What icon should we use?
What confirmation text? Is `Are you sure you want to stop your collaboration with the project 'name'?` OK for you?

**Comment by jkicillof** [comment]
Use `exit_to_app` icon and for confirmation text:
**Are you sure?**
You wont be able to access this project anymore
**LEAVE** **CANCEL**

**Comment by mmuller** [comment]
Working properly in version 55aca59
