### ISSUE TITLE
All questionnaire variables should be represented it the survey response file

### ISSUE THREAD

**Issue by adam704a** [instedd/ask#785]
In this [survey](http://surveda-zambia.org/projects/2/surveys/32), the question **diabetes2** never was asked presumably because of the skip logic (which is fine). However, this variable still should show up in the survey response file.

an example:
[respondents_disposition_history_2017-03-24-14-42-15.xlsx](https://github.com/instedd/ask/files/868449/respondents_disposition_history_2017-03-24-14-42-15.xlsx)

**Comment by mmuller** [comment]
Working properly in version 9c248ee
