### ISSUE TITLE
Export files should use consistent naming for respondent Id variable

### ISSUE THREAD

**Issue by adam704a** [instedd/ask#786]
In the disposition history file respondent id variable is called "Respondent hash"

![screen shot 2017-03-24 at 10 02 38 am](https://cloud.githubusercontent.com/assets/276936/24302693/17ca2c20-1079-11e7-97d9-012ef465dff8.png)

and in the survey response file respondent id variable is called "Respondent ID"

![screen shot 2017-03-24 at 10 04 04 am](https://cloud.githubusercontent.com/assets/276936/24302725/4022696c-1079-11e7-8f04-c3a46ce8449e.png)

This is a lower priority

**Comment by mmuller** [comment]
Now in version 9c248ee  the header reads `Respondent ID` in `Dispositions history` and `Survey results` files but the row  includes the respondent hash.

**Comment by asterite** [comment]
@adam704a should we use "Respondent ID" or "Respondent hash" in the CSV columns?
