### ISSUE TITLE
In the survey response file, the language variable should be the name

### ISSUE THREAD

**Issue by adam704a** [instedd/ask#787]
In the survey response file, the language variable should be the name (“English” “Bemba”, etc.) and not use the code (“en” “bem”)

![screen shot 2017-03-24 at 10 08 58 am](https://cloud.githubusercontent.com/assets/276936/24302988/09cba774-107a-11e7-99ab-9438d4170c95.png)

This is a lower priority.

**Comment by waj** [comment]
Let's create an Elixir library like https://github.com/waj/language-names

**Comment by asterite** [comment]
I fixed this, and also fixed it in the UI.

The new library is this one: https://github.com/manastech/language-names-elixir

**Comment by mmuller** [comment]
Working properly in version 55aca59
