### ISSUE TITLE
[Respondents] Disable scrolling in Download CSV popup and enlarge it so that all options are visible

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#788]
Version Version: 0.7.2-dev-8a3fbff (build 1887)

Unless the user knows about the location of the feature, it's hard to locate the 'Interactions' CSV
![screen shot 2017-03-27 at 1 34 06 pm](https://cloud.githubusercontent.com/assets/9214460/24367468/1d744fe4-12f3-11e7-8b0c-5b72839f6792.png)

**Comment by mmuller** [comment]
Similar behavior reported in #417

**Comment by mmuller** [comment]
Working properly in version 9c248ee

**Comment by mmuller** [comment]
I couldn't reproduce this issue in version 9c248ee, but the issue is not closed yet.

**Comment by nekron** [comment]
The issue is not closed yet because the fix was a temporary one. We should use a component to properly handle this behavior.

**Comment by pmallol** [comment]
Ok in Version: 0.8.1-dev-01a3214 (build 2073)
