### ISSUE TITLE
Handle deleting a channel in surveys

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#791]
When deleting a channel, mark all surveys that rely on that channel as invalid. Stop running surveys that rely on that channel.

Consider detecting deleted channels in Verboice or Nuntium when the broker makes a request to them, and mark them as deleted in Ask then.

**Comment by fgasperij** [comment]
`MigrateSessionToCurrentMode` migration was failing due to a `Session` with an inexistent channel.

**Comment by waj** [comment]
Let's do #1012 first. When channels are deleted, let's mark running surveys with those channels as terminated with exit_code = 3 and exit_message = "Channel 'foo' no longer exists".
