### ISSUE TITLE
Show upload progress for audio files

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#792]

**Comment by spalladino** [comment]
See also #594

**Comment by spalladino** [comment]
@jkicillof any hints on how to show an upload in progress here?

**Comment by jkicillof** [comment]
Like [this](https://projects.invisionapp.com/d/main#/console/8374235/206251445/preview) but moving the spinner to the left in order to fit on the short dropable area for audio files.

**Comment by lmatayoshi** [comment]
@Mscebba, apply style for current implementation:

<img width="1440" alt="screen shot 2017-04-06 at 12 40 45 am" src="https://cloud.githubusercontent.com/assets/8591752/24737092/8652602a-1a62-11e7-8492-8cb778709e5c.png">

Files to be modified are web/static/js/components/questionnaires/IvrPrompt.jsx and web/static/css/_forms.scss

**Comment by lmatayoshi** [comment]
@Mscebba, the "Uploading..." text is not being shown below the spinner. 
http://recordit.co/qs3o8uG77h

If it is possible, it would be great having a border similar to the AudioDropzone while displaying the spinner, as in:

![screen shot 2017-04-11 at 2 10 54 pm](https://cloud.githubusercontent.com/assets/8591752/24921394/1498b796-1ec1-11e7-8b9f-249c9c1516e0.png)

**Comment by mmuller** [comment]
Working properly in version 0.8.0
