### ISSUE TITLE
Show upload progress for questionnaire files

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#794]

**Comment by spalladino** [comment]
See also #733

**Comment by spalladino** [comment]
@jkicillof any hints on how to show an upload in progress here?

**Comment by jkicillof** [comment]
Here is an example of [phone numbers upload](https://projects.invisionapp.com/d/main#/console/8374235/206251445/preview)

**Comment by spalladino** [comment]
@jkicillof where should the spinner be shown?

**Comment by spalladino** [comment]
Note that the user should not be allowed to edit the questionnaire during upload. Should we show a modal with an "Uploading..." legend plus the spinner?

**Comment by mmuller** [comment]
Working properly in version 6baaa96
