### ISSUE TITLE
Stop keyword for stopping a survey for a respondent

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#795]
At any point during a survey, a respondent should be able to send a keyword to opt-out. 
Support STOP (case insensitive) via SMS for now.

Add a validation to questionnaire to reject any STOP responses.

**Comment by spalladino** [comment]
Ensure the "STOP" text is not stored as a response data. Do store it in the interactions log, though.

**Comment by mmuller** [comment]
Working properly in version 9c248ee
After sending `stop` the next questions are not sent, the respondent is marked as `Failed` and the Survey is marked as `Completed`.
The keyword `stop` is not stored as response.

**Comment by nditada** [comment]
@mmuller Can we confirm that even if there's a fallback mode after SMS, the respondent will not be contacted through that mode?

**Comment by mmuller** [comment]
@nditada Yes, after replying `STOP` the respondent will not be contacted through the fallback mode.
