### ISSUE TITLE
Tooltip incorrectly displayed for start survey button

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#797]
If the user moves the cursor on the start button, and then slightly moves it away, the tooltip's black background fades, but the white text is still shown. 

<img width="458" alt="screen shot 2017-03-28 at 2 44 06 pm" src="https://cloud.githubusercontent.com/assets/429604/24419359/42819274-13c5-11e7-916d-2ee64bb8a3f2.png">

**Comment by Mscebba** [comment]
This tooltip is working fine on materialize platform. There's a problem with our tooltip.js

**Comment by mmuller** [comment]
Working properly in version 6baaa96
