### ISSUE TITLE
Unable to import questionnaire using Chrome on Windows

### ISSUE THREAD

**Issue by adam704a** [instedd/ask#798]
When using Chrome on Windows nothing happens when clicking on the Import Questionnaire link. This works fine on OSX. 

![screen shot 2017-03-28 at 11 58 57 am](https://cloud.githubusercontent.com/assets/276936/24419874/fbb790b2-13ad-11e7-96d9-270c297126b4.png)

This seems related to https://github.com/instedd/ask/issues/691

This will impact testing.

**Comment by asterite** [comment]
I can't seem to reproduce this

**Comment by mmuller** [comment]
Not reproducible in version 8a3fbff
