### ISSUE TITLE
Always delete channels when disabling provider

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#800]
Right now, if a provider is disabled and channels are kept, any survey using that channel will fail, since instantiating a channel requires access to the (now deleted) oauth token.

Change the modal from asking "do you want to keep the channels? yes/no/cancel" to "this will delete the channels, are you sure? yes/no".

See #525

**Comment by spalladino** [comment]
The side effect of this issue is that instantiating a channel fails, so all associated surveys fail as well. If we do want to keep the channels, then we should somehow keep the oauth information associated to it to be able to access it. 

@waj please advise on how to proceed here, since we are removing existing functionality

**Comment by spalladino** [comment]
This should also stop any running surveys after #791 is implemented

**Comment by asterite** [comment]
Done! I commented the code for "No" in the view so it can be easily re-enabled after we discuss this.

**Comment by mmuller** [comment]
Working properly in version 9c248ee
