### ISSUE TITLE
Interactions CSV is missing 'Step Name' for step with SMS message sectioned in parts

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#801]
Version: 0.7.2-dev-8a3fbff (build 1887)

Preconditions:
There is a questionnaire which has a message step with an SMS Message divided in 2 parts.

1. Create a survey to send questions through SMS
2. After messages are sent, go to 'Respondents'
3. Download the Respondent Interactions CSV

Observed:
The values in column 'Action Data' are missing for sectioned Message steps  
![screen shot 2017-03-29 at 4 51 50 pm](https://cloud.githubusercontent.com/assets/9214460/24473788/d536e9c6-14a0-11e7-8910-4f9e8c32903a.png)

Related to #701

**Comment by spalladino** [comment]
@pmallol could not reproduce. Does this happen only with multi-part SMS? Can you confirm if  the step in the questionnaire does indeed have a name?

**Comment by spalladino** [comment]
For the record, this is the message in Nuntium. Its `step_title` attribute is empty, hence no Action Data is logged. http://nuntium-stg.instedd.org/ao_messages/99661

**Comment by pmallol** [comment]
Indeed, thank you, the Step name is showing up as expected. I couldn't reproduce it either.
