### ISSUE TITLE
Interactions CSV is empty when contact attempt fails

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#804]
Version: 0.7.2-dev-8a3fbff (build 1887)

1. Send a survey via SMS
2. Don't activate sms channel so that the contact attempt fails

When the sent message appears as '**failed**' in nuntium:
3. Go to Respondents and download the Interactions CSV

Obtained:
The CSV is empty, only columns are shown.

**Comment by spalladino** [comment]
Fix in master

**Comment by asterite** [comment]
@pmallol @spalladino On Nuntium, if the message can't be routed (no suitable channel found for routing) I'm seeing that Nuntium doesn't send a delivery ack in this case. I don't know if it's expected behaviour or not, but it doesn't seem to be a bug in ask.

**Comment by asterite** [comment]
Maybe we'd like to change Nuntium to send it anyway? I can't remember why that check is there: https://github.com/instedd/nuntium/blob/master/app/models/messages/ao_message.rb#L91

**Comment by spalladino** [comment]
@asterite I think that's quite a corner case, but good catch.

@pmallol let's try a different condition for having the contact attempt fail. Maybe use a Twilio channel and send to an invalid number...?

**Comment by mmuller** [comment]
Working properly in version bb5bb2e
