### ISSUE TITLE
Incorrect Nuntium app configuration in new apps

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#806]
When creating a new Nuntium app by syncing the provider from ask, the delivery confirmation callback is not set, and the interface is set to rss instead of get callback.

Found in 0.7.2, in local and staging, using nuntium-stg.

**Comment by asterite** [comment]
The application is configured the moment you launch a survey, though maybe we should change that.

**Comment by spalladino** [comment]
It is configured when the survey starts
