### ISSUE TITLE
Set cache headers to audio files

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#807]
Audio files are *not* being cached by browsers (when downloading them in a questionnaire) or providers (such as Twilio) since they are served with headers indicating not to cache them:
```
cache-control:max-age=0, private, must-revalidate
```

Since audio files do not change, set the headers for aggressive caching in the show action of the audios controllers.

**Comment by spalladino** [comment]
To verify this, upload a large audio file in a questionnaire, reload the page, play the audio file, reload the page again, and check via the browser's network inspector that the file is not re-downloaded.

Another test to perform is to check that Twilio actually caches the audio files. To do this, create a survey with a questionnaire with a large audio file (remember that per #777 wav files are converted to mp3, so the file should be a ~5mb mp3 file), and issue a call to a single respondent. Wait a few minutes and repeat the process. In the call log *in Twilio*, there should be a GET request from Twilio to Ask to retrieve the audio file; in the second call, the time it takes for Twilio to get the file should be much lower, as it is now cached.

**Comment by mmuller** [comment]
In version 9c248ee  I could verify this issue from the browser but the difference between the GET requests from Twilio is not substantial (4203ms and 4147ms).
