### ISSUE TITLE
Allow for editing collaborators

### ISSUE THREAD

**Issue by adam704a** [instedd/ask#808]
We'd like to be able to set someone up as a collaborator as an Editor, then later switch them to a Viewer. Currently (0.7.2), you cannot edit a collaborator once they are set up.

In addition, we need to be able to delete a collaborator from a project.

This will be very critical as we are running bigger surveys and being more selective on who has an editing role.

**Comment by nditada** [comment]
@adam704a should we put this in the backlog for additional functionality?

**Comment by adam704a** [comment]
Yeah, that's fine.

**Comment by asterite** [comment]
@jkicillof I guess we need some design for this

**Comment by waj** [comment]
- [ ] Add a delete button on each row to remove collaborators (owners cannot be removed)
- [ ] Allow editing the role of a collaborator. Clicking on the current role a dropdown is displayed to change the role. (owners role cannot be changed)
- [ ] Remove the current popup on pending invitations.

**Comment by jkicillof** [comment]
Use an inline icons menu like [this] (https://projects.invisionapp.com/d/main#/console/8374235/231395598/preview)

**Comment by lmatayoshi** [comment]
Allow editing the role of a collaborator. Clicking on the current role a dropdown is displayed to change the role. (owners role cannot be changed)

This approach turned out to be difficult to implement due to time constrains, so dropdowns only are displayed

**Comment by mmuller** [comment]
Working properly in version b4a2461
