### ISSUE TITLE
Add 'Prompt:Error' to Interaction csv documentation

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#809]
Version: 0.7.2-dev-8a3fbff (build 1887)

https://docs.google.com/spreadsheets/d/13BgutPibwCAunjl32onZ2oZ1WkU5LtGfMkkIktPyFSo/edit#gid=1881691793

For when respondents answer a quenstion with invalid answer
![screen shot 2017-03-30 at 3 20 29 pm](https://cloud.githubusercontent.com/assets/9214460/24519785/8ed78866-155c-11e7-900b-e2d8a4a5e4ef.png)

**Comment by spalladino** [comment]
Fixed
