### ISSUE TITLE
Survey is never finished when there are Stalled respondents.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#812]
Version 8a3fbff

If there is not Cutoff and there are Stalled respondents the Survey cannot finish.
Users can cancel the Survey pressing the stop button, but it is not clear why the Survey is still running after a few days.
May be helpful to define internally an end time in order to finish surveys running unnecessarily.

**Comment by spalladino** [comment]
Let's define a max-time-for-a-stalled-respondent (either a constant or a value inferred from the retry or fallback times) and move the respondent to failed after that

**Comment by spalladino** [comment]
The alternative is to leave the survey running indefinitely, and for the user to choose when he wants to cancel it; in this case, the survey will end up as cancelled instead of complete.

**Comment by nditada** [comment]
I'd say that if there are only stalled respondents in the queue, then the survey stops.

**Comment by nekron** [comment]
Respondents in stalled state will change to failed after 8 hours. This will lead to the same 8 hours survey timeout but equal for every respondent.

**Comment by mmuller** [comment]
Working properly in version 6baaa96
