### ISSUE TITLE
Respondent via IVR should be marked as failed if doesn't answer

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#813]
Given a survey with an initial language step, if the respondent picks up the phone but does not enter any digits, Ask will eventually hang up the call after 3 attempts. In that case, the respondent should be marked as failed, not completed.

Found in 0.7.2

**Comment by spalladino** [comment]
@mmuller @pmallol could you please check if this issue can be reproduced? It was spotted in https://verboice.surveda-zambia.org/calls/904

**Comment by mmuller** [comment]
Yes, I could reproduce it in version 8a3fbff

**Comment by asterite** [comment]
At least in master the respondent is marked as failed

**Comment by spalladino** [comment]
Check if this is a duplicate of https://github.com/instedd/ask/issues/781

**Comment by spalladino** [comment]
@pmallol @mmuller please try to reproduce in 0.8-dev

**Comment by mmuller** [comment]
Working properly in 0.8.0 (version 9c248ee)
