### ISSUE TITLE
Ask answers with a JSON encoded IVR message on SMS if AT is sent after fallback

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#816]
Given a survey with SMS -> IVR modes, if the respondent answers the SMS question after the fallback voice call had been enqueued, Ask will answer with the structure of the voice message encoded in a Ruby structure, such as:
```
--- !map:ActiveSupport::HashWithIndifferentAccess text: "Prompt." audio_source: upload audio_id: eaab5135-459a-4366-9c37-ae8d911d70c9
```

Found in 0.7.2

**Comment by spalladino** [comment]
@pmallol @mmuller can you try to reproduce this?

**Comment by mmuller** [comment]
I couldn't reproduce this issue in version 8a3fbff

**Comment by spalladino** [comment]
Note that the reverse might happen as well. If there is a call enqueued for several minutes, and the fallback time to SMS is less than that, then the respondent switches to SMS, the call connects, and a text-based prompt is sent to Verboice.

**Comment by asterite** [comment]
I was able to reproduce this locally :-)

**Comment by mmuller** [comment]
Working properly in version 9c248ee
