### ISSUE TITLE
Process user numeric response on IVR after the max number of keypresses

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#817]
Given a multiple choice option, where the numbers for all options are single-digit, the user's response can be processed right away after the first digit is entered, without having to wait the 5 seconds timeout. Same applies to numeric questions with a max value.

Send the maxDigits options to Verboice, using the number of digits of the longest option (if a multiple choice question), or the number of digits of the max accepted value (if a numeric question).

**Comment by asterite** [comment]
Duplicate of #961 (fixed already)
