### ISSUE TITLE
Export MNO error codes in respondent interaction log

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#821]
Note that this information is currently reaching verboice. Make sure it is forwarded to ask, and stored in the survey log.

**Comment by nekron** [comment]
Depends on https://github.com/instedd/verboice/issues/809

**Comment by waj** [comment]
The changes in Verboice are deployed in staging environment. I'd like to improve the solution I implemented but this issue can be considered completed as there are no more changes required on this side.

**Comment by mmuller** [comment]
Working properly in version aebfaec
