### ISSUE TITLE
Change quota completed message to steps

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#822]
Remove quota completed message altogether, and replace by a new questionnaire flow. Note that it should not be possible to jump (ie skip logic) from the main flow to this one, but do allow skip logic within this flow.

Implement in feature branch, wait for 0.9 to merge.

**Comment by nekron** [comment]
For drag and drop, do whatever is easier for now.

**Comment by jkicillof** [comment]
https://projects.invisionapp.com/d/main#/console/8374235/230465184/preview
https://projects.invisionapp.com/d/main#/console/8374235/230465183/preview (the link will open a new questionnaire editor for the quota completed branch)

**Comment by waj** [comment]
NOTE: "Flag" steps are not allowed within the quota completed steps

**Comment by nditada** [comment]
We changed this now to avoid opening a separate editor, but the links above are still valid. cc @waj

**Comment by nekron** [comment]
It's a good chance to finally extract the steps reducer from the questionnaire reducer and reuse it for the new steps.

Same for the validations reducer. Ideally we should not have to define all the validations for the new steps, but simply provide a new path to the same reducer.

**Comment by mmuller** [comment]
Working properly in version 55aca59
