### ISSUE TITLE
Interactions CSV 'Step Name' for step with SMS split message starts with 0

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#823]
Version: 0.7.2-dev-8a3fbff (build 1887)

Preconditions:
There is a questionnaire which has a message step with an SMS Message divided in 2 parts.

1. Create a survey to send questions through SMS
2. After messages are sent, go to 'Respondents'
3. Download the Respondent Interactions CSV

Observed:
The step name displayed in 'Action Data' for split messages starts with 0
  
Expected: 
The step name starts with 1

![screen shot 2017-04-04 at 1 35 39 pm](https://cloud.githubusercontent.com/assets/9214460/24667981/a167ceae-193b-11e7-887f-508015a701f4.png)

**Comment by mmuller** [comment]
Split messages are still starting with zero in version 6baaa96

[respondents_interactions_2017-04-17-14-10-09.txt](https://github.com/instedd/ask/files/925748/respondents_interactions_2017-04-17-14-10-09.txt)

**Comment by mmuller** [comment]
Working properly in version dafd799
