### ISSUE TITLE
Do not show validation errors on a new step

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#826]
Show errors only on lost focus

**Comment by nekron** [comment]
Same as #574

**Comment by asterite** [comment]
My opinion is that this is WRONG. I edit a step, I see a red mark as an error in the lanaguage/mode list, but I have no idea why or where is the error. I have to close the stop and expand it to see the error. Totally unintuitive. Errors should be there from the start. They prompt the user to fill the missing inputs.

**Comment by mmuller** [comment]
Working properly in version 322bad2
