### ISSUE TITLE
Add refusal flag

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#828]
Add "Refusal" as a flag to the "set disposition" step. It's important to make sure that the disposition will not be changed after the skip logic points to "End survey".

**Comment by asterite** [comment]
Done!

@spalladino Internally we store it as "refusal". Is that the correct name for the disposition? Or should we use "refused"? (in any case this is internal data, we can expose it with whatever name we'd like, but for consistency's sake...)

**Comment by spalladino** [comment]
I'd say "refused" is more consistent with "ineligible" and "completed" than "refusal"; but since this is internal data, if it's already implemented as "refusal", I'm fine with it :-)

**Comment by asterite** [comment]
I was going to store it as "refused" but the original description didn't say that. I can still change it if you think it's worth it. So to be clear, we'd use "Refusal" in the UI the "Flag step" options, but show "refused" internally and in CSVs, etc., right?

**Comment by steesdale** [comment]
I think "refused" in the external UI makes more sense.

**Comment by spalladino** [comment]
Let's go for "Refused" in CSV and UI, and either refusal or refused internally

**Comment by mmuller** [comment]
`Refused` flag correctly added in version 6baaa96
