### ISSUE TITLE
Add an orange dot to questionnaires with validation errors in questionnaire listing

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#829]
Version: 0.8.0-dev-9c248ee (build 1938)

When a Questionnaire has a validation error it appears in the Survey Questionnaire selection with an orange dot next to it. I suggest implementing the same approach in the Questionnaire listing so that the user can easily recognise questionnaires with validation issues.

![screen shot 2017-04-04 at 4 03 34 pm](https://cloud.githubusercontent.com/assets/9214460/24673977/623c1072-1950-11e7-8fa8-2463e4370981.png)
![screen shot 2017-04-04 at 4 03 44 pm](https://cloud.githubusercontent.com/assets/9214460/24673979/6260b710-1950-11e7-8497-b9766f3ff44f.png)

**Comment by waj** [comment]
Let's show the orange dot at the rightmost side of each row for the questionnaires having unsolved issues

**Comment by mmuller** [comment]
Working properly in version d6a51e4
