### ISSUE TITLE
Option to create Channel should be added to Survey editor.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#83]
Found in version: 0.1.0-dev-7213533

Preconditions:
The account 'Foo' has no Channels.

Reproduce steps:
Sign in as 'Foo'.
Go to create a new Survey.

Obtained:
In the wizard the user must select a Channel but he/she has no Channels yet. It is not clear how users can create a new Channel.

Expected:
If the account has no Channels we should display a button to create a new Channel from the wizard.

<img width="1547" alt="screen shot 2016-10-03 at 9 02 06 am" src="https://cloud.githubusercontent.com/assets/518152/19036745/2e56f328-8948-11e6-915e-c7a3ced6e1c9.png">

**Comment by waj** [comment]
This was discussed already in previous meetings. Channels is not something that will be created during the same workflow where surveys are created, and probably will be done by different persons.
