### ISSUE TITLE
If only the Mobile mode is enabled the Error Message step should be hidden

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#833]
Found in version 9c248ee

Reproduce steps:
Go to create a Questionnaire.
Disable the `Phone call` and `SMS` modes.
Enable the `Mobile web` mode.
Observe the `Error message` step.

Obtained:
The Questionnaire is marked as invalid because the `Error message` step is empty. Note that it is not possible to add an `Error message` if only the `Mobile web` mode is enabled.

Expected:
The `Error message` step should be hidden if only the `Mobile web` mode is enabled.

<img width="1416" alt="screen shot 2017-04-06 at 3 21 12 pm" src="https://cloud.githubusercontent.com/assets/518152/24769862/5e14dae4-1ade-11e7-8754-2c76652b364b.png">

**Comment by nditada** [comment]
I'm not sure this is a bug, we will need an error message for numeric answers in mobile web.

**Comment by nekron** [comment]
Already added the error msg with https://github.com/instedd/ask/pull/840
