### ISSUE TITLE
[Questionnaire] Validation error is not properly displayed in Mobile web mode.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#834]
Found in version: 9c248ee

Reproduce steps:
Go to create a Questionnaire.
Enable the `SMS` mode.
Enable the `Mobile web` mode.
Add a `Multiple choice` step.
Add a Response.
Click on the `Mobile web` filed and lose the focus.
Observe the validation error.

Obtained:
The orange point overlaps the text.

<img width="905" alt="screen shot 2017-04-06 at 3 39 42 pm" src="https://cloud.githubusercontent.com/assets/518152/24770505/88a9df28-1ae0-11e7-8370-5a61e7ee95f3.png">

**Comment by steesdale** [comment]
It seems like the text for Mobile Web should not be all CAPS?  “e.g., -> Mobile Web”

Also, the differentiation between IVR here and SMS/Mobile Web is kind of funny.  Specifically, Each mode would collect a responses.  But only IVR is called response.  Is a somewhat visually confusing since the patterns break down.

**Comment by mmuller** [comment]
@steesdale the text for the three modes are displayed in all-caps:
`No SMS`
`No IVR`
`No MOBILE WEB`

**Comment by steesdale** [comment]
Let me try to be more specific …. I see in the questionnaire designed strings are capitalized in different ways.

"No response” -> Only the N is caps
“No SMS” -> NThis makes sense as its an abbreviation.
“No IVR” -> Ditto, This makes sense as its an abbreviation.
“No MOBILE WEB” -> I would expect this to match the first format for non-abbreviated words.

We also have “Next question”.  And “End survey”   -> the out of the box capitalization is mismatched.
“Add Language”
“Export questionnaire”
- etc…

I would expect to just use a common approach to the strings - something like this…
- “No Response”
- "No SMS”
- “No IVR”
- “No Mobile Web”
- “Next Question”
- “End Survey"

Or

- “No response”
- “No SMS”
- “No IVR”
- “No mobile web"
- “Next question”
- “End survey"

Scott

**Comment by mmuller** [comment]
Great! Thank you very much @steesdale

**Comment by nekron** [comment]
If there is no input, display only the orange dot. Avoid the "No ..." altogether.
If there is an input, but it's invalid, display only the text in orange with a dotted underline, with no dot.

**Comment by mmuller** [comment]
Working properly in version 6baaa96
