### ISSUE TITLE
[Survey] The launch survey tooltip does not stay fixed while scrolling

### ISSUE THREAD

**Issue by juanboca** [instedd/ask#835]
If the user hovers the play button, and then scrolls (without moving the cursor) up or down, the tooltip will move at the same time as the rest of the content outisde the sidebar, and move away from the play button

<img width="1147" alt="screen shot 2017-04-06 at 4 48 34 pm" src="https://cloud.githubusercontent.com/assets/488553/24772743/e8430a6a-1ae8-11e7-8ca2-63cd2efacfaf.png">

<img width="1163" alt="screen shot 2017-04-06 at 4 45 47 pm" src="https://cloud.githubusercontent.com/assets/488553/24772678/a0c6c37a-1ae8-11e7-9ed6-ce89dac1c473.png">

**Comment by pmallol** [comment]
Ok in Version: 0.10.0-dev-8e75560 (build 2581)
