### ISSUE TITLE
Add progress bar to mobile web respondents form

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#836]
Show a progress bar based on the total number of steps in the questionnaire, jumping forward if there is any skip logic. Use the design in invision.

Depends on #721

**Comment by nekron** [comment]
Make the calculation in the flow, add it to the reply, to allow other modes to take advantage of it in the future.

The reply should contain the current step number, and the total number of steps, excluding flag steps.

**Comment by mmuller** [comment]
Working properly in version d6a51e4
