### ISSUE TITLE
[Questionnaire] Replace texts in Questionnaire view

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#838]
Reported by @https://github.com/steesdale

I see in the questionnaire designed strings are capitalized in different ways.

"No response” -> Only the N is caps
“No SMS” -> NThis makes sense as its an abbreviation.
“No IVR” -> Ditto, This makes sense as its an abbreviation.
“No MOBILE WEB” -> I would expect this to match the first format for non-abbreviated words.

We also have “Next question”.  And “End survey”   -> the out of the box capitalization is mismatched.
“Add Language”
“Export questionnaire”
- etc…

I would expect to just use a common approach to the strings - something like this…
- “No Response”
- "No SMS”
- “No IVR”
- “No Mobile Web”
- “Next Question”
- “End Survey"

Or

- “No response”
- “No SMS”
- “No IVR”
- “No mobile web"
- “Next question”
- “End survey"

**Comment by nekron** [comment]
- Remove the "No..." texts altogether
- Keep "Next step” and “End survey" versions in the skip logic

Reference:
https://projects.invisionapp.com/d/main#/console/8374235/184295215/preview

**Comment by asterite** [comment]
Fixed by #1010

**Comment by mmuller** [comment]
Working properly in version 55aca59
