### ISSUE TITLE
[SurveyWizard] Spinner stays after respondents upload fails

### ISSUE THREAD

**Issue by lmatayoshi** [instedd/ask#839]
Steps to reproduce:

- Go to Survey Wizard
- Try to upload an invalid respondent.csv file, by drag and dropping in the dropzone
- Click the 'UNDERSTOOD' button

Expected:
- Uploading dropzone returns to normal state

Obtained:
- Uploading spinner stays in the dropzone

http://recordit.co/y6lIwExHDL

**Comment by mmuller** [comment]
Working properly in version 6baaa96
