### ISSUE TITLE
Add mobile web message for "survey is over"

### ISSUE THREAD

**Issue by nekron** [instedd/ask#844]
Should be present for Mobile web only. Add as another message in the questionnaire, like error or quota completed.

To be displayed if a respondent follows the link after the survey was finished.

Only to be displayed if mobile-web mode is active.

**Comment by asterite** [comment]
The message should probably belong to the survey, not to each questionnaire, because it makes no sense to have this be part of a questionnaire: consider a survey that compares multiple questionnaires.

**Comment by nekron** [comment]
Take one at random.

**Comment by mmuller** [comment]
Working properly in version d6a51e4
