### ISSUE TITLE
Allow more respondents to be added to an ongoing survey

### ISSUE THREAD

**Issue by nekron** [instedd/ask#845]
After a survey has been started, support adding more respondents.

We should allow only to add respondents to existing groups, NOT allow new respondents groups.

- [ ] Turn the existing group into a dropzone, with a prompt for adding or replacing the current respondents if the survey has not started yet, or just adding them if the survey is running.
- [ ] Notify the user that "n respondents have been added"
- [ ] Add an ADD MORE RESPONDENTS blue button to the left of the footer.
- [ ] Make the DELETE button grey.

**Comment by mmuller** [comment]
Working properly in version d6a51e4
