### ISSUE TITLE
Add a stalled respondents pool

### ISSUE THREAD

**Issue by nekron** [instedd/ask#848]
Currently we have a `batch_size` (we have two, but more on that later), that’s equivalent to the `active_pool`: number of max calls or SMS that are scheduled to go out at any one time.
We need to add a `stalled_pool`: it’s the waiting list/queue of people waiting to be contacted because:
- We have not yet contacted them (but we should)
- The previous contact attempt failed and there are still pending attempts in the schedule

- [ ] Support a `queue_size` that is `active_pool_size + stalled_pool_size`
- [ ] Keep the `batch_size` as `active_pool_size`.
- [ ] Both the `queue_size` and the `active_pool_size` should be configurable through environment variables.
- [ ] The second `batch_size` is how many of those active respondents are we processing per minute, to allow to the callbacks to be answered. Keep this `batch_size` as it is but allow it also to be set through an environment variable.

**Comment by nditada** [comment]
@nekron please discuss this with @waj, there are some improvements we came up with.
