### ISSUE TITLE
[Respondents] CSV download popup makes horizontal scroll bar appear in Windows

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#849]
Version: 0.8.0-dev-6baaa96 (build 2002)
Tested on Windows 7 Chrome 57.0.2987.133

![ask](https://cloud.githubusercontent.com/assets/9214460/24970180/c24b00f6-1f89-11e7-86bb-3fd1848039b4.png)

**Comment by nekron** [comment]
This is related to the change done for #788

**Comment by pmallol** [comment]
Ok in Version: 0.9.0-dev-8fcc4de (build 2189)
Tested with VM Windows 7 (64-bit)
