### ISSUE TITLE
Duplicate respondents can be created when uploading CSV

### ISSUE THREAD

**Issue by asterite** [instedd/ask#852]
Try with this CSV (note the space in the second line):

```
123456789
12345 6789
```

This will create two respondents whose "sanitized" number will be "123456789", so there will be a duplicate.

To solve this, don't just `uniq` the numbers, `uniq` them according to their sanitized version.

**Comment by nekron** [comment]
Check that this does not also happens when the numbers are
```
+1234567
1234567
(+1)234567
```

**Comment by mmuller** [comment]
The same occurs when the numbers are:
```
+1234567
1234567
(+1)234567
01234567
(12) 34-567
```

**Comment by mmuller** [comment]
Working properly in version aebfaec
