### ISSUE TITLE
Survedization: DNS and redirects

### ISSUE THREAD

**Issue by edjez** [instedd/ask#855]
Expected:
-> instances on surveda.instedd.org; surveda-stg ; and surveda-demo
-> Redirects from ask, ask-stg and ask-demo to the above
-> making sure that in migration makes sure of authentication, authorizaton with nuntium + verboice; and channel URLs (eg callbacks from verboice, nuntium  etc) are all taken care of

This will be important for launch (especially surveda.instedd.org)

**Comment by nekron** [comment]
Adding a checklist so we don't forget anything.

Enable domains:
- [ ] surveda.instedd.org
- [ ] surveda-demo.instedd.org
- [ ] surveda-stg.instedd.org

Redirect:
- [ ] ask.instedd.org -> surveda.instedd.org
- [ ] ask-demo.instedd.org -> surveda-demo.instedd.org
- [ ] ask-stg.instedd.org -> surveda-stg.instedd.org

Update server configuration to match the new url:
- [ ] surveda.instedd.org
- [ ] surveda-demo.instedd.org
- [ ] surveda-stg.instedd.org

**Comment by mmuller** [comment]
Working properly in versions:
55aca59 (stg)
0.9.5 (surveda-demo and surveda)
