### ISSUE TITLE
[Survey] SMS channel configuration appears as 'Phone channel'

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#856]
Version: 0.8.0-dev-6baaa96 (build 2002)

1. Create a survey
2. Select any Mode that includes SMS
3. Add respondents

Obtained:
The SMS channel drop menu selector appears as 'Phone channel'
![screen shot 2017-04-13 at 5 19 09 pm](https://cloud.githubusercontent.com/assets/9214460/25022841/c97474cc-206d-11e7-86ea-5a4c65515bf7.png)

**Comment by mmuller** [comment]
Working properly in version 0.8.0
