### ISSUE TITLE
[Mobile Survey] Properly handle multiple tabs

### ISSUE THREAD

**Issue by nekron** [instedd/ask#870]
Ensure that if the same respondent opens a questionnaire in multiple tabs, the application works properly. Answers already sent should be **ignored** by the broker (and not understood as answers for the current question).

  For example:
  1- User opens Tabs T1 and T2 with the questionnaire
  2- User answers Question 1 (Q1) on T1 with YES, and is presented with Q2 in that tab
  3- User answers Q2 with YES in T1 as well, and is presented with Q3 in that tab
  4- User switches to T2, which still has Q1, and sends a NO

  The application should ignore the last NO, ensuring it is not understood as a reply for Q3, optionally display an error, and show Q3 in T2.

**Comment by mmuller** [comment]
Working properly in version d6a51e4
