### ISSUE TITLE
[Mobile Web] Clicking "Next" after explanation step fails

### ISSUE THREAD

**Issue by asterite** [instedd/ask#871]
Steps to reproduce:

- Create a questionnaire with an explanation step followed by a multiple-choice step
- Create a survey with that questoinnaire
- Start the survey
- Follow the link
- Click on "next" (siguiente)

Expected: user is shown the next answer
Actual: an error message appears and the respondent is marked as failed

**Comment by mmuller** [comment]
Working properly in version aebfaec
