### ISSUE TITLE
[Quiz] Empty response error in mobile web is not being displayed after collapsing and expanding step

### ISSUE THREAD

**Issue by lmatayoshi** [instedd/ask#876]
Steps to reproduce:
- Create a new questionnaire
- Toggle SMS mode and mobile-web mode
- Create a multiple choice step without responses
- Collapse step and expand it again, so it starts displaying the errors

Obtained:
- No mobile-web error is displayed, and it only appears after clicking in the response and then outside it.

Expected:
- A mobile-web error should be displayed from the beginning

http://recordit.co/ID4PCoi5Rn

**Comment by mmuller** [comment]
Working properly in version bb5bb2e
