### ISSUE TITLE
[Mobile web] Change cursor to hand when mouse goes over an option.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#881]
Found in version 0.8.0 (build 2035)

<img width="1661" alt="screen shot 2017-04-18 at 2 41 42 pm" src="https://cloud.githubusercontent.com/assets/518152/25144698/2a90f1ba-2445-11e7-85f6-1d62a58e653d.png">

**Comment by asterite** [comment]
This is not done because a user will see it in a mobile, so there's no cursor.
