### ISSUE TITLE
[Quiz] Error is not shown when a multiple choice option has less than 2 options

### ISSUE THREAD

**Issue by lmatayoshi** [instedd/ask#883]

**Comment by fgasperij** [comment]
A multiple choice step? Which multiple choice?

**Comment by mmuller** [comment]
@fgasperij Yes, it happens within the `Multiple Choice` step:

<img width="881" alt="screen shot 2017-04-21 at 11 02 02 am" src="https://cloud.githubusercontent.com/assets/518152/25280930/057034ce-2682-11e7-8850-db7a92530886.png">

**Comment by waj** [comment]
There is a design for this:
https://projects.invisionapp.com/d/#/console/8374235/209338838/preview

**Comment by mmuller** [comment]
Working properly in version d6a51e4
