### ISSUE TITLE
First recontact attempt is being ignored if a fallback is pressent

### ISSUE THREAD

**Issue by nekron** [instedd/ask#889]
Setting a recontact attempt of `1m` and a fallback timeout of `1m` results in not having a retry for the primary mode, but jumping straight to the fallback mode.

Fallback retries are working properly.

<img width="1187" alt="screen shot 2017-04-18 at 3 38 56 pm" src="https://cloud.githubusercontent.com/assets/957103/25147281/6d1d684e-244d-11e7-8abe-589f2ad4a1f4.png">

<img width="222" alt="screen shot 2017-04-18 at 3 39 02 pm" src="https://cloud.githubusercontent.com/assets/957103/25147282/6d3cf5b0-244d-11e7-8a81-b77452669dbf.png">

The questionnaire had an initial explanation step and a prompt.

**Comment by fgasperij** [comment]
This behavior was introduced on this commit (https://github.com/instedd/ask/commit/2b4acc1aab83942884ccd08f691954097e7e6f69#diff-b2805642915a78795fe622c4ee9178d9R59) intentionally, are we sure that it is not desired? Which would be the desired one?

**Comment by mmuller** [comment]
Working properly in version 8fcc4de
