### ISSUE TITLE
Phillippines - Add Chikka Aggregator to Nuntium

### ISSUE THREAD

**Issue by edjez** [instedd/ask#891]
https://api.chikka.com/docs/overview

**Comment by matiasgarciaisaia** [comment]
Test app for reference: https://github.com/matiasgarciaisaia/chikka-test

**Comment by mverzilli** [comment]
Work in progress being done here: https://github.com/instedd/nuntium/commits/wip-chikka

Current status: ready to test. Working with PHL IT staff to help us test end to end. We'll merge to `master` and deploy to staging once we complete some basic end-to-end testing.

**Comment by waj** [comment]
This is already in staging and ph environment. Going to be released in Nuntium 1.10.
