### ISSUE TITLE
Remove dummy `nil` choice from language selection step

### ISSUE THREAD

**Issue by asterite** [instedd/ask#894]
The dummy choice is a hack so that when a user presses "1" it automatically indexes to the correct choice without having to subtract one.

- [x] Don't create the dummy `nil` choice
- [x] Don't ignore the first choice in the language selection step in the UI
- [x] Change tests accordingly
- [x] Write a migration to fix existing language selection steps

**Comment by mmuller** [comment]
#880 and #877 working properly in version bb5bb2e
