### ISSUE TITLE
[Questionnaire] It isn't obvious that empty choices are editable

### ISSUE THREAD

**Issue by asterite** [instedd/ask#896]
Because we applied the comment [here](https://github.com/instedd/ask/issues/834#issuecomment-293337284), when first editing a multiple-choice step and adding choices to it, choices have no value and they aren't supposed to show an error yet, so they appear totally blank and it's not obvious that they are clickable.

I suggest we consider adding a "Missing" text, that's obvious that's something wrong, instead of a floating orange dot that's hard to understand.

We should discuss this before proceeding.

**Comment by waj** [comment]
I agree, let's add the "Missing" caption when there is no content in the field.

**Comment by mmuller** [comment]
Working properly in version bb5bb2e
