### ISSUE TITLE
[Questionnaire] Make the SMS/IVR input more usable

### ISSUE THREAD

**Issue by adam704a** [instedd/ask#898]
The size of the SMS/IVR text boxes is too small, and poses difficulties for QC. When people do QC in the tool, they often are looking at the text. But you can only see 1/3 of the SMS message at a time. Having to navigate around using arrows is burdensome for users and in one case, has caused someone to delete text.

![instedd_ask](https://cloud.githubusercontent.com/assets/276936/25190306/0ecc9ab6-24e9-11e7-9ab6-d5257d9a80ae.png)

**Comment by nekron** [comment]
We should apply draft.js message boxes to SMS and IVR input.

Keep in mind that SMS and IVR should not allow for bold or italic styles.

**Comment by nekron** [comment]
This depends on #710

**Comment by asterite** [comment]
For the one that's going to tackle this:
- The `Draft` component has a `plainText` property: when set to `true`, it's value will be the plaintext representation of the content (one can still use ctrl+b to make text bold, we should disable that)
- SMS and IVR inputs provide autocomplete, which works with a plain `input` tag: `materialize_autocomplete` uses it. If we change the inputs to use draft-js we lose the autocomplete functionality, so it'll have to be reimplemented. Good luck :-)

**Comment by mmuller** [comment]
Working properly in version 55aca59
