### ISSUE TITLE
[Sign up] Validation error message are not styled

### ISSUE THREAD

**Issue by fgasperij** [instedd/ask#899]
The validation error messages of the sign up form  should follow the style used in https://projects.invisionapp.com/d/main#/console/8374235/220060240/preview 
The text should be orange and closer to the field.

**Comment by fgasperij** [comment]
![screen shot 2017-04-19 at 11 35 37 am](https://cloud.githubusercontent.com/assets/1685226/25967840/d1ab696c-3665-11e7-88d8-8d4f35f430a5.png)

**Comment by Mscebba** [comment]
An error class style is missing for input text fields. I can't style the red underline without a class

**Comment by asterite** [comment]
Now it looks like this:

![screen shot 2017-05-15 at 10 31 09 am](https://cloud.githubusercontent.com/assets/209371/26059884/a65420aa-3959-11e7-8e5b-f5c3efec59d3.png)

I don't know if the "Oops" text should appear in red too as there's no design for this, but the page is much clearer now.

**Comment by mmuller** [comment]
Working properly in version 55aca59
