### ISSUE TITLE
Mobile Web - Intro message gets appended to link, which gets 'cut'

### ISSUE THREAD

**Issue by edjez** [instedd/ask#904]
Expected:
1) Shorter link URLs!
2) If the URL would be 'cut' by the intro message, the intro message editor displays a warning that it will take 2 messages to do the introduction, AND the intro text is sent in one SMS, and the full link in another SMS.

Current:
Message 1: 
>>Hi, Please answer this survey from the Shanghai 12320 team to help us provide the right health services in our city https://ask-stg.instedd.org/mobile_survey/11
Message 2:
>>49516?token=4a446b4dc6af

![image](https://cloud.githubusercontent.com/assets/1182549/25211329/9fea3ee0-2539-11e7-9b09-a5e5b1f9c209.png)

**Comment by nekron** [comment]
This should've been fixed by #862

**Comment by mmuller** [comment]
Working properly in version 8fcc4de
