### ISSUE TITLE
Survey Designer - Modes selection is confusing

### ISSUE THREAD

**Issue by edjez** [instedd/ask#906]
current: an exhaustive list of all mode combinations for first and second attempts

Suggest a row with 3 drop downs
1st Mode:  {sms/ivr/mobile web} 
2nd Mode:  {sms/ivr/mobile web/none}
{if 2nd is not 'none', show this} 3rd Mode:  {sms/ivr/mobile web/none}

Maybe it makes sense to put the fallback delay there too

**Comment by waj** [comment]
This is being covered by #861
