### ISSUE TITLE
[Mobile web] Style for respondents form

### ISSUE THREAD

**Issue by lmatayoshi** [instedd/ask#907]
Requirements according to @jkicillof:

- [x] Options should be aligned to bottom of the screen (Multiple choice step). In other words, it shouldn't be empty space at the bottom of the screen

![options-aligned-1](https://cloud.githubusercontent.com/assets/8591752/25243338/0cfab3b8-25d3-11e7-8c9d-22b20e7881f5.png)

- [x]  Options also should be aligned to bottom for Numeric Steps

![options-aligned-2](https://cloud.githubusercontent.com/assets/8591752/25243675/462a797e-25d4-11e7-8fcc-a3d960d4b542.png)

- [x] An "Understood" text or similar is required next to the "check" icon in explanation steps

![understood](https://cloud.githubusercontent.com/assets/8591752/25243794/b344d77a-25d4-11e7-9c70-a4e6adfb2c3c.png)

- [x] Ideally, all buttons should have the same size. If that wasn't possible, longer texts should share a minimum height equivalent to shorter ones. And from there, it should expand as required. In the next example, LESS THAN DAILY BUTTON is slightly shorter than the other ones

![button-size](https://cloud.githubusercontent.com/assets/8591752/25244323/962f2c92-25d6-11e7-8fce-744db19d01dc.png)

Example of buttons of same height:
https://projects.invisionapp.com/d/main#/console/8374235/220357665/preview

**Comment by Mscebba** [comment]
The new classes for buttons are:
"btn large": when buttons count < 4
"btn large multiline": when buttons count < 4, and 2 or more lines of text inside
"btn small": when buttons count > 3

**Comment by Mscebba** [comment]
"prompt" div has a min-height so buttons are aligned to the bottom, but is an approach, not a perfect solution.

**Comment by asterite** [comment]
@lmatayoshi All the chekboxes are checked. What's missing?

**Comment by pmallol** [comment]
Tested with Iphone 5s  and 6 in Chrome and Safari:
- [ ] The Numerical step input field is not aligned with its button.
- [ ] The 'Refusal' option is displayed on top of the input field

Iphone 5s
![img_2017-05-19 13 45 26](https://cloud.githubusercontent.com/assets/9214460/26258201/fbde8860-3c99-11e7-9100-3583583b7527.jpg)

Iphone 6
![img_2017-05-19 13 58 47](https://cloud.githubusercontent.com/assets/9214460/26258523/5f8369de-3c9b-11e7-9e23-a1cebf54378b.jpg)

**Comment by pmallol** [comment]
Ok in Version: 0.10.0-dev-55aca59 (build 2483)
