### ISSUE TITLE
Surveys done in the past loose data when questionnaire is edited

### ISSUE THREAD

**Issue by edjez** [instedd/ask#913]
Steps:
- Run survey with a qex with 3 questions "Survey 1"
- See data (can see 3 result columns)
- Delete / edit significantly qex
- Look at "survey 1" results and they are missing the column

expected:
- When starting a survey, the survey engine creates a snapshot reference of the questionnaire at that point in time, and future edits of the questionnaire don't affect past data survey data items or column names.

Not sure what happens if modes are added/deleted, if languages are added/deleted but it seems it may cause similar related issues.

**Comment by waj** [comment]
Let's create copies of the questionnaires when the survey is started. The copies will be stored in the same table, adding a `snapshot_of` column with the ID of the original questionnaire.

  * [ ] When the survey is started, create the questionnaire copies and update the references
  * [ ] List  only questionnaires where `snapshot_of IS NULL`
  * [ ] Make sure the API doesn't allow updating questionnaire snapshots

**Comment by pmallol** [comment]
Ok in Version: 0.9.0 (build 2357)
