### ISSUE TITLE
[Mobile web] Questionnaire with invalid Mobile Web SMS message is not disabled in the Survey wizard.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#914]
Found in version bb5bb2e

Reproduce steps:
Create a questionnaire.
Enabled the Mobile web mode.
Fill the Mobile web SMS message field with a text too long (~300 chars).
Collapse the Step. The Step does not become orange indicating that there is an error.
Create a Survey.
Select the Questionnaire created in the first step.

Obtained:
The Questionnaire can be selected in the Survey wizard.
If the Survey is started, the respondent receives the SMS with text too long (~300 chars).

Expected:
Questionnaires with invalid Mobile Web SMS message should be disabled in the Survey wizard.

**Comment by asterite** [comment]
Fixed in https://github.com/instedd/ask/commit/714c5c398b415ff41738d883c8232f06c7f0edf8

**Comment by mmuller** [comment]
Working properly in version d6a51e4
