### ISSUE TITLE
Refactor different messages into a single field

### ISSUE THREAD

**Issue by waj** [instedd/ask#915]
Currently we have these message fields, each on a separate column in the table:
 - quota completed
 - error
 - mobile web sms

Let's move the contents of these fields into a single one ("settings") containing a JSON:

```
{
  "quota_completed_message": ...,
  "error_message": ...,
  "mobile_web_sms_message": ...,
  "mobile_web_survey_is_over_message": ...,
}
```

Make sure existing questionnaires are updated with a migration that moves the contents of the previous fields into the new one before removing the columns

**Comment by nekron** [comment]
Shouldn't we keep `:quota_completed_msg` in a separate variable to give place to #822 ?
