### ISSUE TITLE
[Mobile web] Scroll indicator

### ISSUE THREAD

**Issue by waj** [instedd/ask#917]
When the content of the questionnaire step exceeds the height of the window, display an arrow at the bottom of the page (https://projects.invisionapp.com/share/3U8BARPXJ#/screens/227391086).

The arrow should appear with an animation (ask @jkicillof for details) and disappear when the user scrolls the page.

**Comment by mmuller** [comment]
The indicator is not displayed.
Version 8fcc4de
Plattforms: Android and iOS

**Comment by lmatayoshi** [comment]
It think the problem is that 'ic_arrow_downward.svg' file is missing

**Comment by Mscebba** [comment]
Don't link an svg to an external file, embed the svg directly into the html. Check the other files for an example

**Comment by mmuller** [comment]
Working properly in version a74ed81
