### ISSUE TITLE
Refusal doesn't work.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#918]
Found in version bb5bb2e

Reproduce steps:
Create a questionnaire.
Add a `Numeric` Step.
Check `Accepts refusals`.
Fill the `Valid entries` field.

Obtained:
The value entered in the `Valid entries` field is lost.
The `Skip logic` option is set as `Next question` but this option is marked as invalid.

http://recordit.co/VqbJUqse7o

**Comment by waj** [comment]
Also the column for "Mobile web" is missing in the refusal options table

**Comment by mmuller** [comment]
<img width="929" alt="screen shot 2017-04-21 at 4 21 12 pm" src="https://cloud.githubusercontent.com/assets/518152/25292900/9a26c926-26ae-11e7-9fe1-9eb46194cf5f.png">

**Comment by asterite** [comment]
I just fixed the UI (in the `release/0.8` branch)

@jkicillof Could you give us the design for mobile web showing a numeric question with a way to choose a refusal? I imagine a button with that text or something similar.

**Comment by jkicillof** [comment]
https://projects.invisionapp.com/d/main#/console/8374235/220357664/preview

**Comment by asterite** [comment]
This is working now.

@Mscebba Style is missing for this. Could you take care of these two points?

1. The skip icon is missing. In materialize it's the "redo" icon, but **we are not using materialize in the mobile survey**, so maybe we need a hand-made icon for this.
1. The link is not aligned to the bottom of the page.

The code is in `/web/static/mobile_survey/js/components/steps/NumericStep.jsx`. Thank you!

**Comment by mmuller** [comment]
Working properly in version 6a4d2ce
