### ISSUE TITLE
[Mobile Web] Numeric input and checkbox are not aligned in iOS

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#921]
Version: 0.8.1-dev-bb5bb2e (build 2077)
iPhone 5S 

![whatsapp image 2017-04-21 at 5 45 09 pm](https://cloud.githubusercontent.com/assets/9214460/25295563/6fcf9340-26ba-11e7-8ae2-6e0504b90837.jpeg)

**Comment by pmallol** [comment]
Still needs fixing in Version: 0.9.0-dev-8fcc4de (build 2189)

**Comment by mmuller** [comment]
Working properly in version 8fcc4de
