### ISSUE TITLE
[Survey] It would be helpful to sort the Respondents table by Date (descending).

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#922]
Now if the user needs to know the date when the last respondent completed the survey she/he must navigate to the last page. The list of respondents can be downloaded but this action spends more time.

<img width="1477" alt="screen shot 2017-04-24 at 12 33 56 pm" src="https://cloud.githubusercontent.com/assets/518152/25345140/9b2ab308-28ea-11e7-8eff-8613c88e7f60.png">

**Comment by waj** [comment]
Let's allow sorting by either phone number or date by clicking on the columns

**Comment by mmuller** [comment]
Working properly in version 0.9.0
