### ISSUE TITLE
[Quiz] Phone call column of responses displays incorrect error message

### ISSUE THREAD

**Issue by fgasperij** [instedd/ask#925]
Steps to reproduce:

1. Create a new Questionnaire
2. Go to any multiple choice step.
3. Add a response and fill the Response, SMS and Phone call columns with the same letter.
4. Click outside of the response table.

Expected: the Phone call field appears as invalid and the hover shows an error message indicating that the character entered in the field is invalid.

Got: an error message saying that the field is blank.

**Comment by fgasperij** [comment]
![Uploading Screen Shot 2017-04-24 at 2.41.14 PM.png…]()

**Comment by fgasperij** [comment]
![screen shot 2017-04-24 at 2 41 14 pm](https://cloud.githubusercontent.com/assets/1685226/25350740/7e8bb8b6-28fc-11e7-9739-61af1886448d.png)

**Comment by mmuller** [comment]
Working properly in version dafd799
