### ISSUE TITLE
[Collaborators] Editors don't have access to downloading all Respondents CSV 

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#928]
Version: 0.8.1-dev-bb5bb2e (build 2077)

As an Editor Collaborator
1. Open a survey
2. Go to Respondents
3. Click on the Download icon

Obtained:
The Editor only has access to download `Survey results` and `Disposition History` csv

Expected:
The user should be able to download all available respondent csv

**Comment by asterite** [comment]
No, in https://github.com/instedd/ask/issues/690 it says the incentives CSV is only shown for the project admin (owner).
