### ISSUE TITLE
Allow customization of mobile app colors

### ISSUE THREAD

**Issue by waj** [instedd/ask#929]
https://projects.invisionapp.com/d/main#/console/8374235/230465184/preview

**Comment by lmatayoshi** [comment]
@Mscebba , apply style to _Mobile web settings_ according to the mockup

- [ ] Put both input for Primary and Secondary color in the same line. Next to each other
- [ ] Draw line separators
- [ ] Check style for 'Style' and 'Messages' <h5> elements
(Ignore the lack of texts below each input. They aren't being displayed at the moment. Example: 'This message will be sent in an SMS with a link to the survey')

<img width="1418" alt="screen shot 2017-05-05 at 4 08 18 pm" src="https://cloud.githubusercontent.com/assets/8591752/25760495/63de3ffc-31ad-11e7-973a-65219d6c98c2.png">

**Comment by mmuller** [comment]
Working properly in version 0.9.0
