### ISSUE TITLE
The option 'End survey' of Skip logic doesn't work for Flag steps.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#932]
Found in version d6a51e4

<img width="1160" alt="screen shot 2017-04-25 at 4 04 09 pm" src="https://cloud.githubusercontent.com/assets/518152/25404141/2ca90722-29d5-11e7-9b3f-83cf2b28ad3e.png">
<img width="1491" alt="screen shot 2017-04-25 at 4 04 01 pm" src="https://cloud.githubusercontent.com/assets/518152/25404142/2caba504-29d5-11e7-9e71-47e6d5945972.png">
<img width="1020" alt="screen shot 2017-04-25 at 4 03 55 pm" src="https://cloud.githubusercontent.com/assets/518152/25404145/2cb7d78e-29d5-11e7-960c-849b5dee68cb.png">
<img width="954" alt="screen shot 2017-04-25 at 4 03 47 pm" src="https://cloud.githubusercontent.com/assets/518152/25404144/2cb7398c-29d5-11e7-95e2-cc07f691dbc4.png">

**Comment by asterite** [comment]
Fixed in https://github.com/instedd/ask/commit/4ec822dd5f49a5bc18413607216727242c0d0dda

**Comment by mmuller** [comment]
Working properly in version dafd799
