### ISSUE TITLE
In a Numeric step when the Variable name is empty the responses to that question will not be displayed.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#943]
Found in version dafd799

Reproduce steps:
Create a Questionnaire `Q`.
Add a Numeric step `Foo` to `Q`.
Don't fill the field `Variable name`.
Fill the required fields.
Create a Survey for the Questionnaire `Q`.
Start the Survey.
As respondent answer the question `Foo`. 
As owner of the Survey navigate to the `Respondents` tab.
Observe the information displayed in the table.
Download the `Survey results` CSV and observe the information included in the file.

Obtained:
The answer of the respondent is not displayed.

Expected:
If the `Variable name` is not required the answers displayed in the `Respondents` should not depend on the `Variable name`.
If the answers displayed in the `Respondents` depends on the `Variable name` this value should be required.

<img width="871" alt="screen shot 2017-04-27 at 8 48 19 pm" src="https://cloud.githubusercontent.com/assets/518152/25508786/e19a3d98-2b8a-11e7-97af-3c815a8c6dff.png">
<img width="860" alt="screen shot 2017-04-27 at 8 48 02 pm" src="https://cloud.githubusercontent.com/assets/518152/25508785/e197570e-2b8a-11e7-8bef-7634f0e8296d.png">

**Comment by asterite** [comment]
As far as I know, the "Variable name" field is used exactly for that: if you choose a name, you store that value with that name. If you don't fill it it's because you are not interested in the value (maybe the value is used for skip logic, though). Not a bug for me.

**Comment by mmuller** [comment]
@asterite Ok, so there is a bug with the multiple choice step. In a Multiple Choice step when the Variable name is empty the responses to that question is included in the Respondents table.

**Comment by nditada** [comment]
Yes, Ary is correct, that was the original intention at least. But yes, it should be consistent with the behavior in multiple choices.

**Comment by mmuller** [comment]
I logged the issue with the Multiple Choice step as #950
