### ISSUE TITLE
[Mobile Web] Do not set or validate the respondent cookie on the index action

### ISSUE THREAD

**Issue by waj** [instedd/ask#944]
Sometimes the URL might be accessed before the user actually opens the survey (iOS tries to get the page title and icon, Slack fetches the page as well to unfurl). If this happens, by the time the user opens the link he/she cannot access the page because the cookie is not set in the browser, but already generated and stored server side.

Let's do the cookie validation only in the XHR requests (`get_step` and `send_reply`).

**Comment by mmuller** [comment]
Working properly in version 8fcc4de
