### ISSUE TITLE
New step created above the fold if previous step was expanded

### ISSUE THREAD

**Issue by nditada** [instedd/ask#945]
Steps to reproduce

1. In the quiz editor, create a new question and leave it expanded.
2. Scroll down to the "Add new step" link and click it. 

Result:
The new step is created above the fold and there is no visible indication to the user. The experience is as if the link did nothing.

Expected:
The new step is created in the fold and the user can see the new expanded step editor.

**Comment by nekron** [comment]
Let's add some animations to the folding and unfolding of the steps.

Add an automatic scroll to the step header after creation, but just before the unfold of the new step.

**Comment by asterite** [comment]
I fixed this by scrolling to the newly created step when clicking "Add step".

Additionally, when expanding a step or a settings section (SMS settings, etc.), the window scrolls to.

I don't think an "expanding" animation is needed, the scrolling is a good enough hint, but if it's needed please open a separate issue.

**Comment by mmuller** [comment]
Working properly in version 0.9.0
