### ISSUE TITLE
Footer is horizontally displaced in safari

### ISSUE THREAD

**Issue by nekron** [instedd/ask#948]
![screen shot 2017-05-02 at 1 58 41 pm](https://cloud.githubusercontent.com/assets/957103/25629364/ad63978c-2f3f-11e7-937c-e2fbc33618c6.png)
![screen shot 2017-05-02 at 1 58 57 pm](https://cloud.githubusercontent.com/assets/957103/25629365/ad64ff64-2f3f-11e7-80e1-dd523eacf67f.png)

**Comment by mmuller** [comment]
Working properly in version 5abc942
