### ISSUE TITLE
In a Multiple Choice step when the Variable name is empty the responses to that question are displayed in the Respondents table.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#950]
Found in version dafd799

Reproduce steps:
Create a Questionnaire `Q`.
Add a Multiple Choice step `Foo` to `Q`.
Don't fill the field `Variable name`.
Fill the required fields.
Create a Survey for the Questionnaire `Q`.
Start the Survey.
As respondent answer the question `Foo`. 
As owner of the Survey navigate to the `Respondents` tab.
Observe the information displayed in the table.
Download the `Survey results` CSV and observe the information included in the file.

Obtained:
The answer of the respondent is displayed.

Expected:
If the `Variable name` is empty the answers to that question should not be displayed in the `Respondents` table.

**Comment by pmallol** [comment]
Ok in Version: 0.9.0 (build 2357)
