### ISSUE TITLE
Add 'About surveda' link in User Menu

### ISSUE THREAD

**Issue by lmatayoshi** [instedd/ask#952]
https://projects.invisionapp.com/d/main#/console/8374235/231386807/preview

@jkicillof said: Clicking in the link should open the home page in a new tab

**Comment by nekron** [comment]
Use `explicit=true` to force the home not to redirect to the projects page.

Show the user menu on top, and hide the login options.

**Comment by asterite** [comment]
I did this but I just hid the "Login" and "Sign up" buttons. There's no design for showing a menu in the landing page, and the user can always go back to the original tab that opened the home page. Please open a separate issue if you want that to be implemented (though I see no strong reason to do that).

**Comment by mmuller** [comment]
Working properly in version 0.9.0
