### ISSUE TITLE
Remove hardcoded texts from mobile web forms

### ISSUE THREAD

**Issue by nekron** [instedd/ask#953]
https://github.com/instedd/ask/commit/bb4c5603f90d#diff-82ffbebb896df1f26d01e1e8fc2dcf1aR23

**Comment by waj** [comment]
Let's remove the hardcoded text (again). If we want a label we need to add a setting in the questionnaire.

**Comment by pmallol** [comment]
Ok in Version: 0.9.0 (build 2357)
