### ISSUE TITLE
[Mobile Web] Quota completed message should not have a "next" button

### ISSUE THREAD

**Issue by nekron** [instedd/ask#954]
Hide the button according to the survey progress. If it's the last step (quota or regular) hide the "next" button.

Currently the progress is only being used to display the bar at the top. Also use it to show/hide the next button.

Send the proper progress for the quota completed message.

When sending the progress during the normal flow, add (count) an extra step to account for the Thank you message, if present.

Use the same approach for the Thank you message, do not treat it as a special case.

Version: 8fcc4de

<img width="536" alt="screen shot 2017-05-05 at 4 46 18 pm" src="https://cloud.githubusercontent.com/assets/957103/25762128/eed55252-31b3-11e7-8e37-7151c8cbc76e.png">

**Comment by pmallol** [comment]
Ok in Version: 0.9.0 (build 2357)
