### ISSUE TITLE
[Questionnaire] Last Saved Time in the future

### ISSUE THREAD

**Issue by steesdale** [instedd/ask#958]
In production (7.3) 

The saved time for a questionnaire was "5 hours from now"

![screen shot 2017-05-04 at 3 06 47 pm](https://cloud.githubusercontent.com/assets/3987608/25724172/9c6464a0-30e0-11e7-8989-bfa7eaeb1161.png)

**Comment by steesdale** [comment]
The scheduled time for a survey to go out in production is also not working correctly.   Perhaps it is related.

**Comment by waj** [comment]
Are you sure you have the right timezone set in your computer? I did see this issue but my timezone was incorrect.

**Comment by steesdale** [comment]
Yes I have the correct timezone on my computer.

We are also experience scheduling issues; where surveys are stalling in pending when they should be going out.  I have a hunch it is related to this time issue, as when I open up the scheduling time to be 24hours over multiple days everything works fine.

- Scott

**Comment by nekron** [comment]
The schedule bug is already fixed in staging by #938

**Comment by mmuller** [comment]
Working properly in version 0.9.0
