### ISSUE TITLE
Sort Interactions file by respondent id, time.

### ISSUE THREAD

**Issue by adam704a** [instedd/ask#962]
The default sorting of the interactions files will work in very few situations. More useful would be to sort by respondent id, then timestamp.

**Comment by waj** [comment]
Sorting by respondent id should be enough because every respondent should have a different id.

Please, make sure there is an index in the DB for this.

**Comment by asterite** [comment]
I don't think it's enough, there are multiple entries by respondent (this is the interactions file), so I think we need an index by the two columns (id and timestamp)

**Comment by asterite** [comment]
While trying to implement this I found a bug in `Repo.stream` provided by https://github.com/DavidAntaramian/tributary where using `order_by` with two fields will give duplicate results. The bug can be easily reproduced with this code (try it in the console or better in a new test):

```elixir
%Ask.Channel{name: "a", type: "b"} |> Repo.insert!
%Ask.Channel{name: "b", type: "b"} |> Repo.insert!
%Ask.Channel{name: "b", type: "a"} |> Repo.insert!
%Ask.Channel{name: "a", type: "a"} |> Repo.insert!

x = (from c in Ask.Channel,
  order_by: [c.name, c.type]) |> Repo.stream

Repo.transaction(fn() ->
  x |> Enum.to_list |> IO.inspect
end)
```

The latest version of ecto provides a `Repo.stream` that seems to work well and don't have this bug. However, for this we need to update ecto to that version, but there are a number of breaking changes, [mostly to date/time types](https://github.com/elixir-ecto/ecto/blob/v2.1/CHANGELOG.md#integration-with-elixir-13-calendar-types). In total I have 32 out of 456 tests failing.

I think before making this update we should discuss if we want to introduce a big dependency update in 0.9, thus risking breaking other stuff.

@waj What do you think we should do here?

**Comment by waj** [comment]
Why do we need to sort by two fields? Let's upgrade the dependencies if the version we're using has a bug already solved. We have time to test and fix issues caused by the upgrade.

**Comment by asterite** [comment]
I'll sort by `respondent id` and hope that mysql's sort algorithm is stable then.

**Comment by mmuller** [comment]
Working properly in version 0.9.0
