### ISSUE TITLE
[Survey] When launching a survey, the screen only shows one of the questionnaire names

### ISSUE THREAD

**Issue by asterite** [instedd/ask#965]
The [current design](https://projects.invisionapp.com/d/main#/console/8374235/231391853/preview) has a title that is the name of the survey's questionnaire. That design is old now, because a survey can have multiple associated questionnaires. Update the design to reflect this fact.

**Comment by waj** [comment]
@jkicillof can you describe what to show when there's more than one questionnaire selected?

**Comment by nekron** [comment]
https://projects.invisionapp.com/d/main#/console/8374235/232431824/preview

**Comment by mmuller** [comment]
Now in version cc5d3df the Questionnaire name is not displayed on the Survey's overview.

Screenshot:
<img width="1413" alt="screen shot 2017-06-06 at 12 09 41 pm" src="https://user-images.githubusercontent.com/518152/26837152-104117ec-4ab3-11e7-9a9f-595ae8af1fa5.png">

**Comment by mmuller** [comment]
Working properly in version 0d1e2db
