### ISSUE TITLE
[SurveyWizard] Check height of selector's row

### ISSUE THREAD

**Issue by lmatayoshi** [instedd/ask#967]
https://projects.invisionapp.com/d/main#/console/8374235/231944357/preview

Selector's row should be the same height as rows of selected options.

At the moment:

![selectors_row_heights](https://cloud.githubusercontent.com/assets/8591752/25816202/b876a132-33f9-11e7-9cf9-3a06ef21b1b4.png)

**Comment by pmallol** [comment]
Ok in Version: 0.9.0 (build 2357)
