### ISSUE TITLE
[SuveryWizard] Survey selection is not being marked as completed

### ISSUE THREAD

**Issue by lmatayoshi** [instedd/ask#971]
Steps to reproduce:

- Launch a Survey
- Go to Survey Settings

Expected:
- The percentage of completion should mark 100%

Obtained:
- It marks 75% because mode step is not marked as completed

![incomplete](https://cloud.githubusercontent.com/assets/8591752/25857985/01731cdc-34b1-11e7-8564-6e921ddd1288.png)

**Comment by pmallol** [comment]
Ok in Version: 0.9.0 (build 2357)
