### ISSUE TITLE
[QuestionnaireEditor] Valid color are marked as invalid

### ISSUE THREAD

**Issue by lmatayoshi** [instedd/ask#979]
Steps to reproduce:

- Go to Questionnaire Editor, and set a _mobile web questionnaire_
- Edit primary color in Web Settings. Example #111eee

Expected:
- Primary color should be set and the color should be displayed in the circle

Obtained:
- The color is marked as invalid
![invalid-color-settings](https://cloud.githubusercontent.com/assets/8591752/25963555/14f6c3be-3658-11e7-85b8-c5b7a7a19ce0.png)

**Comment by mmuller** [comment]
Working properly in version 0.9.0
