### ISSUE TITLE
Log in and sign up links are not available.

### ISSUE THREAD

**Issue by fgasperij** [instedd/ask#981]
Go to the application home without being logged in.

Expected: Links to log in and sign up at the top of the page.

Result: No links available.

**Comment by fgasperij** [comment]
![screen shot 2017-05-11 at 4 19 22 pm](https://cloud.githubusercontent.com/assets/1685226/25967791/a49c783a-3665-11e7-912a-81201fa6a953.png)

**Comment by pmallol** [comment]
Ok in Version: 0.9.0 (build 2357)
