### ISSUE TITLE
[mobile web] "Survey already taken" message could easily be in multiple languages

### ISSUE THREAD

**Issue by nekron** [instedd/ask#984]
At that point the respondent already answered the preferred language. It's already used to display the title.

<img width="332" alt="screen shot 2017-05-11 at 5 37 02 pm" src="https://cloud.githubusercontent.com/assets/957103/25970853/84979eb0-3670-11e7-8c43-514324846769.png">

**Comment by asterite** [comment]
I couldn't reproduce this locally, but there was a bug in the Draft component that wouldn't update its value when you switch the current language. So maybe you saw a different text in the editor than what you expected in the form.

I still recommend testing this in the bug bash, but locally it worked fine for me.

**Comment by mmuller** [comment]
Working properly in version 0.9.0
