### ISSUE TITLE
Unexpected error when starting a Survey.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#987]
Version a74ed81

The Survey is started but the error `Sorry, something went wrong` is displayed.

Error log:
https://sentry.io/instedd/ask-stg/issues/271416753/

**Comment by asterite** [comment]
I couldn't reproduce this, but I just pushed a commit that probably fixed a case where this can happen. After redeploy, in the bug bash, please try and see if it still happens.

**Comment by mmuller** [comment]
Working properly in version 0.9.0
