### ISSUE TITLE
Questionnaire editor should only display one mode and language at a time

### ISSUE THREAD

**Issue by nekron** [instedd/ask#992]
Change the current mode toggle to a selection of the current mode with a dropdown to add more modes. Only display one mode at a time.

<img width="1360" alt="add mode 2x" src="https://cloud.githubusercontent.com/assets/957103/26064607/df0fa776-3967-11e7-8e91-f728b3f2fe26.png">
<img width="1360" alt="nyanga 2x" src="https://cloud.githubusercontent.com/assets/957103/26064611/e119f60c-3967-11e7-9126-21fbb963203a.png">

**Comment by mmuller** [comment]
Working properly in version 55aca59
