### ISSUE TITLE
[questionnaire] Grey out unselected modes in questionnaire editor

### ISSUE THREAD

**Issue by nekron** [instedd/ask#995]
Right now, every mode is being displayed with the same color:
<img width="282" alt="screen shot 2017-05-15 at 6 31 43 pm" src="https://cloud.githubusercontent.com/assets/957103/26080401/cd9183ae-399c-11e7-84f2-fe00cab75fef.png">

They should have the same style of the languages:
https://projects.invisionapp.com/d/main#/console/8374235/220137297/preview

**Comment by asterite** [comment]
(by the way, the languages's list design also changed, so this should really be applying the new design to those lists)

**Comment by mmuller** [comment]
Working properly in version 55aca59
